- app/src/main/java/com/dhis2/data/forms/FormFragment.java
- app/src/main/java/com/dhis2/usescases/teiDashboard/eventDetail/EventDetailActivity.java
- app/src/main/res/layout/activity_event_detail.xml
- app/src/main/res/layout/fragment_form.xml
Added sections headers when needed to event details
> Event details Activity

- app/src/main/java/com/dhis2/usescases/login/LoginInteractor.java
- app/src/main/java/com/dhis2/usescases/main/MainPresenter.java
- app/src/main/java/com/dhis2/usescases/syncManager/SyncManagerContracts.java
- app/src/main/java/com/dhis2/usescases/syncManager/SyncManagerFragment.java
- app/src/main/java/com/dhis2/usescases/syncManager/SyncManagerPresenter.java
- app/src/main/res/layout-land/fragment_sync_manager.xml
- app/src/main/res/layout/fragment_sync_manager.xml
Separate de schedules jobs from the manual jobs. All sync jobs are now cancel/stop when user block session and log off.
> changes in syncManager

- app/src/main/java/com/dhis2/data/forms/EventRepository.java
- app/src/main/java/com/dhis2/data/forms/FormFragment.java
- app/src/main/java/com/dhis2/data/forms/FormPresenterImpl.java
- app/src/main/java/com/dhis2/data/forms/FormView.java
Completing an event that has a warningOnComplete Rule Action now alerts the user
> warningOnComplete Rule Action

- app/build.gradle
- app/src/main/java/com/dhis2/MyAppGlideModule.java
- app/src/main/java/com/dhis2/data/qr/QRCodeGenerator.java
- app/src/main/java/com/dhis2/usescases/qrCodes/QrActivity.java
- app/src/main/java/com/dhis2/usescases/qrCodes/QrAdapter.java
- app/src/main/java/com/dhis2/usescases/qrCodes/QrFragment.java
- app/src/main/java/com/dhis2/usescases/qrCodes/QrViewModel.java
- Improved QR renderization and memory
> ANDROAPP-1133

- app/src/main/java/com/dhis2/data/qr/QRCodeGenerator.java
- app/src/main/java/com/dhis2/data/qr/QRjson.java
- app/src/main/java/com/dhis2/usescases/qrCodes/QrActivity.java
- app/src/main/java/com/dhis2/usescases/qrReader/QrReaderContracts.java
- app/src/main/java/com/dhis2/usescases/qrReader/QrReaderFragment.java
- app/src/main/java/com/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
- app/src/main/res/values-es-rES/strings.xml
- app/src/main/res/values/strings.xml
- Attributes QR created separately: 1 QR per 2 Attributes
- Enrollments QR created separately: 1 QR per 2 Enrollments
- Added QR for Relationships
> ANDROAPP-1134

- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- Bug fix: tapping twice on create new TEI
> ANDROAPP-1203

- app/src/main/java/com/dhis2/Bindings/Bindings.java
- app/src/main/res/drawable/photo_temp.xml
- app/src/main/res/layout/activity_event_initial.xml
> Android 1223

- app/src/main/java/com/dhis2/data/service/SyncDataService.java
- app/src/main/java/com/dhis2/data/service/SyncMetadataService.java
- app/src/main/java/com/dhis2/usescases/syncManager/SyncManagerPresenter.java
The sync job now is properly finished upon completion. No more sync are done automatically when performing a manual sync
> fixes sync manager bug

- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/com/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/com/dhis2/usescases/qrReader/QrReaderContracts.java
- app/src/main/java/com/dhis2/usescases/qrReader/QrReaderFragment.java
- app/src/main/java/com/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
- app/src/main/java/com/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/com/dhis2/usescases/syncManager/SyncManagerFragment.java
- app/src/main/java/com/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/com/dhis2/usescases/teiDashboard/adapters/NotesViewholder.java
- app/src/main/res/values/strings.xml
- Added control in QR reader to check if "Identification" QR was read before trying to save data.
- Added control in CatCombo filter to check not only CatCombo uid is not equal to default uid, but also display name is not equal to "default"
> ANDROAPP-1326 + ANDROAPP-1343

- app/src/main/java/com/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/com/dhis2/data/forms/dataentry/DataValueStore.java
- app/src/main/java/com/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/com/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/com/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
All timestamps on event and enrollment are set with 00:00:00.000
Changes the order of how the sync down and sync up are executed
> fixes dates from events and enrollments on creation 

- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/com/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- Added check for Program "accessDataWrite" in EventInitial to prevent editting Events.
- Added check for Program "accessDataWrite" in ProgramEventDetail to prevent adding new Events.
> ANDROAPP-1363

- app/src/main/java/com/dhis2/data/forms/dataentry/ProgramStageRepository.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/com/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/com/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/com/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
- Added Program access data write permissions for open events.
> ANDROAPP-1363-fix

- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/res/layout/fragment_form.xml
fixes date dailog appear when saving a TEI
> fixes date dailog appear when saving a TEI

- .gitignore
- .gitmodules
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.java
- app/src/main/java/org/dhis2/usescases/main/MainActivity.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/RelationshipFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/mobile/TeiDashboardMobileActivity.java
Added ability to change orientation of app when used on a tablet device
> Screen rotation

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/utils/Constants.java
Fixes the report date to use on autogenerated events depending on server configuration.
> autogenerate events on Enrollment

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Fixes that search shows local TEI when displayInList is true even if it have a mininum of attributes required to search.
> Display in list

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/TEIDataFragment.java
Now the app triggers the popup asking the user if they which to create another event when that event was completed.
> New events does not trigger the 'Ask user to create new event when stage is complete'

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Fixes issue that didn't took into consideration the standard interval days when auto generating a new event
> Standard interval days issue

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryInteractor.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/mobile/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/utils/custom_views/FormBottomDialog.java
- app/src/main/res/layout/activity_event_detail.xml
- app/src/main/res/layout/form_bottom_dialog.xml
- app/src/main/res/layout/fragment_tei_data_card_front.xml
- 4.4 tablet dashboard fix
- bugfixing
> - view only checks

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- buildsystem/dependencies.gradle
Added the tracked Entity type Attributes from the new table for the search form when its required.
> Added the tracked Entity type Attributes

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.java
- app/src/main/res/layout/form_bottom_dialog.xml
- app/src/main/res/values/strings.xml
> ANDROAPP-1797,ANDROAPP-1797

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
fixes random weird stuff happening on fields when scrolling on data entry form in enrollments and/or events
> [Androapp-1815] - Random behavior when navigating fields of a survey

- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/mobile/TeiDashboardMobileActivity.java
Fixes issue where when an event was completed right after enrolling, it didn't ask to complete program if it was configured to do so.
> ANDROAPP-1949

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/EnrollmentStatusStore.java
> show warning/error not displaying evaluated expression

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
Adds useCodeForOptionSet setting in enrollments
> androapp-1793

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
Fixes crash when showing warning when a program rule changed a data element to a a mandatory field
> androapp-1816

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
> 1.2.1 bugfixing

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/res/values/strings.xml
> ANDROAPP-1771

- app/build.gradle
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- buildsystem/dependencies.gradle
orderByEventDate for event list
> SDK v0.15.1

- app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueActivity.java
- app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueContracts.java
- app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValuePresenter.java
Added error dialog when error while reserving values from settings screen
> Androapp 1965

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryFragment.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/RowAction.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/res/layout-land/activity_event_initial.xml
- app/src/main/res/layout-w600dp-land/activity_event_initial.xml
- Fixed crashed on landscape when creating a new event in tablet
> 1.2.3 bugfixing

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewHolder.java
- app/src/main/java/org/dhis2/utils/custom_views/FormBottomDialog.java
- app/src/main/res/layout/form_bottom_dialog.xml
- app/src/main/res/layout/section_selector.xml
- app/src/main/res/values/strings.xml
- improved flow for finishing event data entry
- relationships bugfixing
- search and register bugfixing
- login bugfixing
> ANDROAPP-1656 and bugfixing

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/main/program/SyncConflictAdapter.java
- app/src/main/java/org/dhis2/usescases/main/program/SyncConflictHolder.java
- app/src/main/java/org/dhis2/usescases/main/program/SyncStatusDialog.java
- app/src/main/java/org/dhis2/usescases/syncManager/ErrorViewHolder.java
- app/src/main/java/org/dhis2/utils/CustomItemDecorator.kt
- app/src/main/java/org/dhis2/utils/WebViewActivity.kt
- app/src/main/res/layout/activity_webview.xml
- app/src/main/res/layout/item_sync_conflict.xml
- app/src/main/res/layout/sync_bottom_dialog.xml
- app/src/main/res/values/strings.xml
ANDROAPP-2159 programs state and sync conflict dialog in home
> ANDROAPP-1240 fix

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/res/values/strings.xml
> Rules Performance Improvement and description dialog label changed

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.java
- app/src/main/java/org/dhis2/utils/TestingCredential.java
- app/src/main/res/raw/testing_credentials.json
- app/src/main/res/values/strings.xml
> Updated login testing credentials

- app/src/main/java/org/dhis2/data/forms/dataentry/AttributeValueStore.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataValueStore.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
- app/src/main/res/layout-land/activity_login.xml
- rules
- login tablet buttons
- tei count
> 1.3.0 bugfixing

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Closes event if mandatory fields are not filled up when trying to save event
> androapp-1656

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/java/org/dhis2/utils/custom_views/FormBottomDialog.java
- app/src/main/res/layout/custom_dialog.xml
- Show complete enrollment dialog fix
- Custom dialog with scrollable content
> ANDROAPP-2181

- app/src/main/java/org/dhis2/data/metadata/MetadataRepository.java
- app/src/main/java/org/dhis2/data/metadata/MetadataRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardProgramModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/TeiDataDetailPresenter.java
- app/src/main/res/layout/activity_teidata_detail.xml
- app/src/main/res/layout/fragment_tei_data_card_front.xml
active/selected enrollment uses and shows correct Organisation Unit in the dashboard and tei details
> Androapp-2114

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
Removes queries from DataSetTable's usecase. Updates with sdk modules and refactored code
> Dataset Modules

- app/src/main/java/org/dhis2/data/forms/dataentry/AttributeValueStore.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataValueStore.java
- app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.java
- app/src/main/java/org/dhis2/utils/DatePickerUtils.java
- app/src/main/java/org/dhis2/utils/custom_views/AgeView.java
- app/src/main/java/org/dhis2/utils/custom_views/DateTimeView.java
- app/src/main/java/org/dhis2/utils/custom_views/DateView.java
- app/src/main/res/layout/custom_dialog.xml
- app/src/main/res/layout/item_search_tracked_entity.xml
> 1.3.0 design review

- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListActivity.java
Fixes programs-to-enroll list from duplicating when setting the app on background on the devices
> androapp-2125

- app/src/main/java/org/dhis2/utils/custom_views/OrgUnitDialog_2.java
Add orgUnit dialog class that was not committed earlier
> OrgUnit Dialog

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/data/nfc/NFCManager.kt
- app/src/main/java/org/dhis2/data/qr/QRCodeGenerator.java
- app/src/main/java/org/dhis2/data/qr/QRInterface.java
- app/src/main/java/org/dhis2/usescases/main/MainActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/nfc_data/NfcDataWriteActivity.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
- app/src/main/res/drawable/ic_nfc.xml
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/item_program_event.xml
- app/src/main/res/menu/main_menu.xml
- app/src/main/res/values/themes.xml
> 1.3.0 redesign

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionContract.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepository.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
> ANDROAPP-2224

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
Fixes issue when input field refocus when programRule assagina value to another field
> androapp-2219

- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/java/org/dhis2/data/forms/FormPresenterImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/AttributeValueStore.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryFragment.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenterImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetAdapter.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetDialog.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetOnClickListener.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetPopUp.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetView.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetViewHolder.java
- OptionSets performance refactor
- unique value fix
> fix: 1.3.0_beta bugfixing

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
value type string values now must have format yyyy-MM-dd
ANDROAPP-2264
> fix(programRules): changed string value of age value type

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventSectionHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/SectionSelectorAdapter.java
- app/src/main/res/layout/item_section_selector.xml
> fix(event sections): Fix section indicator

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/RulesActionCallbacks.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl_backup.java
BREAKING CHANGE: The popup to display errors was showing in every section. Now it will only be displayed when trying to finish the form. The popup will open the section containing the first error field.
ANDROAPP-2262
> fix(showError): Error popup showing in every section

- app/src/main/res/layout/fragment_tei_data.xml
FAB button options not showing completely on small devices.
Jira Issue: [ANDROAPP-2237]( https://jira.dhis2.org/browse/ANDROAPP-2237)
> fix(fragment_tei_data.xml): FAB button options not showing completely on small devices.

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Fixes data element order on the dataset table.
Jira Issue: [ANDROAPP-2106](https://jira.dhis2.org/browse/ANDROAPP-2106)
> fix(DataValueRepository): fixes data element order

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/utils/custom_views/AgeView.java
- app/src/main/java/org/dhis2/utils/custom_views/CoordinatesView.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
- app/src/main/java/org/dhis2/utils/custom_views/DateTimeView.java
- app/src/main/java/org/dhis2/utils/custom_views/DateView.java
- app/src/main/java/org/dhis2/utils/custom_views/TimeView.java
Clear source field when "Show error" program rule is triggered
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2286
> feat: clear field when error is triggered

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Stop animation when search is done && fix problem can't type on search fields
Jira issue: https://jira.dhis2.org/browse/ANDROAPP-2278
>  fix(SearchTEActivity): search when create relationship 

- app/src/main/java/org/dhis2/data/forms/FormModule.java
- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryModule.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterImpl.java
Program rules initialization issues prevented program indicators to show.
jira Issue: [ANDROAPP-2216](https://jira.dhis2.org/browse/ANDROAPP-2216)
> fix(program indicators): Program Indicators did not show  on dashboard

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetView.java
- app/src/main/java/org/dhis2/utils/custom_views/orgUnitCascade/OrgUnitItem.java
Bug when content and data are null.
Bug. It is no cleaning the field of option set when set an error
https://jira.dhis2.org/browse/ANDROAPP-2286
> fix: Bug when content and data are null.

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
BREAKING CHANGE Before saving a value there is a new check to ensure the field section is not hidden.
[jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2243)
> fix(programRules): Assigning values to a field in a hidden section

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/utils/AuthorityException.java
- app/src/main/res/menu/dashboard_menu.xml
- app/src/main/res/values/strings.xml
[ANDROAPP-1665](https://jira.dhis2.org/browse/ANDROAPP-1665)
> feat(TEI deletion): Add option to delete TEI or Enrollment

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/res/layout-land/activity_event_initial.xml
Bug share button when a new event is being creating
> fix: Bug share button when a new event is being creating

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryFragment.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetDialog.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetPopUp.java
Validates if dialog is already shown and removes unused imports of this class.
> fix(OptionSetDialog): Validates if dialog is already shown.

- app/src/main/java/org/dhis2/utils/custom_views/OptionSetPopUp.java
Bug null pointer in OptionSetPopUp
> fix: Bug null pointer in OptionSetPopUp

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/utils/custom_views/OrgUnitDialog_2.java
ANDROAPP-2294 App crashes during organisation unit selection for enrolling person from one program to another
https://jira.dhis2.org/browse/ANDROAPP-2294
> fix: App crashes during organisation unit selection for enrolling person from one program to another

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
ANDROAPP-2264 Age data type in program rules not rendering correctly
https://jira.dhis2.org/browse/ANDROAPP-2264
> fix: Age data type in program rules not rendering correctly

- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
Do not get events with state TO_DELETE in the count of events
Jira Issue: [ANDROAPP-2292](https://jira.dhis2.org/browse/ANDROAPP-2292)
> fix(HomeRepositoryImp): show correct number of events when deleting one

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/res/values/strings.xml
Only users with the correct authority can re-open completed events
> feat(EventCapture): Only users with the correct authority can re-open completed events

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/custom_views/FormBottomDialog.java
- app/src/main/res/layout/form_bottom_dialog.xml
Jira issue: [ANDROAPP-2282](https://jira.dhis2.org/browse/ANDROAPP-2282)
>  fix(EventCapture): show only mandatory warning when is able to complete

- app/src/main/res/menu/dashboard_menu.xml
change icon to delete enrollment
https://jira.dhis2.org/browse/ANDROAPP-1665
> fix: change icon to delete enrollment

- app/src/main/java/org/dhis2/utils/custom_views/orgUnitCascade/OrgUnitItem.java
Improves performance in the Org Unit Cascade Dialog, when there are many options in the different levels.
> perf(OrgUnitCascadeDialog): Org Unit Cascade selector

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
Performs null validation on Field parameter of rule actions
> fix(RulesRepository): Performs null validation on Field parameter of RuleAction

- app/build.gradle
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/data/service/ReservedValuesWorker.java
- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/org/dhis2/data/service/files/FilesWorker.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventInitialFragment/EventCaptureInitialFragment.java
- app/src/main/java/org/dhis2/usescases/sync/SyncActivity.java
- app/src/main/java/org/dhis2/usescases/sync/SyncPresenter.java
- app/src/main/java/org/dhis2/usescases/syncManager/SyncManagerFragment.java
- app/src/main/java/org/dhis2/usescases/syncManager/SyncManagerPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/utils/SyncUtils.java
- buildsystem/dependencies.gradle
- SDK 0.17.1
- androidX work manager dependency update
- Fixed enrollment deletion bug
> feat(SDK): Updated SDK

- app/src/main/java/org/dhis2/usescases/jira/JiraViewModel.kt
- app/src/main/java/org/dhis2/utils/custom_views/DateTableView.java
- app/src/main/java/org/dhis2/utils/custom_views/DateTimeTableView.java
- app/src/main/java/org/dhis2/utils/custom_views/TimeTableView.java
> fix: Bug compiling

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataTableModel.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
User is able to re-open and edit an approved record
Fixes because of updated sdk/develop as well.
https://jira.dhis2.org/browse/ANDROAPP-2156
> feat: User is able to re-open and edit an approved record

- app/src/main/java/org/dhis2/data/forms/dataentry/DataValueStore.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
- Fixed crash when validating integer values
- Fixed bug preventing event to be updated
> fix: 1.3.0 bugfixing

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
Sync Aggegates data
https://jira.dhis2.org/browse/ANDROAPP-1186
> fix: Sync Aggegates data

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateHolder.java
- app/src/main/java/org/dhis2/utils/custom_views/CoordinatesView.java
Allows user to input latitude and location values in the coordinate value type view.
> fix(CoordinateView): Allows user to input latitude and location values in the coordinate value type view.

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
- tableview/src/main/java/com/evrencoskun/tableview/adapter/AbstractTableAdapter.java
> feat(dataSets): Move scale button to top header

- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.java
Program list now includes tracker and aggregates
> feat(ProgramPresenter): Program list now includes tracker and aggregates

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
Crash into the select of approval
https://jira.dhis2.org/browse/ANDROAPP-2156
> fix: crash into the select of approval

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Add the "All" Authority to permit to reopen completed events
> feat(EventCapture): Add the "All" Authority to permit to reopen completed events

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
> fix(reservedValues): Enrollment should be blocked if rv is empty

- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardProgramModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java
Sorts programs lists throughout the app alphabetically
> fix(Programs): Sorts programs lists throughout the app alphabetically

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
Do nor block data entry on TEI form when enrollment is completed or deactivated
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2246
> fix(EnrollmentRepository): do not block TEI form 

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
- app/src/main/res/values/strings.xml
> fix(forms): Resolve bugs with fields

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
> feat: Remove create event button if all catOptions have no writeAccess

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/utils/ValidationUtils.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
- app/src/main/res/layout/fragment_settings.xml
- app/src/main/res/layout/settings_sms.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
> feat(dataEntry): Added new validations for text data entry

- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/custom_views/CoordinatesView.java
- app/src/main/java/org/dhis2/utils/custom_views/FormBottomDialog.java
- app/src/main/res/layout/form_bottom_dialog.xml
ANDROAPP-2301
ANDROAPP-2302
ANDROAPP-2306
ANDROAPP-2308
ANDROAPP-2310
> fix: Bugfixing

- app/src/main/java/org/dhis2/utils/ValidationUtils.java
Fixes fieldviewmodel's validation
> fix(ValidationUtils): Fixes fieldviewmodel's validation

- app/src/main/java/org/dhis2/data/forms/dataentry/ProgramAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
- app/src/main/res/layout/spinner_program_layout.xml
Removes deprecated ProgramModel class from search usecase
> refactor(Search):  Removes deprecated ProgramModel class from search usecase

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
Removes deprecated Models classes and removes SQL queries from Search usecase
> refactor(Search): Removes deprecated Models classes and removes SQL queries from Search usecase

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryDiffCallback.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenterImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/RulesActionCallbacks.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetDialog.java
- app/src/main/java/org/dhis2/utils/custom_views/OptionSetPopUp.java
Implemented rogram rule show option group and some fixes in kind of program rule: hide option group and hide option.
https://jira.dhis2.org/browse/ANDROAPP-2271
> feat: Program rule show option group

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Can search by tracked entity type when a program is not selected
> feat(Search): Can search by tracked entity type when a program is not selected

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Handle just last button submit
> feat: create button submit

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
Related to [Androsdk 901](https://github.com/dhis2/dhis2-android-sdk/pull/929)
> feat: Refactor DataSetReport -> DataSetInstance

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
ANDROAPP-2156 Remove query and set module to get approvals
https://jira.dhis2.org/browse/ANDROAPP-2156
> fix: Remove query and set module to get approvals

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/metadata/MetadataRepository.java
- app/src/main/java/org/dhis2/data/metadata/MetadataRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardProgramModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/DashboardProgramAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/DashboardProgramViewHolder.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/EventAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/EventViewHolder.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/TeiDataDetailModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/TeiDataDetailPresenter.java
- app/src/main/res/layout/activity_teidata_detail.xml
- app/src/main/res/layout/fragment_tei_data.xml
- app/src/main/res/layout/fragment_tei_data_card_front.xml
- app/src/main/res/layout/item_dashboard_program.xml
- app/src/main/res/layout/item_event.xml
Removes metadata repository from TEI and TEI detail dashboards presenters
> refactor: Removes metadata repository from TEI and TEI detail dashboards presenters

- app/src/main/java/org/dhis2/data/metadata/MetadataRepository.java
- app/src/main/java/org/dhis2/data/metadata/MetadataRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryInteractor.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/res/layout-land/activity_event_initial.xml
- app/src/main/res/layout/activity_event_initial.xml
Metadata repository and Event initial and summary presenters
> refactor: Metadata repository and Event initial and summary presenters

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/utils/ValueUtils.java
- app/src/main/res/layout/item_search_relationship_tracked_entity.xml
- app/src/main/res/layout/item_search_tracked_entity.xml
Removes Models from search usecase
> refactor: Removes Models from search usecase

- app/src/main/java/org/dhis2/data/qr/QRCodeGenerator.java
- app/src/main/java/org/dhis2/usescases/qrCodes/QrAdapter.java
- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderContracts.java
- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderFragment.java
- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
Removes Models from QR classes
> refactor: Removes Models from QR classes

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenterImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/ProgramStageRepository.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.java
Removes models from ProgramStage, RulesRepository, DataEntry usecases
> refactor: Removes models from ProgramStage, RulesRepository, DataEntry usecases

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryPresenterImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/ProgramStageRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventSectionHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/SectionSelectorAdapter.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.java
Removes models from EventCapture usecase
> refactor: Removes models from EventCapture usecase

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/EventRepository.java
- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/java/org/dhis2/data/forms/FormPresenter.java
- app/src/main/java/org/dhis2/data/forms/FormPresenterImpl.java
- app/src/main/java/org/dhis2/data/forms/FormRepository.java
- app/src/main/java/org/dhis2/data/forms/FormView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EventsRuleEngineRepository.java
- app/src/main/java/org/dhis2/usescases/qrCodes/QrAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/EnrollmentStatusStore.java
Removes models from dataEntry Repositories and form usecase
> refactor: Removes models from dataEntry Repositories and form usecase

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/EventRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/EnrollmentStatusEntryStore.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/EnrollmentStatusStore.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/TeiDataDetailModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/TeiDataDetailPresenter.java
Adds ability to add enrollments with featureType Point
> refactor: Adds ability to add enrollments with featureType Point

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/EnrollmentStatusStore.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/TeiDataDetailPresenter.java
Adds GeometryHelper methods calls
> feat: Adds GeometryHelper methods calls

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
Related to https://github.com/dhis2/dhis2-android-sdk/pull/945
> [ANDROSDK-640] Adapt to androsdk-640

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateHolder.java
- app/src/main/java/org/dhis2/utils/custom_views/CoordinatesView.java
- buildsystem/dependencies.gradle
Fixes issue that coordinates where save in db in the wrong order.
> fix(Coordinates): Fixes issue that coordinates where save in db in the wrong order.

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.java
- app/src/main/java/org/dhis2/utils/OrgUnitUtils.java
- app/src/main/java/org/dhis2/utils/custom_views/OrgUnitDialog_2.java
BREAKING CHANGE: Changed way to get orgUnits to avoid unnecessary waiting
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2317
> fix: avoid to show message that there are no orgunits for event date

- app/src/main/java/org/dhis2/utils/custom_views/DateDialog.java
Fixed instance creation in DateDialog.java. If instance is created we recreated that.
> Data set date dialog fixed

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValuePresenter.java
Solves [ANDROSDK-905](https://jira.dhis2.org/browse/ANDROSDK-905)
> feat: [ANDROSDK-905] Adapt reservedValue calls

- app/build.gradle
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/MainActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/custom_views/PictureView.java
- app/src/main/res/layout/form_picture.xml
- app/src/main/res/layout/form_picture_accent.xml
- form field layouts
- Search online
- DB exporter test
> fix: Form field layouts refactor and bugfixing

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
User could modify dataElement value when it has a error.
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2342
> fix: allow to modify wrong value when error is made

- app/src/main/java/org/dhis2/data/forms/FormFragment.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2337
> fix: allow user to create a new TEI when adding a relationship

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/OrgUnitUtils.java
> fix: Org unit filter not showing ou list

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/OrgUnitUtils.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl_backup.java
The program rule action was not being created with the correct parameters
ANDROAPP-2349
> fix: Program Rule Hide option bugfixing

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/OrgUnitUtils.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl_backup.java
Reverts dhis2/dhis2-android-capture-app#762
> Revert "fix: Program Rule Hide option bugfixing"

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryFragment.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- app/src/main/java/org/dhis2/utils/custom_views/CustomTextView.java
- app/src/main/res/layout/custom_long_text_view.xml
- app/src/main/res/layout/custom_long_text_view_accent.xml
- app/src/main/res/layout/custom_text_view.xml
- app/src/main/res/layout/custom_text_view_accent.xml
> fix: Next in text fields for enrollment forms not working

- app/src/main/java/org/dhis2/utils/custom_views/AgeView.java
- app/src/main/res/layout/dialog_age.xml
Jira Issues : https://jira.dhis2.org/browse/ANDROAPP-2351 and https://jira.dhis2.org/browse/ANDROAPP-2348
> fix: adds a dialog to modify years/months/days of age field

- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DateRangeInputPeriodModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/OrgUnitUtils.java
- app/src/main/java/org/dhis2/utils/custom_views/OrgUnitDialog.java
- app/src/main/res/layout/dialog_orgunit.xml
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-1857
> feat: adds search in orgunit selector and get it faster

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
preselection when there is only one orgUnit after setting a date in event initial screen
> fix: ou preselection

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/EventRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/ProgramStageRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactory.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/file/FileViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/unsupported/UnsupportedViewModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/res/values/strings.xml
https://jira.dhis2.org/browse/ANDROAPP-1236
> feat: Auto-formatting fields

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
https://jira.dhis2.org/browse/ANDROAPP-1236
> fix: Auto-formatting fields removing on search mode

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
https://jira.dhis2.org/browse/ANDROAPP-2326   
**Bug fix. Show map when TEI has coordinates**
> fix: ANDROAPP-2326 Hide TEI when is deleted.

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateHolder.java
- app/src/main/java/org/dhis2/data/service/files/FilesWorker.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/utils/FileResourcesUtil.java
- app/src/main/java/org/dhis2/utils/maps/GeometryUtils.kt
Minor bugfixing:
- Coordinates requeries to set featureType
> feature: Add TEI profile images to map

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureHolder.java
- app/src/main/java/org/dhis2/data/service/files/FilesWorker.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentContract.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/utils/FileResourcesUtil.java
- app/src/main/java/org/dhis2/utils/custom_views/PictureView.java
- app/src/main/java/org/dhis2/utils/maps/GeometryUtils.kt
- app/src/main/res/xml/file_paths.xml
> feat: Support for TEI profile image (and fields with valueType IMAGE)

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/SyncStatusDialog.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/eventDetail/EventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiDataDetail/EnrollmentStatusStore.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
Remove all method called withAllChildren
> feat: remove all method called withAllChildren

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- Avoid setting rule variables when dataElement and Attribute are null or do not exist
- Fixed order of dataELements in sections
- Fixed rendering of LONG_TEXT in search screen
> fix: Event forms bugfixing

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- ANDROAPP-2338
- Keyboard for text fields fix
> fix: Autocomplete rendering type

- app/src/main/java/org/dhis2/data/service/files/FilesWorker.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/utils/FileResourcesUtil.java
- app/src/main/java/org/dhis2/utils/custom_views/PictureView.java
- Refactor tei profile picture
- Refactor file worker
> refactor: TEI profile image

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
> fix: DE not included in any section appears in all of them

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/res/xml/file_paths.xml
Fixes crash when taking a picture from the camera.
> fix: Fixes crash when taking a picture from the camera.

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/main/MainActivity.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/SyncStatusDialog.java
- app/src/main/java/org/dhis2/usescases/sms/SmsSendingService.java
Fixes from aggregates. List of dataValues and sync granular icon.
**Also. Bugs analytics firebase**
> fix: Fixes from aggregates. List of dataValues and sync granular icon.

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Use date and time to update the date when complete dataset
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2394
> fix: completed date with time

- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/res/layout/dialog_rooted_body.xml
- app/src/main/res/layout/dialog_rooted_title.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
Fixes crash when trying to display security dialog when app is used in a rooted device.
> fix: crash when trying to display security dialog when app is used in a rooted device.

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/events/ScheduledEventPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- tableview/src/main/res/drawable-v19/outline_cell_bg.xml
Removed withCategoryCombo filter from d2.programModules().programs
> refactor(SDK): Removed withCategoryCombo filter

- app/src/main/res/layout/activity_search.xml
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2404
> fix: do not hide filter bar options

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
Minor changes adapting to the sdk
> refactor: Remove withRelatedPrograms

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/data/notifications/DhisFirebaseMessagingService.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/res/values/strings.xml
- build.gradle
- buildsystem/dependencies.gradle
- gradle to 3.5.1
- kotlin
- google-play-services
- firebase-plugins
Added:
- FirebaseCloudMessaging
> refactor: Gradle version and dependencies

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Jira Isuue: https://jira.dhis2.org/browse/ANDROAPP-2147
> fix: check access data write for attributeOptionCombo on dataSet tables

- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/main/java/org/dhis2/utils/custom_views/CategoryOptionPopUp.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2112
> fix: filter categoryOptionCombo by date

- app/src/main/java/org/dhis2/data/forms/RulesRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/utils/custom_views/PictureView.java
- app/src/main/java/org/dhis2/utils/granular_sync/GranularSyncPresenterImpl.kt
- app/src/test/java/org/dhis2/data/schedulers/SchedulersProviderImpl.kt
- app/src/test/java/org/dhis2/utils/granular_sync/GranularSyncPresenterTest.kt
Fixed fields with valueType IMAGE in event forms.
> fix: ANDROAPP-726 bugfixing

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
fix: crash when there is not catCombo
fix: dateHolder cell color
> fix: dataset initial crash and dataset date holder

- app/src/main/java/org/dhis2/App.java
- app/src/main/java/org/dhis2/data/server/ServerModule.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
- ANDROAPP-2112 fix
- fixed D2Manager instance issues
> fix(D2Manager): Fixed several issues related to new D2 instance method 

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Also improve performance displaying tables
> fix: show table correctly for any number of headers

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/customviews/orgUnitCascade/OrgUnitCascadeAdapter.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
Jira issue: [ANDROAPP-2465](https://jira.dhis2.org/browse/ANDROAPP-2465)
> fix: Message not triggered when completing event

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2464
> fix: see dashboard after completing or deactivating enrollment

- docs/recommendations-for-a-dhis2-mobile-deployment.md
> add 'versions'

- docs/recommendations-for-a-dhis2-mobile-deployment.md
Small edit in Recommendations for mobile deployment
> Small edit in Recommendations for mobile deployment

- app/src/main/res/drawable/gray_border_gray_solid_box.xml
- app/src/main/res/layout/fragment_settings.xml
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2359
> fix: settings alignment

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
Jira Issue: [ANDROAPP-2462](https://jira.dhis2.org/browse/ANDROAPP-2462)
Fixes issue with field in form was hidden behind keyboard when the form had many fields.
> fix: [ANDROAPP-2462] Fields changes focus in registration form

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
https://jira.dhis2.org/browse/ANDROAPP-2482
> fix(dataSetTableAdapter): check cell item empty

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/sms/SmsSendingService.java
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usecases/datasets/DataValuePresenterTest.kt
**Jira Issue**: [ANDROAPP-2484](https://jira.dhis2.org/browse/ANDROAPP-2484)
**changes**: It now uses the SyncStatusDialog and fixes how the updates list are shown to the user.
> fix: [ANDROAPP-2484] sms granular sync dialog 

- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsConstants.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
Jira issue: [ANDROAPP-2480]https://jira.dhis2.org/browse/ANDROAPP-2480)
> fix(home): Home takes too long to load for dataSets

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/layout/item_dataset.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usecases/datasets/DataValuePresenterTest.kt
Jira issue: [ANDROAPP-2483](https://jira.dhis2.org/browse/ANDROAPP-2483)
> fix(dataSets): DataSets showing wrong state

- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
https://jira.dhis2.org/browse/ANDROAPP-2481
> fix(tableView): scroll to start of table when zoom is pressed

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/layout/item_dataset.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usecases/datasets/DataValuePresenterTest.kt
[Jira issue](https://jira.dhis2.org/browse/ANDROAPP-2486)
> fix(analytics): Analytic events not sending user properties

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
- app/src/test/java/org/dhis2/usecases/datasets/dataSetTable/DataSetTablePresenterTest.kt
Related to PR #945 
Adds ondismiss listener to dialog to prevent crash. Also changes the name of the method to show the sync dialog.
> fix: (SyncStatusDialog): Adds onDismissListener to dialog

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerModule.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2487)
> fix: Reset app not landing on login screen

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2487)
> fix: DataSet state not updated with complete/reopen actions

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerModule.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java
- app/src/main/res/layout/development_activity.xml
> feat: New icons in sdk and shortcut to find drawable with errors

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
Jira issues:
[ANDROAPP-2497](https://jira.dhis2.org/browse/ANDROAPP-2497)
[ANDROAPP-2501](https://jira.dhis2.org/browse/ANDROAPP-2501)
> fix(category option combo): Crash on event initial

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2500
> fix: enable orgUnit field when event is referral

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
**Jira Issue**: [ANDROAPP-2502](https://jira.dhis2.org/browse/ANDROAPP-2502)
> fix(Search): Fixes search teis list when device is offline

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2507)
> fix(style): Object Style blocked new relationships

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
From the TEI details screen in the dashboard. Clicking the device physical back button was not triggering data verification and because of it you could leave the screen with empty values in mandatory fields.
> fix: Physical back button not showing empty/error field dialog

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/utils/ObjectStyleUtils.java
- app/src/main/res/layout/fragment_tei_data_card_front.xml
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2509)
> fix: Missing Tracked Entity Type icon in dashboard

- app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
**JIRA ISSUE**: [ANDROAPP-2512](https://jira.dhis2.org/browse/ANDROAPP-2512)
> fix(FilterManager): fixes bug with the period filter from-To and other

- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/values/strings.xml
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2515)
> fix(granular sync): Sync dialog layout showed errors after sms sync

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
**JIRA ISSUE**: [ANDROAPP-2516](https://jira.dhis2.org/browse/ANDROAPP-2516)
> fix(TrackedEntityAttributeValue): Removes uid from Search and Dashboard

- app/src/main/java/org/dhis2/usescases/jira/JiraViewModel.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2519)
> fix: Crash when selecting Report Jira Issue in home screen

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2517)
> fix: Crash when clicking on polygon widget for program with null feature type

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2131
> fix: allow user to select different OrgUnit

- app/src/main/res/values-es/strings.xml
_Subsequent transifex translations will be added to this PR until it is merged._
> chore(translations): sync Spanish translations from transifex (develop)

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
https://jira.dhis2.org/browse/ANDROAPP-2356
> fix: Fix random order for DE/Attributes marked with displayInList

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
**JIRA ISSUE**: [ANDROAPP-2522](https://jira.dhis2.org/browse/ANDROAPP-2522)
> fix(DataEntryAdapter): Scrolls when adding many field to the forms

- app/src/main/res/layout/fragment_tei_data_card_front.xml
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2538
> fix: do not overlap label by orgUnit name

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
**JIRA ISSUE**: [ANDROAPP-2535](https://jira.dhis2.org/browse/ANDROAPP-2535)
> fix(Dashboard): fixes dashboard crash when returning from event's form on tablet

- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionViewHolder.java
https://jira.dhis2.org/browse/ANDROAPP-2536
> fix: Create event for TEI crash when drawable resource does not exist

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
https://jira.dhis2.org/browse/ANDROAPP-2356
> fix: Bug order for DE/Attributes marked with displayInList when there is no sections

- app/src/main/res/raw/testing_credentials.json
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2540)
> refactor(testing credentials): Change default credentials

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
[jiraIssue](https://jira.dhis2.org/browse/ANDROAPP-2537)
> fix(indicators): It takes too long to show data in the indicator tab in a TEI dashboard

- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
- app/src/test/java/org/dhis2/usecases/main/program/ProgramPresenterTest.kt
https://jira.dhis2.org/browse/ANDROAPP-2543
> fix: Home loading is never hide after clean install

- app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2324)
> fix(developActivity): Icons tested individually to catch more errors

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/res/drawable/ic_edit_green.xml
- app/src/main/res/layout/activity_dataset_table.xml
https://jira.dhis2.org/browse/ANDROAPP-2548
> fix(DatasetTableActivity): Use of enrollment status/icons in Data sets

- app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2564)
> fix(orgUnits): Show capture orgUnits when search ou has not been assigned in web

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
- tableview/src/main/java/com/evrencoskun/tableview/handler/SelectionHandler.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2541
> fix: handle keypad 'next' behavior on dataSet tables

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
https://jira.dhis2.org/browse/ANDROAPP-2565
> fix(EnrollmentActivity): Field TEI Detail is not being saved when save without change the focus

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerContracts.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java
- app/src/main/res/values/strings.xml
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2590)
> fix(sms): Show sms permission when enabling option in settings

- app/src/main/java/org/dhis2/App.java
[jira](https://jira.dhis2.org/browse/ANDROAPP-2593)
> fix(maps): Fixed unregistered receiver for kujaku map downloader

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/res/layout/enrollment_activity.xml
- app/src/main/res/values/strings.xml
Add hide/show enrollment data.
> fix(enrollent form): Removed nestedScroll in enrollment form

- app/src/main/java/org/dhis2/Bindings/EventExtensions.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2148)
> fix(teiDashboard): Fixed event order

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
- app/src/main/res/layout/enrollment_activity.xml
jira issue : https://jira.dhis2.org/browse/ANDROAPP-2591
> fix: Hide Save button during enrollment form loading

- app/src/main/java/org/dhis2/data/service/SyncPresenter.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2546)
> fix(granular sync): DataSet complete registration not been uploaded in home

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Jira Issue : https://jira.dhis2.org/browse/ANDROAPP-2597
> fix(SearchTE): hide map when there is not selected program

- app/src/main/java/org/dhis2/App.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/activity_search.xml
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2593)
> fix: Kujaku offline map service crashed

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
[Issue](https://jira.dhis2.org/browse/ANDROAPP-2603)
> fix: make enrollment data visible from the start

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
https://jira.dhis2.org/browse/ANDROAPP-2605
> fix(SyncManagerFragment): Remove sms toast when entering the settings screen

- app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
- app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2602)
> fix(fields): Some fields can be cleared even if they are not editable

- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
- app/src/test/java/org/dhis2/data/forms/RulesRepositoryTest.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2609)
> fix: Supplementary data throws an exception for option group without code

- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
**JIRA ISSUE**: [ANDROAPP-2606](https://jira.dhis2.org/browse/ANDROAPP-2606)
> fix(GranularSyncPresenter): [ANDROAPP-2606] - trackerImportConflicts for a TEI are not showing

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2604
> fix: not update overdue events on search screen

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageHolder.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2611)
> fix(visualDataEntry): Options that contains "-" in their name break the forms.

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2614)
It also has newer version of the SDK (1.0.0) and newer version of the rule engine with a fix for compatibility with android 4.4
> fix: Maps in event programs shows error message when trying to click a second marker

- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
- Sync button only appears when status is not synced
- SMS sync can't show in home screen elements
- Fixed granular sync dialog state when there was one completed dataSetInstance
- Prevent crash if enrollment list is empty
[issue](https://jira.dhis2.org/browse/ANDROAPP-2612)
> fix: Granular sync fixes

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
**Jira Issue**: [ANDROAPP-2617](https://jira.dhis2.org/browse/ANDROAPP-2617)
> fix(EventCaptureRepository): [ANDROAPP-2617] Fixes order of options in an optionSet

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
https://jira.dhis2.org/browse/ANDROAPP-2623
> fix(DataValueRepository): 3 Headers CatOptionCombo DataSets

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/java/org/dhis2/utils/BiometricStorage.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2621
> fix(Fingerprint): [ANDROAPP-2621] login with fingerprint

- app/src/main/java/org/dhis2/utils/customviews/OptionSetPopUp.java
- app/src/main/java/org/dhis2/utils/optionset/OptionSetPresenter.kt
- app/src/test/java/org/dhis2/utils/optionset/OptionSetPresenterTest.kt
**JIRA ISSUEs**: [ANDROAPP-2615](https://jira.dhis2.org/browse/ANDROAPP-2615), [ANDROAPP-2617](https://jira.dhis2.org/browse/ANDROAPP-2617)
> fix(Options): [ANDROAPP-2617] - Fixes order of options in options set

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2621
> fix: get section by displayName

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2625)
> fix: Hide complete/reopen button if a dataSet cant't be edited

- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/test/java/org/dhis2/data/forms/RulesRepositoryTest.kt
- app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
**JIRA ISSUE**: [ANDROAPP-2629](https://jira.dhis2.org/browse/ANDROAPP-2629)
Only the file SyncStatusDialog was changed to fulfill the issue. The other files were fixed by running the KtlintFormat gradle task.
> feat(SMS Sync): [ANDROAPP-2629] - Disables sms sync for TEIs

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/RowAction.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerHolder.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
https://jira.dhis2.org/browse/ANDROAPP-2626
> fix(DataValuePresenter): Data set display option code and not the name

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
**JIRA ISSUES**: [ANDROAPP-2631](https://jira.dhis2.org/browse/ANDROAPP-2631)
> fix(EnrollmentForm): [ANDROAPP-2631] - handles TEI coordinate field in servers 2.29 and 2.30

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerHolder.java
https://jira.dhis2.org/browse/ANDROAPP-2630
> fix: Able to select options in Data set with can view only permissions

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2628)
> fix: DataSetInstance sync icon not being updated

- app/src/main/java/org/dhis2/utils/customviews/PeriodAdapter.kt
- app/src/main/java/org/dhis2/utils/customviews/PeriodDialog.java
- app/src/main/java/org/dhis2/utils/customviews/PeriodDialogInputPeriod.java
https://jira.dhis2.org/browse/ANDROAPP-2613
> fix(PeriodDialogInputPeriod): Crash in DataInputPeriod. It is not working

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
init method should be reviewed to add all test
> test: adds test on programEventDetailPresenter

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
Reverts dhis2/dhis2-android-capture-app#1094
> fix: Revert "fix: coordinates callback"

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2640)
> fix: Program Rule effect showing code or name vale for different events in an enrollment

- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2627)
> fix: Online records displaying code instead of name of option

- docs/contribute-to-the-app.md
Link was wrong. Fixed to markdown
> docs: transifex link [skip ci]

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
jira issue : https://jira.dhis2.org/browse/ANDROAPP-2415
> fix: Double click formulary

- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/main/java/org/dhis2/utils/customviews/PeriodAdapter.kt
- app/src/main/java/org/dhis2/utils/customviews/PeriodDialogInputPeriod.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-1828
> fix: [ANDROAPP-1828] filter periods by orgUnit closing/opening dates

- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
Jira issue: https://jira.dhis2.org/browse/ANDROAPP-2638
> feat: adds informative messages when sync with SMS

- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/datasets/dataSetInitial/DataSetInitialRepositoryImplTest.kt
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2644
> test: [ANDROAPP-2644] adds test cases on dataSetInitialRepository

- app/build.gradle
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/utils/Constants.java
- app/src/main/java/org/dhis2/utils/EventMode.kt
**JIRA ISSUE**:  [ANDROAPP-1998](https://jira.dhis2.org/browse/ANDROAPP-1998)
> feat(EventCapture): [ANDROAPP-1998] ask user to confirm deletion when going back on newly created event

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
**JIRA ISSUE**:  [ANDROAPP-2673](https://jira.dhis2.org/browse/ANDROAPP-2673)
> fix(ProgramEventDetail): [ANDROAPP-2673] fixes that the sync dialog was not showing.

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2659
> fix: [ANDROAPP-2659] don't search if all fields are empty

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
**JIRA ISSUE**: [ANDROAPP-1998](https://jira.dhis2.org/browse/ANDROAPP-1998)
> fix: [ANDROAPP-1998] don't save event on back

- docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
- docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
- docs/src/commonmark/en/dhis2_android_implementation_guideline_INDEX.md
fix INDEX files
fix wrong image name
> docs: add metadata to INDEX files [skip ci]

- docs/src/commonmark/en/content/implementation-guide/dhis2-configuration-for-android.md
- docs/src/commonmark/en/content/implementation-guide/testing.md
Transformed HTML tables to GFM where possible
> docs: transform html tables to GFM [skip ci]

- Android CodeStyle.xml
Please update this in your Android Studio settings.
**file** -> **settings** -> **Editor** -> **Code Style** -> **Kotlin** -> 🔆 -> _Import scheme_
remember to delete the previous scheme and select the new one!
> chore: Updates codestyle configurations file

- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2677)
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2679)
> fix: [ANDROAPP-2677] New program stage selection screen is empty

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2681
> fix: [ANDROAPP-2681] attributes on dashboard

- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2682)
> fix: [ANDROAPP-2682] Update coordinates after accepting permissions

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
https://jira.dhis2.org/browse/ANDROAPP-1670
> fix: ANDROAPP-1670 Fixed Read barcode / qr Code in Form Enrollment

- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
related jira issues:
[issue](https://jira.dhis2.org/browse/ANDROAPP-1273)
[issue](https://jira.dhis2.org/browse/ANDROAPP-1275)
[issue](https://jira.dhis2.org/browse/ANDROAPP-1277)
> refactor: [ANDROAPP-1273] Add userId to analytics

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/res/layout/item_note.xml
- app/src/main/res/values/colors.xml
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2672
> fix: [ANDROAPP-2672] keep pager adapter when returning from other activity

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchProgramAttributes.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
[jira](https://jira.dhis2.org/browse/ANDROAPP-1670)
> fix: [ANDROAPP-1670] Updated search activity to be able to use QR/Barcode scanner

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/AttributeValueStore.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryStore.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataValueStore.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
- app/src/main/java/org/dhis2/data/forms/dataentry/StoreResult.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStore.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/Dhis2TextUtils.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
- app/src/test/java/org/dhis2/usescases/datasets/DataValuePresenterTest.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
- Updated sdk with master-dev branch
- Added value checks
- Added filter to events with future dates
> fix: 2.0.1 latest fixes

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
**JIRA ISSUE**: [ANDROAPP-2728](https://jira.dhis2.org/browse/ANDROAPP-2728)
> fix(SearchActivity): [ANDROAPP-2728] handle the location permision on the search activity

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
**JIRA ISSUE**: [ANDROAPP-2726](https://jira.dhis2.org/browse/ANDROAPP-2726)
**JIRA ISSUE**: [ANDROAPP-2729](https://jira.dhis2.org/browse/ANDROAPP-2729)
> fix: [ANDROAPP-2726] fields recalculate when receiving the gallery or camera intent result.

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterImpl.java
[jira](https://jira.dhis2.org/browse/ANDROAPP-2725)
> fix: [Androapp 2725] Fix percentage calculation by removing display elements

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
**JIRA ISSUE**: [ANDROAPP-2660](https://jira.dhis2.org/browse/ANDROAPP-2660)
> fix: [ANDROAPP-2660] Correct sort order the searchable fields

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Jira issue: https://jira.dhis2.org/browse/ANDROAPP-2712
> feat: [ANDROAPP-2712] apply "Assigned to me" filter in event screen

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerTabletAdapter.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2740
> fix: [ANDROAPP-2740] crash in relationship

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/res/layout/enrollment_activity.xml
**JIRA ISSUE**: [ANDROAPP-7231](https://jira.dhis2.org/browse/ANDROAPP-2731)
> feat: [ANDROAPP-7231] Changes save button to a FAB button

- docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
Table was not properly formatted due to an error. Corrected
> docs: Update program rules table [skip ci]

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
- app/src/main/java/org/dhis2/utils/customviews/AlertBottomDialog.kt
- app/src/main/res/layout/alert_bottom_dialog.xml
- app/src/main/res/values/colors.xml
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-2733
> feat: [ANRDROAPP-2733] Change form alerts design to bottomSheetDialogs

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2734)
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2735)
Ignore commented lines in EventCaptureRepository. Can be removed after testing.
> fix: [ANDROAPP-2734/35] Program rules fixes

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
Jira Issue: https://jira.dhis2.org/browse/ANDROAPP-1670
> fix: [ANDROAPP-1670] scan not capturing data on search and check rendering type

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageRow.java
- app/src/main/res/layout/section_selector_fragment.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2732)
> fix: [ANDROAPP-2732] Fix image height for sequential and matrix rendering

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2716)
> fix: [ANDROAPP-2716] increase row header width when clicking zoom icon

- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
- app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
- app/src/test/java/org/dhis2/usescases/main/program/HomeRepositoryImplTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2743)
> fix: [ANDROAPP-2743] Grey out data sets when "Assigned to me" filter is active

- app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
**JIRA ISSUE**: [ANDROAPP-2738](https://jira.dhis2.org/browse/ANDROAPP-2738)
> fix: [ANDROAPP-2738] fixes deletion of a Tei or an Enrollement

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2772)
- Enrollment count fix
> fix: [ANDROAPP-2772] Fix loop with program rules action assign and error

- app/build.gradle
- app/src/main/java/org/dhis2/Bindings/ContextExtensions.kt
- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/res/layout-land/activity_login.xml
- app/src/main/res/layout/activity_login.xml
- Search attribute list order
- Fix focus from text fields in forms
> fix: [ANDROAPP-2782] OptionCode not been selected for program rule variable value

- app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
Brings tei and enrollment deletion from 2.0.1 branch to develop
> fix: TEI and Enrollment deletion

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-2770)
> fix: [ANDROAPP-2770] Disable settings parameter when there is no internet connection

- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
[https://jira.dhis2.org/browse/ANDROAPP-2767](Jira Issue)
DateUtils tests updated
> fix: [ANDROAPP-2767] get next periods of some periodTypes

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2768)
> fix: [ANDROAPP-2768] Hide filters in search screen until a list result is fetch

- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/EventRepository.java
- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
- app/src/main/res/values/strings.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2786)
> fix: [ANDROAPP-2786] Program rules are not filtered by program stage

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/java/org/dhis2/utils/maps/GeometryUtils.kt
- app/src/main/java/org/dhis2/utils/maps/MapboxExtension.kt
JIRA ISSUE 2804
Problems Found : 
- The map was loading only sometimes. initialization issue
- When there was no data to load on map, the zoom was set to "1". So you could see grey out map
- When clicking on Tei point the app was crashing. Now it opens the TeiDashboard
> fix: 2804 mapbox issue

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/res/menu/dashboard_tei_menu.xml
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2787)
> fix: [ANDROAPP-2787] options on tei enrollments

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
Issue: ANDROAPP-2805 
Crash with referal https://jira.dhis2.org/browse/ANDROAPP-2805
> fix: [ANDROAPP-2805] crash with periodType

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
**JIRA ISSUE**: [ANDROAPP-2779](https://jira.dhis2.org/browse/ANDROAPP-2779)
> fix: [ANDROAPP-2779] Checks if unique attributes has coincidences or not before saving an enrollment

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2800)
> fix: [ANDROAPP-2800] Use code for variable not wornking with tracked entity attributes

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImplTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2810)
> fix: [ANDROAPP-2810] Can't enroll tei in program from dashboard list

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2790)
> fix: [ANDROAPP-2790] TEType in coordinates label

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
**JIRA ISSUE**: [ANDROAPP-2803](https://jira.dhis2.org/browse/ANDROAPP-2803)
> fix: [ANDROAPP-2803] Updates Tei image on search list when it's updated.

- app/src/main/java/org/dhis2/usescases/map/MapSelectorActivity.kt
**JIRA ISSUE**: [ANDROAPP-2818](https://jira.dhis2.org/browse/ANDROAPP-2818)
> fix: [ANDROAPP-2818] Updates location of map when granting location permission.

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2820)
> fix: [ANDROAPP-2820] Duplicated fields and crash in single section events

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonCellHolder.java
- app/src/main/java/org/dhis2/utils/customviews/YesNoView.java
- app/src/main/res/layout/yes_no_view_primary.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2817)
> fix: [ANDROAPP-2817] Datasets yes/no value type rendering

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2819)
> fix: [ANDROAPP-2819] check enrollment followUp is not null

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/res/layout/activity_event_capture.xml
[jira](https://jira.dhis2.org/browse/ANDROAPP-2822)
> style: [ANDROAPP-2822] Fix event form toolbar title style

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/res/layout/tei_data_header.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2821)
> style: [ANDROAPP-2821] Fix enrollment toolbar title

- app/src/main/java/org/dhis2/Bindings/ViewExtensions.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
**JIRA ISSUE**: [ANDROAPP-2824](https://jira.dhis2.org/browse/ANDROAPP-2824)
> style: [ANDROAPP-2824] Change color to section fields number when all fields have values

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TeiDataRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/tei_events/EventViewModel.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/tei_events/StageViewHolder.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2823)
> fix: [ANDROAPP-2823] Fix add event when grouping events

- app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[jira](https://jira.dhis2.org/browse/ANDROAPP-2814)
> fix: [ANDROAPP-2814] Fix crash related to search list

- app/src/main/res/layout/fragment_settings.xml
https://jira.dhis2.org/browse/ANDROAPP-2825
> fix: [ANDROAPP-2825] Add padding to parameter settings layout

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
- app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
**JIRA ISSUE**: [ANDROAPP-2568](https://jira.dhis2.org/browse/ANDROAPP-2568)
> test: [ANDROAPP-2568] DataSetTable Presenter Tests

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2827)
> fix: [ANDROAPP-2827] Fix inner shadow in last form field

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/tei_events/StageViewHolder.kt
- app/src/main/res/drawable/square_rounded_corners_2.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2830)
> fix: [ANDROAPP-2830] Fix grouping stage icon corner radius

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
**JIRA ISSUE**: [ANDROAPP-2831](https://jira.dhis2.org/browse/ANDROAPP-2831)
> fix: [ANDROAPP-2831] Sets elevation when filters are shown in the TEI Dashboard

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayHolder.java
[jira](https://jira.dhis2.org/browse/ANDROAPP-2783)
> fix: [ANDROAPP-2783] Fix changing display text to display key value pair

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2838)
> fix: [ANDROAPP-2838] Do not delete values when hide section is activated

- app/src/main/java/org/dhis2/Bindings/Extensions.kt
- app/src/main/java/org/dhis2/Bindings/FileExtensions.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureRow.java
- app/src/main/java/org/dhis2/utils/customviews/ImageDetailBottomDialog.kt
- app/src/main/java/org/dhis2/utils/customviews/PictureView.java
- app/src/main/res/layout/detail_image_bottom_dialog.xml
- app/src/main/res/layout/form_picture.xml
- app/src/test/java/org/dhis2/bindings/FileExtensionsTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2839)
> fix: [ANDROAPP-2835] Display full image when clicked

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
This PR was already merged in the Release/2.1.0 branch in PR #1280. 
This is meant to be merged in develop
> fix: [ANDROAPP-2831] Changes toolbar elevation when filters are displayed

- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
**JIRA ISSUE**: [ANDROAPP-2844](https://jira.dhis2.org/browse/ANDROAPP-2844)
> fix: [ANDROAPP-2844] Change PreferenceProvider instead of SharedPreferences

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2826)
> fix: [ANDROAPP-2826] save values on clear

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
- app/src/main/res/drawable/shadow.xml
- app/src/main/res/layout/activity_event_capture.xml
- app/src/main/res/layout/enrollment_activity.xml
- app/src/main/res/layout/form_section.xml
- app/src/main/res/layout/section_selector_fragment.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2828)
> fix: [ANDROAPP-2828] Improve open/close section animation

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2846)
> fix: [ANDROAPP-2846] TEI details title attributes

- docs/src/commonmark/en/content/capture-app/program-indicators.md
Aligned SDK and App documentation regarding program indicators
> docs: Align doc SDK-App [skip ci]

- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
**JIRA ISSUE**: [ANDROAPP-2847](https://jira.dhis2.org/browse/ANDROAPP-2847)
> fix: [ANDROAPP-2847] Removes SharedPreferences from logout and uses instead the PreferenceProvider

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
**JIRA ISSUE**: [ANDROAPP-2807](https://jira.dhis2.org/browse/ANDROAPP-2807)
> fix: [ANDROAPP-2807] Sets server url and user name of previous successful login.

- app/src/main/java/org/dhis2/utils/ValidationUtils.kt
- app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
**JIRA ISSUE**: [ANDROAPP-2852](https://jira.dhis2.org/browse/ANDROAPP-2852)
> fix: [ANDROAPP-2852] Validates that a field of valueType of Number does not round decimals.

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- app/src/main/res/layout/fragment_settings_item.xml
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2856)
> fix: [ANDROAPP-2856] change color and padding when there is a error

- app/src/debug/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/map/MapSelectorActivity.kt
- app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2864)
> fix: [ANDROAPP-2864] ask only for fine location

- app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2863)
> fix: [ANDROAPP-2863] Fix crash in search screen

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/UtilsModule.java
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2866)
> fix: [ANDROAPP-2866] Hide section rule should not delete field's values

- app/src/main/java/org/dhis2/Bindings/MeasureExtensions.kt
- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetRowHeader.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/utils/OrientationUtils.kt
- app/src/main/res/drawable/ic_increase_width.xml
- app/src/main/res/drawable/ic_reduce_width.xml
- app/src/main/res/layout/item_dataset_row.xml
- app/src/main/res/layout/table_view_corner_layout.xml
- app/src/main/res/values/dimens.xml
- app/src/test/java/org/dhis2/usescases/datasets/DataValuePresenterTest.kt
- tableview/src/main/java/com/evrencoskun/tableview/ITableView.java
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
- tableview/src/main/java/com/evrencoskun/tableview/adapter/AbstractTableAdapter.java
[jira](https://jira.dhis2.org/browse/ANDROAPP-2865)
> fix: [ANDROAPP-2813] Fix dataSet label width

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/activity_search_backup.xml
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
**JIRA ISSUE**: [ANDROAPP-2858](https://jira.dhis2.org/browse/ANDROAPP-2858)
> fix: [ANDROAPP-2858] Prevents search when a minimum required attribute is needed

- app/build.gradle
- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
- app/src/main/java/org/dhis2/usescases/sync/SyncActivity.java
- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
- app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/layout/custom_text_view.xml
- app/src/main/res/layout/form_spinner.xml
- app/src/main/res/layout/form_spinner_accent.xml
- app/src/main/res/layout/item_program_model.xml
- app/src/main/res/values/styles.xml
[ANDROAPP-2861](https://jira.dhis2.org/browse/ANDROAPP-2861)
[ANDROAPP-2862](https://jira.dhis2.org/browse/ANDROAPP-2862)
I tried to add some unit tests, but the SMSConfig class in the SDK is needed and it has no public access.
> feat: [ANDROAPP-2861,ANDROAPP-2862] Update SDK to support SMS in tracker

- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2874)
> fix: [ANDROAPP-2874] Fix enrollment from tei dashboard

- app/src/main/res/layout/item_search_tracked_entity.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2876)
> fix: [ANDROAPP-2876] Icons overlap in search screen

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/res/layout/activity_dataset_table.xml
- app/src/main/res/layout/activity_event_initial.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2857)
> fix: [ANDROAPP-2857] Display color and icon for stages and dataSets

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
**JIRA ISSUE**: [ANDROAPP-2858](https://jira.dhis2.org/browse/ANDROAPP-2858)
> fix: [ANDROAPP-2858] Fixes the search displayFrontPage and minimum required attribute

- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2875)
> fix: [ANDROAPP-2875] Handle single event deletion

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2879)
> fix: [ANDROAPP-2879] clear focus when orientation changes

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/utils/maps/MapLayerDialog.kt
- app/src/main/java/org/dhis2/utils/maps/MapLayerManager.kt
- app/src/main/res/layout/dialog_map_layer.xml
- app/src/main/res/values/strings.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2885)
> fix: [ANDROAPP-2885] Filters in maps do not update data

- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2887)
> fix: Use code for option set fix

- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
[Jira issue](https://jira.dhis2.org/browse/ANDROAPP-2859)
> fix: [ANDROAPP-2859] value type icon white on TEI search

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2871)
> fix: [ANDROAPP-2871] enrollment errors only when save button is clicked

- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
Bug that fixs tei's not being downloaded when the server has no Webapp
> fix: bug when trying to sync tei

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
[Jira issue](https://jira.dhis2.org/browse/ANDROAPP-2867)
>  fix(Enrollment): [ANDROAPP-2867] orgUnit not editable when is only one

- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
Added chinese and arabic language files
> feat: Languages update

- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2895)
> fix: [ANDROAPP-2895] Attribute not downloaded causing crashes

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2898)
> fix: [ANDROAPP-2898] Always show arrows in sections

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2879)
> fix: [ANDROAPP-2879] Fix rotation displacement of cells

- app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
- app/src/main/res/layout/activity_event_initial.xml
- app/src/main/res/layout/item_program_model.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2709)
> fix: [ANDROAPP-2709] Round corners for program and program stage icons

- app/src/main/res/layout/item_search_tracked_entity.xml
**JIRA ISSUE**: [ANDROAPP-2902](https://jira.dhis2.org/browse/ANDROAPP-2902)
> fix: [ANDROAPP-2902] TEI item list layout when attributes are not shown.

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2903)
> fix: [ANDROAPP-2903] Enrollment form not opening when creating a tei for relationship

- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
**JIRA ISSUE**: [ANDROAPP-2904](https://jira.dhis2.org/browse/ANDROAPP-2904)
> fix: [ANDROAPP-2904] Fixes QR Code Scan for the first time

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2703)
> fix: [ANDROAPP-2703] sort indicators alphabetically

- app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
- app/src/main/java/org/dhis2/utils/Constants.java
- app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
**JIRA ISSUE**: [ANDROAPP-2908](https://jira.dhis2.org/browse/ANDROAPP-2908)
> fix: [ANDROAPP-2908] Separates Scan code reader depending on its ValueTypeRenderingType

- app/src/main/res/layout/item_stage_section.xml
**JIRA ISSUE**: [ANDROAPP-2915](https://jira.dhis2.org/browse/ANDROAPP-2915)
> fix: [ANDROAPP-2915] Adds ellipsis to the end of the stage display name

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2913)
> fix: [ANDROAPP-2913] update fields after reopen event

- app/src/main/java/org/dhis2/Bindings/Extensions.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
- app/src/main/java/org/dhis2/utils/customviews/ImageDetailBottomDialog.kt
- app/src/main/res/drawable/shadow.xml
- app/src/main/res/layout/form_section.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2916)
> fix: [ANDROAPP-2916] Last section padding/shadow fix

- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2914)
> fix: [ANDROAPP-2914] Looping rules message displayed when hiding attribute from event

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
- app/src/main/java/org/dhis2/utils/session/PinDialog.kt
- app/src/main/java/org/dhis2/utils/session/PinModule.kt
- app/src/main/java/org/dhis2/utils/session/PinPresenter.kt
- app/src/test/java/org/dhis2/utils/session/PinPresenterTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2921)
> fix: [ANDROAPP-2921] Pin dialog shoud close session if clicked on forgot code

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2922)
> fix: [ANDROAPP-2922] Show assign to me filter only if a program stage is configured

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
- app/src/main/java/org/dhis2/utils/recyclers/StickyHeaderItemDecoration.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2927)
> fix: [ANDROAPP-2927] Click in info icon in a section do not display pop up

- app/src/main/res/layout/enrollment_activity.xml
- app/src/main/res/layout/section_selector_fragment.xml
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2980)
> fix: [ANDROAPP-2980] change save icon

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/res/values/strings.xml
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-2982)
> fix(EnrollmentActivity): [ANDROAPP-2982] check uuid is not null

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
- app/src/main/res/drawable/ic_arrow_back.xml
- app/src/main/res/drawable/ic_increase_width.xml
- app/src/main/res/drawable/ic_reduce_width.xml
- tableview/build.gradle
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2668)
> fix: [ANDROAPP-2668] Support RTL in dataSet tables

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
- app/src/main/res/layout/form_section.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2981)
> fix: [ANDROAPP-2981] Show section number

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventMapperTest.kt
**JIRA ISSUE**: [ANDROAPP-2983](https://jira.dhis2.org/browse/ANDROAPP-2983)
> fix: [ANDROAPP-2983] Fix crash on ProgramEventDetailRepository

- app/src/main/res/layout/fragment_tei_data_card_front.xml
[issue](https://jira.dhis2.org/browse/ANDROAPP-2666)
> fix: [ANDROAPP-2666] RTL errors in tei dashboard card

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2954)
- NEEDS CHANGING NETWORKUTILS -
> fix: [ANDROAPP-2954] Sync screen showing after login offline

- app/build.gradle
- app/src/main/java/org/dhis2/data/fingerprint/FingerPrintController.kt
- app/src/main/java/org/dhis2/data/fingerprint/FingerPrintControllerImpl.kt
- app/src/main/java/org/dhis2/data/fingerprint/FingerPrintModule.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/res/layout/dialog_body.xml
- app/src/main/res/values/themes.xml
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2984)
> fix: [ANDROAPP-2984] Crash when using fingerprint

- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/utils/extension/ActivityExtension.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-2985)
> fix: [ANDROAPP-2985] Crash when starting app

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
[Jira Issue](https://jira.dhis2.org/browse/ANDROAPP-3021)
> fix: [ANDROAPP-3021] don't count fields without section for percentage

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-2963)
> fix: [ANDROAPP-2963] Set incident date without hours and minutes

- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/test/java/org/dhis2/utils/filters/FilterManagerTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-3023)
> fix: [ANDROAPP-3023] Filter "Not synced" adding uploading as a different "To post" state

- app/src/main/java/org/dhis2/Bindings/Extensions.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
**JIRA ISSUE**: [ANDROAPP-3022](https://jira.dhis2.org/browse/ANDROAPP-3022)
> fix: [ANDROAPP-3022] Fixes bug with back button on enrollment and event forms

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- viewpagerdotsindicator/build.gradle
- viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/DotsIndicator.java
- viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/SpringDotsIndicator.java
- viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/WormDotsIndicator.java
**JIRA ISSUE**: [ANDROAPP-2072](https://jira.dhis2.org/browse/ANDROAPP-2872)
> fix: [ANDROAPP-2872] Updates viewpager dotsindicator library to work with ViewPager2

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
[issue](https://jira.dhis2.org/browse/ANDROAPP-3024)
> fix: [ANDROAPP-3024] Do not hide filters icon if no data is returned

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
[issue](https://jira.dhis2.org/browse/ANDROAPP-3032)
> fix: ANDROAPP-3032

- app/src/main/java/org/dhis2/data/forms/RuleActionUnsupported.java
Update rule engine with expression parser
> feat: rule engine update

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/notes/NoteType.kt
- app/src/main/java/org/dhis2/usescases/notes/NotesFragment.kt
- app/src/main/java/org/dhis2/usescases/notes/NotesPresenter.kt
- app/src/main/java/org/dhis2/usescases/notes/NotesRepository.kt
- app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailRepositoryImpl.kt
- app/src/test/java/org/dhis2/usescases/notes/NotesPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/notes/NotesRepositoryTest.kt
- app/src/test/java/org/dhis2/usescases/notes/noteDetail/NoteDetailRepositoryTest.kt
> chore: Removes notes from DataSets

- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout/dialog_map_layer.xml
Add relationships to search map to show how them are displayed dynamically
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3088)
> feat: [ANDROAPP-3088] Add dynamic layers to layers dialog

- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
Get relationships of each TEI on search screen and add it to the feature collection
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3119)
> feat: [ANDROAPP-3119] add relationships to feature collection on search screen

- app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
- app/src/main/res/drawable/ic_arrowhead.xml
- app/src/main/res/drawable/ic_arrowhead_bidirectional.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3118)
> feat: [ANDROAPP-3118] Show relationship line direction

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3136)
Not filtering null values is enough to display the correct list.
> fix: [ANDROAPP-3136] Always show attribute main names in tei card

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapRelationshipsToFeatureCollection.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeiEventsToFeatureCollection.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonPointToFeature.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonToFeature.kt
> fix: crash search map

- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/res/drawable/bottomsheet_bg.xml
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/dialog_map_layer.xml
- app/src/main/res/layout/fragment_relationships.xml
- app/src/main/res/layout/item_layer.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Added layer button in events and relationships maps. Also changed the dialog to bottomsheetdialog to fix some UI issues.
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2891)
> feat: [ANDROAPP-2891] Show map layer dialog in all maps

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3148)
> fix: Crash in searchTei due to null value in teicard

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ADNROAPP-3144)
> feat: [ANDROAPP-3114] Inherit values

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
- app/src/main/res/layout/activity_event_capture.xml
> fix: Rollback viewpager 2

- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
- release.info
> fix: rule engine update

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventViewModel.java
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/item_carousel_program_event.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Display a carousel on program events with all events info
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3172)
> feat: [ANDROAPP-3172] add carousel to program events map

- app/src/main/java/org/dhis2/Bindings/DoubleExtensions.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/MapSelectorActivity.kt
- app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
[ANDROAPP-3167](https://jira.dhis2.org/browse/ANDROAPP-3167)
> fix: Limits location values to no more than 5 decimal

- app/src/main/java/org/dhis2/usescases/settings/models/ErrorModelMapper.kt
> fix: Updates sdk that fixes orderByOrgUnitName in the events repo.

- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
[ANDROAPP-3174](https://jira.dhis2.org/browse/ANDROAPP-3174)
> chore: [ANDROAPP-3174] Changes Events fragments title

- app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/main/java/org/dhis2/utils/filters/StatusEnrollmentFilterHolder.java
- app/src/test/java/org/dhis2/bindings/TrackedEntityInstanceExtensions.kt
[ANDROAPP-3192](https://jira.dhis2.org/browse/ANDROAPP-3192)
> feat: [ANDROAPP-3192] Implements single selection in Enrollment Status filter

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerHolder.java
- app/src/main/java/org/dhis2/utils/ValidationUtils.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3180)
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3128)
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3030)
Updated RuleEngine and added requestFocus to optionSet field.
> fix: [ANDROAPP-3180, 3128, 3030] RuleEngine fixes

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
[ANDROAPP-3174](https://jira.dhis2.org/browse/ANDROAPP-3174)
> fix: [ANDROAPP-3174] change string resource Details to Data

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
[ANDROAPP-3162](https://jira.dhis2.org/browse/ANDROAPP-3162)
> fix: [ANDROAPP-3162] Changes event status when enrollment is completed/re-open/deactivate

- app/src/main/java/org/dhis2/utils/ValidationUtils.kt
- app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3078)
> fix: [ANDROAPP-3078] Numeric value type formats

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/res/layout/fragment_validation_result_violation.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3197)
> fix: [ANDROAPP-3197] Data set layout errors

- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3195)
> fix: [ANDROAPP-3195] Remove request focus when field has error

- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
[ANDROAPP-2911](https://jira.dhis2.org/browse/ANDROAPP-2911)
> fix: [ANDROAPP-2911] Removes pin windows when a user logout

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
> fix: [ANDROAPP-3207] Fix crash when selecting profile image in dashboard

- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/mapper/MapRelationshipToRelationshipMapModel.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/fragment_relationships.xml
- Colors of displayed relationships
- Hyphen for missing attributes in relationships cards
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3208)
> fix: [ANDROAPP-3208] Improvements in TEI map

- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3203)
> fix: [ANDROAPP-3203] Improved scroll animation for carousel view

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiEventMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3205)
> fix: [ANDROAPP-3205] Improvements in Event Maps

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/strings.xml
[ANDROAPP-3213](https://jira.dhis2.org/browse/ANDROAPP-3213)
> fix: [ANDROAPP-3213] Changes dataset details tab title to data

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3211)
> fix: [ANDROAPP-3211] Sync icon is not shown when granular sync ends

- app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
- app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3211)
> fix: [ANDROAPP-3211] New period labels and enrollment date position

- app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
- app/src/main/java/org/dhis2/utils/customviews/AlertBottomDialog.kt
- app/src/main/res/drawable/ic_bottom_sheet_dialog.xml
- app/src/main/res/layout-land/fragment_program.xml
- app/src/main/res/layout/alert_bottom_dialog.xml
fix alertBottomDialog rounded corners
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3216)
> fix: [ANDROAPP-3216] Fix crashes and rounded corners

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3220)
> fix: [ANDROAPP-3220] Show only display in list attributes

- app/src/dhis/java/org/dhis2/usescases/main/program/ProgramAnimation.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3227)
> fix: [ANDROAPP-3227] Backdrop animation fix

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/res/layout/filter_enrollment_status.xml
- app/src/main/res/values/strings.xml
Change alert dialog text and negative button.
> fix: update alert dialog with new text and remove negative btn

- docs/src/commonmark/en/content/capture-app/app-android-settings-configuration.md
Change "Android Settings App" by "Android Settings Web App"
> docs: Update app-android-settings-configuration.md [skip ci]

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3226)
> fix: [ANDROAPP-3226] Filters allow unwanted event creation

- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3230)
> fix: [ANDROAPP-3230] Camera moving to places with no coordinates

- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3244)
> fix: [ANDROAPP-3244] Event capture with QR

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3223)
> fix: [ANDROAPP-3223] check all fields for dataElement required

- app/src/main/java/org/dhis2/App.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3231)
> fix: [ANDROAPP-3231] Data is not saved after clicking save button

- docs/src/commonmark/en/content/implementation-guide/SMS-for-reporting.md
Small edits in the introductory text.
> Update SMS-for-reporting.md  [skip ci]

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeHolder.java
- app/src/main/java/org/dhis2/utils/customviews/AgeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateTableView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3246)
> fix: [ANDROAPP-3246] Fix AgeHolder date format

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
> fix: edit event test tests

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3259)
> fix: [ANDROAPP-3259] Unknown attribute crash

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3257)
> fix: [ANDROAPP-3257] Fix tei card image

- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/utils/session/PinDialog.kt
> fix: Pin dialog fixed

- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
- app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3264)
> fix: [ANDROAPP-3264] Assigned values to integers showing decimals

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3253)
> fix: [ANDROAPP-3253] Do not open activity if enrollment does not exist

- buildsystem/dependencies.gradle
> fix: Updated sdk to 1.2.1

- RELEASE.md
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-id/strings.xml
- app/src/main/res/values-km/strings.xml
- app/src/main/res/values-lo/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- release.info
- whatsnew/whatsnew-en-US
> feat: Release notes

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3160)
> fix: [ANDROAPP-3160] Fix landscape dashboard pages titles

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2669)
> fix: [ANDROAPP-2669] Update drawable tint when changing program

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/res/values/colors.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3116)
> fix: [ANDROAPP-3116] Notes badge color

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3276)
> fix: [ANDROAPP-3276] Hide schedule option if hideDueDate is true

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextRow.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
- app/src/main/res/layout/scan_text_view.xml
- app/src/main/res/layout/scan_text_view_accent.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3086)
> feat: [ANDROAPP-3086] QR and Barcode allow typing

- app/src/main/java/org/dhis2/utils/customviews/OptionSetPopUp.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3095)
> fix: [ANDROAPP-3095] Dismiss popup when item is selected

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
[ANDROAPP-3086](https://jira.dhis2.org/browse/ANDROAPP-3086)
> fix: [ANDROAPP-3086] QR and Barcode crash inputting text in the search attribute field

- app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorAdapter.java
- app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorHolder.kt
[ANDROAPP-3296](https://jira.dhis2.org/browse/ANDROAPP-3296)
> fix: [ANDROAPP-3296] Org Unit selection when scrolling in the orgUnitSelector tree.

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
[ANDROAPP-3232](https://jira.dhis2.org/browse/ANDROAPP-3232)
> fix: [ANDROAPP-3232] Changing Event date clear OrgUnit field

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
> fix: calculated value being ignore

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
> fix: getNextsection

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ANDROAPP-3307](https://jira.dhis2.org/browse/ANDROAPP-3307)
> fix: [ANDROAPP-3307] Search's clear button is now working

- app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.kt
- app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorAdapter.java
- app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorHolder.kt
- app/src/main/java/org/dhis2/usescases/orgunitselector/TreeNodeCallback.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3296)
> fix: [ANDROAPP-3296] Fixed org. unit list crash when scrolling

- app/src/main/java/org/dhis2/uicomponents/map/TeiMarkers.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/res/drawable/bg_image_marker.xml
Display TEI images on map
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3294)
> fix: [ANDROAPP-3294] display TEI images on map

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt
[ANDROAPP-3293](https://jira.dhis2.org/browse/ANDROAPP-3293)
> fix: [ANDROAPP-3293] Greyed fields are not being respected

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3247)
> fix: [ANDROAPP-3247] Do not auto-remove value from local database after showError action

- RELEASE.md
- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/data/sorting/SearchSortingValueSetter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/GetNextVisibleSection.kt
- app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.kt
- app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorAdapter.java
- app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorHolder.kt
- app/src/main/java/org/dhis2/usescases/orgunitselector/TreeNodeCallback.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/test/java/org/dhis2/data/sorting/SearchSortingValueSetterTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
- buildsystem/dependencies.gradle
- docs/src/commonmark/en/dhis2_android_MDM_INDEX.md
- release.info
> feat: Update with 2.2.2 changes

- app/src/main/java/org/dhis2/data/service/SyncGranularRxWorker.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/settings/models/ErrorModelMapper.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/test/java/org/dhis2/usescases/settings/models/ErrorModelMapperTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2778)
> feat: [ANDROAPP-2778] Use displayDescription instead of conflict

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormView.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
> fix: [ANDROAPP-3252] Event form freeze

- app/src/androidTest/java/org/dhis2/usescases/settings/SettingsTest.kt
- app/src/main/java/org/dhis2/data/server/ServerModule.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2868)
> refactor: [ANDROAPP-2868] Increase timeout connection to 10 minutes

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/res/layout-land/activity_login.xml
- app/src/main/res/layout/activity_login.xml
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3315)
> fix: [ANDROAPP-3315] change info icon for clear button in server url

- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/res/values/strings.xml
[ANDROAPP-2998](https://jira.dhis2.org/browse/ANDROAPP-2998)
> feat: [ANDROAPP-2998] checks for debugger in release apk

- app/src/main/java/org/dhis2/App.java
Enable acra in prod and debug
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3332
> feat: Enable acra

- app/src/main/assets/paperwork.json
- app/src/main/res/layout/age_custom_view.xml
- app/src/main/res/layout/age_custom_view_accent.xml
- app/src/main/res/layout/custom_long_text_view.xml
- app/src/main/res/layout/custom_long_text_view_accent.xml
- app/src/main/res/layout/custom_text_view.xml
- app/src/main/res/layout/custom_text_view_accent.xml
- app/src/main/res/layout/date_time_view.xml
- app/src/main/res/layout/date_time_view_accent.xml
- app/src/main/res/layout/form_coordinates.xml
- app/src/main/res/layout/form_coordinates_accent.xml
- app/src/main/res/layout/form_spinner.xml
- app/src/main/res/layout/form_spinner_accent.xml
- app/src/main/res/layout/scan_text_view.xml
- app/src/main/res/layout/scan_text_view_accent.xml
- app/src/main/res/layout/yes_no_view.xml
- app/src/main/res/layout/yes_no_view_primary.xml
[ANDROAPP-3338](https://jira.dhis2.org/browse/ANDROAPP-3338)
> fix: [ANDROAPP-3338] Removes top padding and adds bottom padding to fields layout

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/file/FileViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/unsupported/UnsupportedViewModel.java
- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
> fix: [ANDROAPP-3348] Disable edition of fields when value is assigned

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3346)
> fix: [ANDROAPP-3346] Apply displayInList in dashboard TEI card

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitHolder.java
- app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
- app/src/main/java/org/dhis2/utils/customviews/AgeView.java
- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
- app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateView.java
- app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
- app/src/main/java/org/dhis2/utils/customviews/OrgUnitView.java
- app/src/main/java/org/dhis2/utils/customviews/TimeView.java
- app/src/main/res/layout/custom_long_text_view.xml
- app/src/main/res/layout/custom_long_text_view_accent.xml
- app/src/main/res/layout/custom_text_view.xml
- app/src/main/res/layout/form_coordinates.xml
- app/src/main/res/layout/form_coordinates_accent.xml
- app/src/main/res/layout/form_picture.xml
- app/src/main/res/layout/form_picture_accent.xml
- app/src/main/res/layout/yes_no_view.xml
- app/src/main/res/layout/yes_no_view_primary.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3333)
> fix: [ANDROAPP-3333] form design improvements

- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
> fix: selected image overlap current and is not displayed behind

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3349)
> fix: [ANDROAPP-3349] crash when reset search with all TET

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
> fix: [ANDROAPP-3352] Warning showing for unique value

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
> fix: [ANDROAPP-3341] Tracker conflict in event prevent showing form

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
> fix: [ANDROAPP-3351] Do not show warning/error badge in section until save button is pressed

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewModel.kt
- app/src/main/res/layout/item_event.xml
- app/src/main/res/layout/item_stage_section.xml
> fix: [ANDROAPP-3329] Event item layout design fixes

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/utils/filters/EnrollmentDateFilterHolder.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3323
> fix: ANDROAPP-3323 Search network calls

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3345)
> fix: [ANDROAPP-3345] Display view model method setting null in nonnull variable

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3358)
> fix: [ANDROAPP-3358] crash when changing program from all TET

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
[ANDROAPP-3353](https://jira.dhis2.org/browse/ANDROAPP-3353)
> fix: [ANDROAPP-3353] Avoids showing a floating header on an form without section

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3357)
> fix: [ANDROAPP-3357] Allow new enrollment when minAttributesToSearch is 0

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3362)
> fix: [ANDROAPP-3362] image issues

- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3369)
> fix: [ANDROAPP-3369] Do not copy FilterManager values using equal assignments

- app/src/androidTest/java/org/dhis2/AppTest.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
- app/src/main/java/org/dhis2/data/service/SyncGranularWorker.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3321)
> test: [ANDROAPP-3321] Flow ui test

- app/src/main/res/values/strings.xml
> feat: Update strings.xml for transifex translations

- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateView.java
- app/src/main/java/org/dhis2/utils/customviews/TimeView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3364)
> fix: [ANDROAPP-3364] User friendly value not shown in event cards

- app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateView.java
- app/src/main/java/org/dhis2/utils/customviews/TimeView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3373)
> fix: [ANDROAPP-3373] Date fields not removing focus from text fields

- scripts/requirements.txt
- scripts/reviewers.py
> chore: DO NOT MERGE, PR for testing purposes [skip ci]

- scripts/requirements.txt
- scripts/reviewers.py
> chore: Adds reviewers script

- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3379)
> fix: [ANDROAPP-3379] Revert to value path for images

- scripts/reviewers.py
> fix: Adds validation to check if the PR already has an approval, comment or a change requested

- app/src/main/res/layout/item_carousel_tei.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3397)
> fix: [ANDROAPP-3397] Check was hiding main attribute in carousel item

- app/src/main/java/org/dhis2/data/prefs/Preference.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3332)
> fix: ANDROAPP-3332 Update map when event changes coordinates

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
- app/src/main/res/layout/form_section.xml
- app/src/test/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3186])
> fix: [ANDROAPP-3186] Show description icon when test is ellipsized

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3186)
> fix: [ANDROAPP-3186] Clear item before recycle it

- app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3373)
> fix: [ANDROAPP-3373] Missing date and dateTime formats

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3388)
> fix: [ANDROAPP-3388] Hide keyboard when clicking save button

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3029)
> fix: [ANDROAPP-3029] Fix tracked entity type attributes order in search

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ANDROAPP-3375](https://jira.dhis2.org/browse/ANDROAPP-3375)
> fix: [ANDROAPP-3375] Offline tei cards not showing the attributes dropdown arrow

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
- app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
[ANDROAPP-3392](https://jira.dhis2.org/browse/ANDROAPP-3392)
> fix: [ANDROAPP-3392] Adds correct hint label to search fields

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/test/java/org/dhis2/uicomponents/map/layer/MapLayerManagerTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3395)
> fix: [ANDROAPP-3395] refactor mapManager initialization and get featureType for each layer

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
- app/src/main/res/layout/enrollment_activity.xml
- app/src/main/res/layout/section_selector_fragment.xml
**Main issue**
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3079)
**Related issue**
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3387)
> fix: [ANDROAPP-3079] Freeze on data entry for long forms

- RELEASE.md
- app/src/main/res/layout/item_search_tracked_entity.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-zh/strings.xml
- buildsystem/dependencies.gradle
- whatsnew/whatsnew-en-US
> feat: SDK, translations and release notes

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
> fix: [ANDROAPP-3380] Do not preselect enrollment org unit if scope is not capture

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3396)
> fix: [ANDROAPP-3396] Sync TEI for tracker events granular sync

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3439)
> fix: [ANDROAPP-3439] Text fields sending data twice

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
[ANDROAPP-3434](https://jira.dhis2.org/browse/ANDROAPP-3434)
> fix: [ANDROAPP-3434] Org Unit filter in dashboard now updates total filters count

- app/src/main/java/org/dhis2/data/forms/dataentry/validation/IntegerValidator.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/validation/NumberValidator.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/validation/ValueTypeValidatorFactory.kt
- app/src/main/java/org/dhis2/utils/ValidationUtils.kt
- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
- app/src/test/java/org/dhis2/data/forms/dataentry/validation/IntegerValidatorTest.kt
- app/src/test/java/org/dhis2/data/forms/dataentry/validation/NumberValidatorTest.kt
- app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3394)
> Create INTEGER valueType validator

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/test/java/org/dhis2/utils/filters/FilterManagerTest.kt
> fix: [ANDROAPP-3434] update total filters

- app/src/main/res/layout/item_search_tracked_entity.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3435)
> fix [ANDROAPP-3435] align TEIs separator line

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateView.java
- app/src/main/java/org/dhis2/utils/customviews/TimeView.java
[ANDROAPP-3443](https://jira.dhis2.org/browse/ANDROAPP-3443)
> fix: [ANDROAPP-3443] Makes the icon on the date, datetime, and time fields clickable

- app/src/main/java/org/dhis2/Bindings/ViewExtensions.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3374)
> fix: [ANDROAPP-3374] Event list should have rounded top corners

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
> fix: remove ignore teidashboard tests

- app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
- app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
- app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
- app/src/main/java/org/dhis2/utils/customviews/DateView.java
- app/src/main/java/org/dhis2/utils/customviews/FieldLayout.java
- app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
- app/src/main/java/org/dhis2/utils/customviews/TimeView.java
- app/src/main/java/org/dhis2/utils/customviews/YesNoView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3442)
> fix: [ANDROAPP-3442] The X button is shown even when no data can be deleted

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3447)
> fix: [ANDROAPP-3447] Crash when event program has a displayInList image

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3394)
> fix: [ANDROAPP-3394] Remove float conversion whe storing integer values

- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/dhislogic/DhisProgramUtils.kt
- app/src/main/java/org/dhis2/data/dhislogic/DhisTrackedEntityInstanceUtils.kt
- app/src/main/java/org/dhis2/data/filter/DataSetFilterSearchHelper.kt
- app/src/main/java/org/dhis2/data/filter/EventProgramFilterSearchHelper.kt
- app/src/main/java/org/dhis2/data/filter/FilterController.kt
- app/src/main/java/org/dhis2/data/filter/FilterHelperActions.kt
- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
- app/src/main/java/org/dhis2/data/filter/TrackerFilterSearchHelper.kt
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepository.kt
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModelMapper.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/resources/ResourceManager.kt
- app/src/test/java/org/dhis2/data/filter/DataSetFilterSearchHelperTest.kt
- app/src/test/java/org/dhis2/data/filter/EventProgramFilterSearchHelperTest.kt
- app/src/test/java/org/dhis2/data/filter/TrackerFilterSearchHelperTest.kt
- app/src/test/java/org/dhis2/usescases/main/program/HomeRepositoryImplTest.kt
- app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3299)
> fix: [ANDROAPP-3299] Discrepancies between home and search screen filters

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3446)
> fix : [ANDROAPP-3446] Indicator cannot load when one program indicator expression fails

- app/src/main/java/org/dhis2/data/filter/FilterPresenter.kt
- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.java
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainModule.kt
- app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
- app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
- app/src/main/java/org/dhis2/utils/filters/OrgUnitFilterHolder.java
- app/src/main/java/org/dhis2/utils/filters/sorting/FilteredOrgUnitResult.kt
- app/src/main/res/layout/filter_org_unit.xml
- app/src/test/java/org/dhis2/usescases/main/program/HomeRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3278)
> feat: [ANDROAPP-3278] show dropdown with results of orgUnits filters

- docs/src/commonmark/en/content/implementation-guide/mobile-device-specs.md
> docs: Update mobile specs to include Google

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
- app/src/main/res/layout/item_carousel_program_event.xml
> [ANDROAPP-3436] Fix arrow animation in layout

- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/test/java/org/dhis2/uicomponents/map/layer/MapLayerManagerTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3395)
> fix: [ANDROAPP-3395] Fix map init

- docs/src/commonmark/en/content/capture-app/recommendations-for-a-dhis2-mobile-deployment.md
- docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
- docs/src/commonmark/en/dhis2_android_implementation_guideline_INDEX.md
Added info on the guidelines to explain that they are valid for 2.3
> docs: Update docs info to say 2.3 [skip ci]

- scripts/prlabels.py
> feat: [ANDROAPP-3458] Added script to label prs

- docs/src/commonmark/en/content/tech-guides/README.md
Added the other guide to the README
> Add current guides and desc in REAMDE.md

- app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/robot/ProgramEventsRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
> test: [program-event] add test cases

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/utils/WebViewActivity.kt
- app/src/main/res/layout/activity_webview.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2747)
> fix: [Androapp 2747] Emtpy screen on recover account

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/SectionHandler.kt
- app/src/test/java/org/dhis2/data/forms/dataentry/SectionHandlerTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3481)
> fix: [ANDROAPP-3481] Crash due to invalid cast in DataEntryAdapter

- app/src/androidTest/java/org/dhis2/AppTest.kt
- app/src/main/java/org/dhis2/App.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3478)
> feat: [ANDROAPP-3478] disable analytics in AppTest for espresso tests

- app/src/main/java/org/dhis2/data/prefs/PreferenceProviderImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3477)
> fix: [ANDROAPP-3477] don't store pass if empty and catch exceptions

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
> fix: [ANDROAPP-3474] Map layer button crash and adapter init before styles

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
- app/src/main/java/org/dhis2/utils/DateUtils.java
> fix: [ANDROAPP-3433] change database format for DateTime fields

- app/src/main/java/org/dhis2/utils/WebViewActivity.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2747)
> fix: [ANDROAPP-2747] Fix submit recover address button feedback

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
> fix: map ui test

- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3496)
> fix: [ANDROAPP-3496] enrollment from-to filter

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3501)
> fix: [ANDROAPP-3501] display TEIs on map when creating new relationship

- app/src/main/res/layout-land/activity_search.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3303)
> fix: [ANDROAPP-3303] Hide close filters arrow in landscape search screen

- app/src/main/java/org/dhis2/App.java
- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapEventToFeatureCollection.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
- app/src/main/res/layout-land/activity_search.xml
- app/src/test/java/org/dhis2/uicomponents/map/geometry/MapEventToFeatureCollectionTest.kt
- app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
> feat: last 2.3.1 changes

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
- tableview/src/main/java/com/evrencoskun/tableview/adapter/recyclerview/holder/AbstractViewHolder.java
- tableview/src/main/java/com/evrencoskun/tableview/listener/itemclick/CellRecyclerViewItemClickListener.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2986)
> fix: [ANDROAPP-2986] Long text cells require long click

- app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
- app/src/main/java/org/dhis2/usescases/events/ScheduledEventActivity.kt
- app/src/main/java/org/dhis2/usescases/events/ScheduledEventContract.kt
- app/src/main/java/org/dhis2/usescases/events/ScheduledEventModule.kt
- app/src/main/java/org/dhis2/usescases/events/ScheduledEventPresenterImpl.kt
- app/src/test/java/org/dhis2/usescases/events/ScheduledEventPresenterImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3503)
> fix: [ANDROAPP-3503] Open form/event initial screen when setting date to schedule event

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3511)
> fix: [ANDROAPP-3511] handle null catOptionCombo

- app/build.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3520)
> fix: [ANDROAPP-3520] update constraint-layout library

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/androidTest/java/org/dhis2/usescases/searchte/robot/FilterRobot.kt
Search Test: Mixing search field, filter, and sorting.
[ Jira issue](https://jira.dhis2.org/browse/ANDROAPP-3512)
- Test steps: 
Type on field
Click on Filter
Filter by
Click on sort
Check filter and total filter counter (when sorting, filter counter+1)
Check TEIs matches filter and search info
- Add filter and total filter counter to previous tests
- Fix strings previous tests
> test: [ANDROAPP-3512] Mix Search and Filter test

- app/src/main/java/org/dhis2/uicomponents/map/model/EventUiComponentModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3522)
> fix: [ANDROAPP-3522] Maps not rendering when TEType has no icon

- app/src/main/res/layout/activity_main.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3533)
> fix: [ANDROAPP-3533] Incorrect placement of the filter indicator in home screen

- app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowTest.kt
Search Test: new TEI enrollment and check enrollment is open and not sync.
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3524)
- TEI enrollment
- filter by open enrollment and not sync
> test: [ANDROAPP-3524] create TEI and check enrollment

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
- app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3535)
> fix: [ANDROAPP-3535] Add all data approval states to check

- app/src/main/java/org/dhis2/Bindings/Extensions.kt
- app/src/main/java/org/dhis2/widgets/DhisCustomLauncher.kt
[ jira issue ](https://jira.dhis2.org/browse/ADROAPP-3529)
> fix: [ADROAPP-3529] Widget not rendering correct icon

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
> fix: [ANDROAPP-3532] Set url after scanning QR

- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
Fix the overdue filter request, by enrolling a TEI and then update an event, changing the due date (1 month less than the current)
[jira issue](https://jira.dhis2.org/browse/ANDROAPP-3512)
> test: [ANDROAPP-3512] Fix overdue filter test

- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3453)
> feat: [ANDROAPP-3453] (Maps) don't move camera to enrollment

- app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3019)
> fix: [ANDROAPP-3019] org unit of existing event not editable

- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3466)
> fix: [ANDROAPP-3466] display device position on maps

- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3551)
> fix: [ANDROAPP-3551] add all relationships to featureCollections 

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
> fix: [ANDROAPP-3561] Assigned to me filter is not displayed in tracker programs

- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3553)
> fix: [ANDROAPP-3553] handle image when TEI is not downloaded

- app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3538)
> fix: [ANDROAPP-3538] Stage access is not set properly at event creation

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.kt
- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3571)
> fix: [ANDROAPP-3571] hide sync state icon creating relationship

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_program.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3514)
> feat: [ANDROAPP-3514] add BottomNavigation to home

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3516)
> fix: [ANDROAPP-3516] update color of bottomNavigation

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/utils/NetworkUtils.java
[ANDROAPP-3465](https://jira.dhis2.org/browse/ANDROAPP-3465)
> feat: [ANDROAPP-3465] Removes google play services - Dialog removal

- app/src/androidTest/java/org/dhis2/common/matchers/ChartMatchers.kt
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/analytics/AnalyticsModel.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/ChartViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsView.kt
- app/src/main/res/menu/dashboard_menu.xml
- app/src/main/res/menu/dashboard_menu_group.xml
- app/src/main/res/values/strings.xml
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToBarEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarData.kt
[ANDROAPP-3540](https://jira.dhis2.org/browse/ANDROAPP-3540)
> feat: [ANDROAPP-3540] Adds Bar ChartType to the analytics module

- app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
- app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3539)
> fix: [ANDROAPP-3539] update sdk

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/res/layout/activity_event_capture.xml
- app/src/main/res/layout/fragment_notes.xml
- app/src/main/res/menu/navigation_event_menu.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3517)
> feat: [Androapp-3517] Implement new navigation in event forms

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/res/layout/activity_dataset_table.xml
- app/src/main/res/layout/fragment_dataset_section.xml
- app/src/main/res/menu/navigation_dataset_menu.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3518)
> feat: [ANDROAPP-3518] New navigation in data sets

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3592)
> fix: [ANDROAPP-3592] Cat. Option combo selector not showing up

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3594)
> fix: [ANDROAPP-3594] Relationships not showing in the search map

- app/src/androidTest/java/org/dhis2/common/matchers/ChartMatchers.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
- app/src/main/res/layout/item_chart.xml
- app/src/main/res/menu/dashboard_menu.xml
- app/src/main/res/menu/dashboard_menu_group.xml
- app/src/main/res/values/strings.xml
- dhis_android_analytics/build.gradle
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableAdapter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableHolder.kt
- dhis_android_analytics/src/main/res/layout/item_table_cell.xml
- dhis_android_analytics/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3542)
> feat: [ANDROAPP-3542] render analytic data as table

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
- app/src/main/res/layout/form_radio_button_horizontal.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3555)
> fix: [ANDROAPP-3555] Radiobutton misbehaviour

- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3600)
> fix: [ANDROAPP-3600] Add click listener when showing info dialog on log in

- app/src/main/java/org/dhis2/data/dhislogic/DhisTrackedEntityInstanceUtils.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3574)
> fix: [ANDROAPP-3574] check overdue events
