app/src/main/res/values/styles.xml

Fixes issue when on some devices the dialog alert button were colored white and couldn't be seen.

Androapp 1794 - Fixes alert's buttons not showing

---

app/src/main/java/org/dhis2/utils/custom_views/DateTimeView.java
app/src/main/java/org/dhis2/utils/custom_views/DateView.java
app/src/main/java/org/dhis2/utils/custom_views/TimeView.java

Fixes the date, datetime and time value type fields to reset picker's initial value when shown.
Jira Issue: [ANDROAPP-2253](https://jira.dhis2.org/browse/ANDROAPP-2253)

fix(DateTimeCustomView): Resets picker initial value when date picker is shown

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java

Fixes that a re-opened event showed the finish and complete bottom sheet and did't allowed a user to move to different sections.

fix(EventCapturePresenterImpl): Fixes that a re-opened event showed the finish and complete bottom sheet

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java

This commit fixes a bug when wrong pattern appears and changes another field and returns the focus of previous field.
https://jira.dhis2.org/browse/ANDROAPP-2342

fix: when wrong patters remove the dataelement value

---

docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md

The index is using now the common section from the main repository in dhis2-docs

docs: Update dhis2_android_capture_app_INDEX.md [skip ci]

---

app/src/dhisNoSMS/java/org.dhis2.Bindings/ContextExtensions.kt

[issue](https://jira.dhis2.org/browse/ANDROAPP-2845)

fix: [ANDROAPP-2845] Missing import in ContextExtension

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java

[issue](https://jira.dhis2.org/browse/ANDROAPP-2923)

fix: Crash on search initialization when results come before setting trackedEntityType

---

app/src/main/res/values/strings.xml

I just stumbled on this - it appears to be a Google API key (presumably for maps) which isn't used anywhere.  As such I think it should probably be removed? (we shouldn't hard-code API keys anyways)

chore: remove google api key from strings.xml

---

app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
app/src/main/java/org/dhis2/utils/Constants.java
app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt

This PR was already tested and merged to the develop branch in PR #1349, but it's needed in 2.1.1.

chore: [ANDROAPP-2908] Separates QR code formats depending ValueTypeRenderingType

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
app/src/main/res/layout/activity_event_initial.xml

[issue](https://jira.dhis2.org/browse/ANDROAPP-3020)

fix: [ANDROAPP-3020] Tint event initial icon with the same colors as in home screen

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetRHeaderHeader.java
app/src/main/res/layout/item_dataset_header.xml

Allow text to autoscroll if it does not fit in the column header
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3077)
Set the ellipsize mode of the textview to marquee

fix: [ANDROAPP-3077] Show complete text in dataset column header

---

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java

Handles back button and close keyboard on search fields.
[ANDROAPP-3041](https://jira.dhis2.org/browse/ANDROAPP-3041)
Handles back button and close keyboard on search fields by removing the call to AbstractActivity `back` method and override it in the SearchTEActivity class

fix: [ANDROAPP-3041] back/close keyboard on the search fields.

---

app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
app/src/main/res/layout/custom_text_view_cell.xml
tableview/src/main/java/com/evrencoskun/tableview/ITableView.java
tableview/src/main/java/com/evrencoskun/tableview/TableView.java
tableview/src/main/java/com/evrencoskun/tableview/handler/ScrollHandler.java
tableview/src/main/java/com/evrencoskun/tableview/handler/SelectionHandler.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3038)
One a cell is selected, the whole table scrolls to that column position.

fix: [ANDROAPP-3038] Wrong behaviour when selecting a non visible cell in the table

---

app/src/main/java/org/dhis2/data/prefs/Preference.kt
app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialComponent.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenter.java
app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2335)
Added test to check that the returned org unit is the correct one in event initial screen.
Due to the fact that this activity is going to dissapear in the near future I have decided not to include any more tests.

feat: [ANDROAPP-2335] Preselect org unit when adding sequential events to a program

---

app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java

Scrolls open section to the top of the RecyclerViewhe related jira issue if it exists.
[ANDROAPP-3104](https://jira.dhis2.org/browse/ANDROAPP-3104)
Adds a method to get the open section position in the adapter and scrolls to that position

fix: [ANDROAPP-3104] Scrolls open section to the top of the RecyclerView

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java

Adds section title when there is only one section and removes bottom section shadow when the form has no section
[ANDROAPP-3093](https://jira.dhis2.org/browse/ANDROAPP-3093)
We need to make sure the the sectionList has an sectionUid not empty to determine that it has a section. If the sectionUid is empty it mean it a form with no section.
WIP

fix: [ANDROAPP-3093] Adds section title when there is only one section

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java

Saves datetime field without seconds in the database.
[ANDROAPP-3108](https://jira.dhis2.org/browse/ANDROAPP-3108)
We format the date object as a string with this pattern `"yyyy-MM-dd HH:mm"`
- [x ] 9.X - 10.X

fix: [ANDROAPP-3108] Saves datetime field without seconds in the database.

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
app/src/main/res/layout/form_section.xml

Removes background from xml and adds it programmatically
[ANDROAPP-3109](https://jira.dhis2.org/browse/ANDROAPP-3109)
Removes background from xml and adds it programmatically in the setionHolder using ContextCompat's getDrawable

fix: [ANDROAPP-3109] Removes background from xml and adds it programmatically

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java

updates the complete/open status icon and label when a dataset is complete or re-open.
[ANDROAPP-3037](https://jira.dhis2.org/browse/ANDROAPP-3037)
updates the complete/open status icon and label when a dataset is complete or re-open.

fix: [ANDROAPP-3037] updates the complete/open status icon and label when a dataset is complete or re-open.

---

app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java

Form now distinguish between a opening and scrolling to the top a previously closed section. Also it does not scrolls to the top when a value of a field is changed.
[ANDROAPP-3104](https://jira.dhis2.org/browse/ANDROAPP-3104)
1. In the adapter we have to determine what section is mark as open, using the isOpen() method and make a public method to get that section position in the list.
2. In the activity we have to setup a callback in the adapter's swap() method to have the layoutManager scroll to the last open section, using the public method describe in the above step.

fix: [ANDROAPP-3104] Open section scroll to top

---

app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
app/src/test/java/org/dhis2/bindings/TrackedEntityInstanceExtensions.kt
buildsystem/dependencies.gradle

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3122)
Do not return a new list when filtering a datasource.

fix: [ANDROAPP-3122] Fix crash when deleting enrollment

---

app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java

Removes the grammar red lines from option sets options when there are strange words.
[ANDROAPP-3094](https://jira.dhis2.org/browse/ANDROAPP-3094)
Added the TEXT_FLAG_NO_SUGGESTION inputText to the option set's editText.

fix: [ANDROAPP-3094] Removes the grammar red lines from option sets options

---

app/src/main/res/values/styles.xml

[ANDROAPP-2849](https://jira.dhis2.org/browse/ANDROAPP-2849)
Adds a style setting to the TextInputLayout style to add the same color as the background color

fix: [ANDROAPP-2849] Removes Long TextField dark gray color.

---

app/src/main/java/org/dhis2/utils/filters/OrgUnitFilterHolder.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3043)
We should clear focus when going to OU tree selector because of that OU adapter was not updating when returning from tree selector

fix: [ANDROAPP-3043] update OU filter list

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
app/src/main/res/layout/violation_rules_bottom_sheet.xml

Hides "complete anyways" button from error bottomsheet if the dataset has set that it must be valid to complete.
[ANDROAPP-1157](https://jira.dhis2.org/browse/ANDROAPP-1157)
Check if the dataset has the setting "Complete allowed only if validation passes" in its configuration and show the complete button only when this setting is false.

fix: [ANDROAPP-1157] Hides "complete anyways" button when dataset has set that it must be valid to complete

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
app/src/main/res/layout/activity_event_capture.xml

An user has reported that the note fragment is selected automatically during data entry.
Cound not be replicated and in the code there is no way to change pages except by scrolling or clicking in the correct tab so it is highly possible it is an issue in the device screen.
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3143)
No fix is needed. But just in case, we have migrated the viewpager to viewpager2.

fix: [ANDROAPP-3143] Set viewpager2 in event data entry

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3113)
Close keyboard when a field with datetime is open

fix: [ANDROAPP-3113] close keyboard before open calendar picker

---

app/src/main/res/layout/form_spinner_selection.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3098)
Add a horizontal scroll view to scroll items when it is configured as horizontal checkboxes or horizontal radio button and there are many items

fix: [ANDROAPP-3098] add horizontal scroll when to many options

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt

[ANDROAPP-3166](https://jira.dhis2.org/browse/ANDROAPP-3166)
Checks is selectedEnrollment is not null to set its status in the holder

fix: [ANDROAPP-3166] Fixes crash when selectedEnrollment is null in SearchTEViewHolder

---

app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3164)
Check dialog is not visible when displaying it to avoid show it two times and get a crash

fix: [ANDROAPP-3164] avoid showing orgUnit dialog two times

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java

Disable horizontal swipe in dataset tabs. Change tab will be able only by clicking it
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3158)

fix: [ANDROAPP-3158] disable horizontal swipe on dataset tabs

---

app/build.gradle
app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
app/src/main/assets/paperwork.json
app/src/main/java/org/dhis2/App.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
app/src/main/java/org/dhis2/utils/idlingresource/CountingIdlingResourceSingleton.kt

With this PR, all "Thread.sleep" are deleted and espresso is sync when tei's are loaded in search screen.
As a result, we're enabling some important tests for us. This solution is temporal until we review all threads and work that is done in UI/IO and whats being done in the main thread.

fix: Fix search issue espresso

---

app/src/main/java/org/dhis2/utils/filters/AssignToMeFilterHolder.kt

[ANDROAPP-3173](https://jira.dhis2.org/browse/ANDROAPP-3173)
Set the filter arrow visibility from GONE to INVISIBLE in the AssignedToMeHolder, to give space to switch view to accepts clicks events

fix: [ANDROAPP-3173] fix the assigned to me filter switch

---

app/src/main/java/org/dhis2/usescases/main/MainActivity.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3169)
Check presenter is initialized before using it.

fix: [ANDROAPP-3169] check presenter is initialized

---

app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
app/src/main/assets/paperwork.json
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt

[ANDROAPP-3162](https://jira.dhis2.org/browse/ANDROAPP-3162)
Updates enrollment in the eventAdapter
Functional test

fix: [ANDROAPP-3162] refreshes events status when enrollment is completed/reopen

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP3014)
DisplayKeyValue fields shouldn't count
for percentage calculation

fix: [ANDROAPP-3014] display fields do not count for percentage

---

app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3182)
Server URL and username have to be saved and restored when user do log out also when device do not have fingerprint option

fix: [ANDROAPP-3182] save server and user when login

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java

[ANDROAPP-3213](https://jira.dhis2.org/browse/ANDROAPP-3213)
- [x ] I have performed a self-review of my own code

fix: [ANDROAPP-3213] Changes the tab title when the dataset has no section from "Tables" to "Data"

---

app/src/main/java/org/dhis2/Bindings/StringExtensions.kt
app/src/main/java/org/dhis2/uicomponents/map/geometry/LngLatValidator.kt
app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
app/src/main/res/values/strings.xml
app/src/test/java/org/dhis2/bindings/StringExtensionsTest.kt

[ANDROAPP-3167](https://jira.dhis2.org/browse/ANDROAPP-3167)

fix: [ANDROAPP-3167] truncates coordinates values when entered manually by user.

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
app/src/main/res/layout/violation_rules_bottom_sheet.xml
app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt

[ANDROAPP-3245](https://jira.dhis2.org/browse/ANDROAPP-3245)

fix: [ANDROAPP-3245] hide error bottom sheet when clicking save on dataset

---

app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3222)

fix: [ANDROAPP-3222] Keyboard is closed when moving to next cell

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3140)
We should keep field focus to be able to open the corresponding keyboard.
Also, we have to keep focus on selected item when selecting a field that is above current

fix: [ANDROAPP-3140] don't lose focus when change focus manually

---

app/src/main/res/layout/dialog_body.xml

[ANDROAPP-3228](https://jira.dhis2.org/browse/ANDROAPP-3228)

fix: [ANDROAPP-3228] sets same style to OK button in the dialog

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3250)

fix: [ANDROAPP-3250] Missing catCombo in event initial screen

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3275)

fix: [ANDROAPP-3275] Indicator name is not always displayed

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt

[ANDROAPP-3274](https://jira.dhis2.org/browse/ANDROAPP-3274)

fix: [ANDROAPP-3274] Prevents user's ability to add an enrollment when doing an empty search

---

app/src/main/java/org/dhis2/usescases/settings/ErrorAdapter.java
app/src/main/java/org/dhis2/usescases/settings/ErrorViewHolder.java
app/src/main/java/org/dhis2/usescases/settings/models/ErrorViewModel.kt

[ANDROAPP-3287](https://jira.dhis2.org/browse/ANDROAPP-3287)

fix: [ANDROAPP-3287] handles correct selection when scrolling in the sync error log 

---

app/src/main/assets/paperwork.json
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java

@ferdyrod @mmmateos @Balcan 
When you enter search for some programs, for example XX TRACKER for android-current or the ones that @jaboto was testing you could see in the logs that multiple unnecesary network calls were being launched. Here are a few things that I have found out:
- Threading in search is no correct in some places. (UI thread being used when it should not)
- **setProgram** was called twice. There is an distinctUntilChanged (not the best solution) for current program (so the second call was being ignore) but setProgram method was sending events for query processor that were not being ignore.
- _FilterManager.getInstance().asFlowable().startWith(FilterManager.getInstance())_ with combineLatest was actually triggering two events, this combine with setProgram **was adding a …

fix: Multiple unnecessary network calls in search screen 

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java

[ANDROAPP-3309](https://jira.dhis2.org/browse/ANDROAPP-3309)

fix: [ANDROAPP-3309] Shows Dataset save button after Validations error dialog is displayed and closed

---

app/src/main/java/org/dhis2/data/sorting/SearchSortingValueSetter.kt
app/src/test/java/org/dhis2/data/sorting/SearchSortingValueSetterTest.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3308)

fix: [ANDROAPP-3308] Fix crash when using event date sorting

---

app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java

[ANDROAPP-3330](https://jira.dhis2.org/browse/ANDROAPP-3330)

fix: [ANDROAPP-3330] Prevents crash when section has no data elements

---

app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt
app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
app/src/main/java/org/dhis2/usescases/main/MainView.kt
app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt

In the Main screen, if we are in a section different than Home, when the user tap back, the current section changes but the transition is not made. Then is user taps again, the app consider it is in Home and exits the application.
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3261

fix: Navigate back to home from a different section in navigation drawer

---

app/src/main/res/values/strings.xml

[ANDROAPP-3347](https://jira.dhis2.org/browse/ANDROAPP-3347)

chore: [ANDROAPP-3347] updates the custom crash activity's strings

---

app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java

[ANDROAPP-3326](https://jira.dhis2.org/browse/ANDROAPP-3326)

fix: [ANDROAPP-3326] Prevent crash on datasets with optionset

---

app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt

[ANDROAPP-3342](https://jira.dhis2.org/browse/ANDROAPP-3342)

fix: [ANDROAPP-3342] Do not round value in field of ValueType UNIT_INTERVAL

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
app/src/main/res/layout/item_search_tracked_entity.xml

TEI card downloading button does not work and message showing "downloading %null" is displayed. It should show a more descriptive text.
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3255)

fix: [Androapp 3255] Change downloading feedback

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/RelationshipLiveAdapter.java

[ANDROAPP-3363](https://jira.dhis2.org/browse/ANDROAPP-3363)

fix: [ANDROAPP-3363] Relationship Tei cards List not showing attributes in same order

---

app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3378)

fix: [ANDROAPP-3378] Option sets in data set had white text color

---

app/src/main/java/org/dhis2/Bindings/CategoryOptionExtensions.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
app/src/main/java/org/dhis2/utils/customviews/CatOptionPopUp.kt
app/src/test/java/org/dhis2/data/dhislogic/CategoryOptionExtensionsKtTest.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3391)

fix: [ANDROAPP-3391] Event init takes too long when category has too many options

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt
app/src/main/res/layout/item_stage_section.xml
app/src/main/res/values/themes.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3371)

fix: [ANDROAPP-3371] Theme color prevented seeing the add event button

---

app/src/main/res/layout/custom_text_view_accent.xml

[ANDROAPP-3431](https://jira.dhis2.org/browse/ANDROAPP-3431)

fix: [ANDROAPP-3431] Enables clicks on org unit field in the search activity.

---

app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3395

fix: [ANDROAPP-3395] Map not showing icons on initialization when search backdrop is active

---

docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
docs/src/commonmark/en/dhis2_android_implementation_guideline_INDEX.md

Add SMS gateway information in the implementation guide and the reference on the configuration guide (SMS sync feature)

docs: add SMS to implementation guide and references [skip ci]

---

app/src/main/res/layout/date_time_view.xml
app/src/main/res/layout/date_time_view_accent.xml

[ANDROAPP-3443](https://jira.dhis2.org/browse/ANDROAPP-3443)

fix: [ANDROAPP-3443] Adds ripple effect to date, datetime, and time field's icons.

---

app/src/main/java/org/dhis2/data/dhislogic/Authorities.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryTest.kt
app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryTest.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3366)

fix: [ANDROAPP-3366] Check datavalue authority in data sets

---

scripts/reviewers.py

fix: Reviewers script now prevents error when PR  owner is different from the established developers

---

app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java

validates that a the first visible position from the form is not greater than the items size, and returns false if it is instead of a IndexOutOfBoundsError
[ANDROAPP-3498](https://jira.dhis2.org/browse/ANDROAPP-3498)

fix: [ANDROAPP-3498] IndexOutOfBounds in dataEntryAdapter when checking section header

---

app/src/main/res/layout/dialog_edittext.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3519)

fix: [ANDROAPP-3519] set editText max height for longtext dialog

---

app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3525)

fix: [ANDROAPP-3525] Percentage icon set in wrong fields

---

app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3534

fix: [ANDROAPP-3534] Unable to type in text fields in data set

---

app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
app/src/main/java/org/dhis2/data/forms/dataentry/SectionHandler.kt

[ANDROAPP-3471](https://jira.dhis2.org/browse/ANDROAPP-3471)

fix: [ANDROAPP-3471] Sticky section header now sticks

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3629)

fix: [ANDROAPP-3629] Fix clear button for long text fields

---

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetIntents.kt
app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt
app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
app/src/main/res/values/strings.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3584)

fix: [ANDROAPP-3584] Do not close activity when checking complete dataSet

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
tableview/src/main/res/layout/item_table_header.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-1161)

fix: [ANDROAPP-1161] set max width to indicator label

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml

fix: [ANDROAPP-3716] Avoid hiding last edit text with keyboard

---

app/src/main/assets/paperwork.json
app/src/main/java/org/dhis2/Bindings/Bindings.java
app/src/main/res/layout/custom_text_view.xml
app/src/main/res/layout/form_spinner.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3792)

fix: [ANDROAPP-3792] Legends text is cut even if there is enough room

---

app/src/main/res/drawable/ic_map_layers.xml
app/src/main/res/layout-land/activity_search.xml
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/fragment_program_event_detail_map.xml

[ANDROAPP-3971](https://jira.dhis2.org/browse/ANDROAPP-3971)

fix: [ANDROAPP-3791] Map layers icon resized

---

app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java

fix: [ANDROAPP-3822] open keyboard on search for android <= 7

---

app/src/main/assets/paperwork.json
app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt

[ ANDROAPP-3824](https://jira.dhis2.org/browse/ANDROAPP-3824)

fix: [ANDROAPP-3824] autogenerated fields remain non-editable when focusing on other fields. 

---

app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
app/src/test/java/org/dhis2/bindings/TrackedEntityInstanceExtensions.kt

Local teis marked as RELATIONSHIP might hide online teis in search query.
[ ANDROAPP-3827 ](https://jira.dhis2.org/browse/ANDROAPP-3827)
Do not consider RELATIONSHIP teis as valid teis.
--

fix: Filter out RELATIONSHIP teis in search query

---

app/src/main/res/layout/form_image.xml
app/src/main/res/layout/matrix_option_set.xml

fix: [ANDROAPP-3834] disable click on matrix elements when event is not editable

---

docs/src/commonmark/en/content/capture-app/features-supported.md
docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
docs/src/commonmark/en/content/capture-app/programs-specific-features.md
docs/src/commonmark/en/content/capture-app/test.md

Several of the image links in the documentation are broken. This PR updates the links to use the correct paths for the existing images.

fix: correct image links in docs

---

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
app/src/main/java/org/dhis2/utils/reporting/CrashReportController.kt
app/src/main/java/org/dhis2/utils/reporting/CrashReportControllerImpl.kt
app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventMapperTest.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4108

fix: [ANDROAPP-4108] Add breadcrumb to log Event before crash

---

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableAdapter.kt
tableview/src/main/res/layout/item_table_fixed_header.xml

fix: [ANDROAPP-4255] indicators table header width not fixed

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt

fix: [ANDROAPP-4256] display dataset indicators when there is no tables

---

app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4254)

fix: [ANDROAPP-4254] OptionSet rendering type not showing in enrollment forms

---

app/src/main/java/org/dhis2/uicomponents/map/camera/CameraExtension.kt
app/src/main/java/org/dhis2/uicomponents/map/layer/LayerConstants.kt
app/src/main/java/org/dhis2/uicomponents/map/layer/types/FieldMapLayer.kt

fix: [ANDROAPP-4241] don't overlap icon for DE on map

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt

[ANDROAPP-4416](https://jira.dhis2.org/browse/ANDROAPP-4416)

fix: [ANDROAPP-4416] Added top padding to the indicators table in datasets

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt

[ANDROAPP-4416](https://jira.dhis2.org/browse/ANDROAPP-4416)

fix: [ANDROAPP-4416] Adds bottom padding to the indicators table to clear the FAB button

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt

[ANDROAPP-4427](https://jira.dhis2.org/browse/ANDROAPP-4427)

fix: [ANDROAPP-4427] prevents from updating an event status when it is a ReadOnly event.

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt

[ANDROAPP-4439](https://jira.dhis2.org/browse/ANDROAPP-4439)

fix: [ANDROAPP-4439] Prevents NPE crash when opening a relationship that is not local data

---

app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
form/src/main/java/org/dhis2/form/data/FormValueStore.kt
form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4481)

fix: [ANDROAPP-4481] Fix crash in event and multi-section enrollment fields

---

build.gradle

[ANDROAPP-4433](https://jira.dhis2.org/browse/ANDROAPP-4433)

fix: [ANDROAPP-4433] Isolates JCenter-only dependencies

---

build.gradle
buildsystem/dependencies.gradle

[ANDROAPP-4433](https://jira.dhis2.org/browse/ANDROAPP-4433)

refactor: [ANDROAPP-4433] migrates flipper from jcenter to mavenCentral

---

app/src/main/java/org/dhis2/Bindings/Extensions.kt

[ANDROAPP-4260](https://jira.dhis2.org/browse/ANDROAPP-4260)

fix: [ANDROAPP-4260] Selects the first image field as profile image of a tei

---

.gitignore
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
app/src/main/res/layout/table_view_corner_layout.xml
app/src/main/res/values/dimens.xml

[ANDROAPP-3016](https://jira.dhis2.org/browse/ANDROAPP-3016)

feat: [ANDROAPP-3016] Resize arrow prevents reducing more than a minimum size and are aligned to the left

---

app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt

[ANDROAPP-4577](https://jira.dhis2.org/browse/ANDROAPP-4577)

fix: [ANDROAPP-4577] Assign value program rules correctly assigns value to OptionSet fields

---

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt

Solution by google
https://developer.android.com/codelabs/kotlin-android-training-live-data#6

fix: [ANDROAPP-4581] Avoid navigate during activity recreation

---

app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt

Related to [this PR in the SDK](https://github.com/dhis2/dhis2-android-sdk/pull/1737). The FileResourceDirectoryHelper has been migrated to kotlin and expects a NonNull context. This was not considered a breaking change because the context must be NonNull before as well, but it was not imposed by an annotation in Java.
[ANDROSDK-1494](https://jira.dhis2.org/browse/ANDROSDK-1494)

fix: Add requireContext() for FileResourceDirectoryHelper

---

app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt

[ANDROAPP-653](https://jira.dhis2.org/browse/ANDROAPP-653)

fix: [ANDROAPP-653] Correctly clears username field when trying to add a new account and the field was previously filled.

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
app/src/main/res/layout/activity_dataset_table.xml

[ANDROAPP-4331](https://jira.dhis2.org/browse/ANDROAPP-4331)

fix: [ANDROAPP-4331] Granular sync button display in dataset detail screen only.

---

app/src/debug/res/menu/main_menu.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-1655)

feat: [ANDROAPP-1655] Only show troubleshooting option in release apk

---

app/src/debug/AndroidManifest.xml
app/src/main/AndroidManifest.xml

fix: [ANDROAPP-4665] don't hide save button on short forms

---

app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt

[ANDROAPP-4679](https://jira.dhis2.org/browse/ANDROAPP-4679)
According to the[ Android documentation ](https://developer.android.com/reference/android/app/Fragment.html?authuser=1#Fragment%28%29) 
_Every fragment must have an empty constructor, so it can be instantiated when restoring its activity's state. **It is strongly recommended that subclasses do not have other constructors with parameters, since these constructors will not be called when the fragment is re-instantiated**; instead, arguments can be supplied by the caller with [setArguments(Bundle)](https://developer.android.com/reference/android/app/Fragment?authuser=1#setArguments(android.os.Bundle)) and later retrieved by the Fragment with [getArguments()](https://developer.android.com/reference/android/app/Fragment?authuser=1#get …

fix: [ANDROAPP-4679] Avoid fragment recreation in search form

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java

[ANDROAPP-4561](https://jira.dhis2.org/browse/ANDROAPP-4561)

fix: [ANDROAPP-4561] Event detail sync button hidden on events that have EventMode.NEW

---

form/src/main/java/org/dhis2/form/ui/binding/OptionSetSpinnerBindings.kt
form/src/main/res/layout/option_set_select_check_item.xml
form/src/main/res/layout/option_set_select_item.xml
form/src/main/res/layout/pop_up_menu_item.xml

[ jira issue ](https://jira.dhis2.org/browse/[ANDROAPP-4542)

fix: [ANDROAPP-4542] Handle long option names in option sets

---

form/src/main/res/layout/form_check_button.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4739)

fix: [ANDROAPP-4739] Yes only checkbox should not display the "yes" label

---

app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
form/src/main/java/org/dhis2/form/ui/DataEntryAdapter.kt
form/src/main/java/org/dhis2/form/ui/FormViewHolder.kt
form/src/main/java/org/dhis2/form/ui/binding/FieldBindings.kt
form/src/main/res/layout/form_edit_text_custom.xml
form/src/main/res/layout/form_email.xml
form/src/main/res/layout/form_integer.xml
form/src/main/res/layout/form_integer_negative.xml
form/src/main/res/layout/form_integer_positive.xml
form/src/main/res/layout/form_integer_zero_positive.xml
form/src/main/res/layout/form_letter.xml
form/src/main/res/layout/form_long_text_custom.xml
form/src/main/res/layout/form_number.xml
form/src/main/res/layout/form_percentage.xml
form/src/main/res/layout/form_phone_number.xml
form/src/main/res/layout/form_scan.xml
form/src/main/res/layout/form_unit_interval.xml
form/src/main/res/layout/form_url.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4763)

fix: [ANDROAPP-4763] Text fields copied to one another when clicking next

---

app/src/main/res/layout/item_event.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4775)

fix: [ANDROAPP-4775] Event status icon missing start margin

---

app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt
commons/src/main/java/org/dhis2/commons/bindings/ValueExtensions.kt

fix: [ANDROAPP-4790] save 0 and 1 for unit interval

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
app/src/main/java/org/dhis2/utils/customviews/navigationbar/NavigationBottomBar.kt
app/src/main/res/layout-land/activity_search.xml
app/src/main/res/layout/activity_search.xml

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4764)

fix: [ANDROAPP-4764] Keep bottom bar selection when rotating in search screen

---

form/build.gradle

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4842)

feat: [ANDROAPP-4842] Allow form module to access maps

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4870)

fix: [ANDROAPP-4870] Crash when selecting an option from catCombo

---

app/src/main/java/org/dhis2/Bindings/Extensions.kt

Skips the logic to get the profile picture attribute if the TEI has no image attribute values.
[ANDROSDK-1568](https://jira.dhis2.org/browse/ANDROSDK-1568)
Skip the logic
----

feat: [ANDROSDK-1568] Skip profile picture logic when no image values

---

compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt
compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt
compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt

fix: [ANDROAPP-4898] Remove focus on text input component when clicking back

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt

[ANDROAPP-4944](https://dhis2.atlassian.net/browse/ANDROAPP-4944?atlOrigin=eyJpIjoiODFmYzg2NDU0NzBjNGFlNzg5MTY4OWVlOTgxZjU2MjkiLCJwIjoiaiJ9)

fix: [ANDROAPP-4944] Search viewModel's init now runs in background thread

---

app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
buildsystem/dependencies.gradle

fix: [ANDROAPP-4961] Extracting GS1 values for som AI fails

---

commons/src/main/java/org/dhis2/commons/filters/FilterManager.java

fix: [ANDROAPP-4939] Removes enrollment date's filter count when resetting filters

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt

fix: [ANDROAPP-4993] Dataset indicator not updating when saving value

---

app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt

fix: [ANDROAPP-5005] restart sender when sms sync finishes

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepository.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/CategoryDialogInteractions.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventCatComboOptionSelector.kt
app/src/main/java/org/dhis2/utils/category/CategoryDialog.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventCatComboOptionSelectorTest.kt
commons/src/main/java/org/dhis2/commons/data/EventViewModel.kt

fix: [ANDROAPP-5138] CatComboOption not properly set for autogenerated events

---

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
form/src/main/java/org/dhis2/form/data/RuleUtilsProviderResult.kt

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5172)

[ANDROAPP-5172] Avoid ConcurrentModificationException by using iterators

---

app/src/debug/java/org.dhis2/data/appinspector/AppInspector.kt

chore: [ANDROAPP-5267] Disables support for Flipper for devices lower than Android 7 (API 22)

---

ui-components/src/main/java/org/dhis2/ui/items/SyncStatusItem.kt

fix: [ANDROAPP-5275] Set sync status item background to white

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.kt

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-ANDROAPP-5251)

fix: [ANDROAPP-5251] Close sync dialog after form section is opened

---

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt

fix: [ANDROAPP-5310] Adds bottom padding to table to show last item when keyboard is open

---

compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt
compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5130)

[ANDROAPP-5130] Follow-up clicks can be skipped by the app when entering data into tables

---

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt
stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt

Last line item in a list partially covered by on-screen keyboard
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5331
Increasing padding bottom
- [ x] Smartphone Emulator
- [ x] 11.X - 13.X
- [x ] My code follows the style guidelines of this project

Adding padding for table

---

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt

The property `relationPeriods` has been removed in the SDK from the Visualization model as part of [ANDROSDK-1687](https://dhis2.atlassian.net/browse/ANDROSDK-1687). There was just one usage of this property in the Android app, which is removed in the PR.
The parameter has been removed from the function as it didn't have any effect on the result.
[ANDROSDK-1687]: https://dhis2.atlassian.net/browse/ANDROSDK-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [ANDROSDK-1687] Adapt analytics to changes in SDK; remove unused period

---

commons/src/main/java/org/dhis2/commons/filters/FilterManager.java

fix: [ANDROAPP-5253] Removes event status filter check when resetting filters

---

compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
compose-table/src/test/java/org/dhis2/composetable/TableModelTest.kt

fix: [ANDROAPP-5330] Handles indexOutOfBounds when checking for errors in cells

---

app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselTeiHolder.kt

fix: [ANDROAPP-5370] hide navigation button when tei have no coordinate

---

build.gradle.kts
form/build.gradle.kts

chore: [ANDROAPP-5074] Adds desugar to move out zxing-android-embedded from jcenter

---

form/src/main/java/org/dhis2/form/data/EnrollmentRepository.kt

Changes to adapt the application to recent changes in SDK (null-safety)
[ANDROSDK-1717](https://dhis2.atlassian.net/browse/ANDROSDK-1717)
[ANDROSDK-1717]: https://dhis2.atlassian.net/browse/ANDROSDK-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adapt to changes in SDK repositories (list type filters)

---

app/src/main/java/org/dhis2/utils/category/CategoryDialogPresenter.kt
stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockManagerImpl.kt

The SDK has refactored their dataSource classes and now returns a `List<T>` instead of a `MutableList<T>` (Java / Kotlin). It is required to adapt a few methods.
[ANDROSDK-1742](https://dhis2.atlassian.net/browse/ANDROSDK-1742)
[ANDROSDK-1742]: https://dhis2.atlassian.net/browse/ANDROSDK-1742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor filter methods in dataSource

---

commons/src/main/java/org/dhis2/commons/resources/ColorUtils.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/layer/MapLayerDialog.kt

ANDROAPP-5533 crash when colorUtils not instantiated in map layer dialog

---

app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
commons/src/main/java/org/dhis2/commons/bindings/SdkExtensions.kt
commons/src/main/java/org/dhis2/commons/orgunitselector/OURepositoryConfiguration.kt
dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
form/src/main/java/org/dhis2/form/data/EnrollmentRepository.kt
form/src/main/java/org/dhis2/form/data/EnrollmentRuleEngineRepository.kt
form/src/main/java/org/dhis2/form/data/EventRepository.kt
gradle/libs.versions.toml

Adapt to changes in repository nullability (Kotlin migration).
Additionally, it replaces the property `collapsibleSections` by `disableCollapsibleSections`.
[ANDROSDK-1717](https://dhis2.atlassian.net/browse/ANDROSDK-1717)
[ANDROSDK-1717]: https://dhis2.atlassian.net/browse/ANDROSDK-1717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adapt to changes in Kotlin nullability

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
app/src/main/java/org/dhis2/utils/ValueUtils.java
app/src/test/java/org/dhis2/data/filter/TrackerFilterSearchHelperTest.kt
commons/src/main/java/org/dhis2/commons/data/SearchTeiModel.java
commons/src/main/java/org/dhis2/commons/filters/data/FilterPresenter.kt
commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt
commons/src/main/java/org/dhis2/commons/filters/data/TrackerFilterSearchHelper.kt
gradle/libs.versions.toml

This PR uses the new TrackedEntitySearchRepository to search TEIs. This repository has the same method than TrackedEntityInstanceQueryRepository. It returns a new class TrackedEntitySearchItem that includes more information about the TEI, such as the TEI header, the attribute list ready to be displayed and the TE type. More information will be added (profile picture,...). 
The class SearchTeiModel has been modified to include the `header` property. This property is not displayed in the TEI card yet, but it is ready to be used. 
There is no end-to-end integration with the AWSA yet, so it is not possible to test it.
Additionally, it removes some duplicated code in the Android app to improve performance.
[ANDROAPP-5402](https://dhis2.atlassian.net/browse/ANDROAPP-5402)
[ANDROAPP-5402]: …

Use TrackedEntitySearch repository; add TEI header model

---

app/src/main/java/org/dhis2/utils/analytics/AnalyticsInterceptor.kt

The class AnalyticsInterceptor has two properties (`isLogged` and `dhis2Version`) that are evaluated just once. In this way, these properties are not evaluated each time they are used and this works fine if there is a single server.
In the case the user started a session in a server, then logout and login in a different server, these properties are not evaluated again. It has two consequences:
- the apps gets `isLogged=true` even when it is not true, which causes issues accessing the DB.
- the app might include the wrong dhis2Version in the matomo event.
[ANDROAPP-5648](https://dhis2.atlassian.net/browse/ANDROAPP-5648)
The solution is to evaluate this properties in each failed called. The evaluation of these properties is very light and it only happens if the response code is an error …

Analytics: evaluate isLogged and dhis2Version in each failed call 

---

app/src/main/java/org/dhis2/usescases/teiDashboard/data/ProgramConfigurationRepository.kt
app/src/test/java/org/dhis2/data/filter/FilterRepositoryTest.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/ProgramConfigurationRepositoryTest.kt
commons/src/main/java/org/dhis2/commons/bindings/SdkExtensions.kt
commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt
dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ChartsRepositoryTest.kt
gradle/libs.versions.toml

Update android SDK to snapshot 52.
Adapt to changes in ObjectRepositories due to refactor to Kotlin.
[ANDROSDK-1768](https://dhis2.atlassian.net/browse/ANDROSDK-1768]
[ANDROSDK-1768]: https://dhis2.atlassian.net/browse/ANDROSDK-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update SDK to snapshot 52; adapt object repositories

---

form/src/main/java/org/dhis2/form/ui/provider/inputfield/ImageInputProvider.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/SignatureProvider.kt

Add empty imageClick implementation for input Image and Input signature

Empty onImageClick implementation

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchPageConfigurator.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchPageConfiguratorTest.kt

There are two expensive evaluations performed before displaying the Program home screen (the TEI list). They are the evaluation of `displayMap` and `displayAnalytics`, which determined if these tabs must be shown in the bottom menu. This PR improves the performance of both variables.
[ANDROAPP-5660](https://dhis2.atlassian.net/browse/ANDROAPP-5660)
Improvements for displayMap:
- Early return when the conditions are enough to determine if the result is true or false.
- Single DB query instead of traversing all the events in the program.
Some measurements:
- Physical device, Android 8, program without coordinates with ~2000 teis: it improves from ~8s to ~0.070s (no early return, improvement thanks to single DB query).
- Physical device, Android 8, program with coordinates with 50 teis: it …

Improve performance in program bottom menu evaluation

---

app/src/main/java/org/dhis2/utils/analytics/AnalyticsInterceptor.kt

There is constraint in the access to the database when encryption is enabled: if a thread opens a transaction, the database is locked for other threads and they can't read. This issue seems to be a limitation of SQLCipher and it is not clear if there is a possible workaround to this. This is the reason why it doesn't happen when the database is not encrypted.
In order to minimize changes during the soft freeze, the approach here was to change the way matamo events are sent. The AnalyticsInterceptor class emitted the event in a blocking way, causing a deadlock if the database was locked by other thread. The new approach is to send the matomo event in an IO thread, so the event is sent once the database is unlocked.
The root cause of this issue is still in the SDK …

fix: [ANDROAPP-5727] Defer matomo event tracking to IO thread

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt
app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt
app/src/test/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapperTest.kt
commons/src/main/java/org/dhis2/commons/date/DateExtensions.kt
commons/src/main/java/org/dhis2/commons/resources/ResourceManager.kt
commons/src/main/res/values/strings.xml

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5704)
- I have create a new extension to create `overdueUiText` and added strings to the `common` module. Without those strings we would have pass a type like `OverduePeriod` and use a when block at call site to extract the string. I initially tried that, but if there are multiple places with this extension we will be duplicating the conditional and potentially using wrong strings. So, made it it part of the extension it self.
- There is also a overdue string usage in `EventCardMapper`, since this story only showed TEI card, wasn't sure if that required updating. So, didn't change it. Let me know if that needs to be changed as well.

fix: [ANDROAPP-5704] Overdue date in patient line list follows inconsistent format

---

app/src/main/java/org/dhis2/usescases/settings/SettingsRepository.kt
app/src/main/java/org/dhis2/utils/granularsync/SMSSyncProvider.kt
app/src/main/java/org/dhis2/utils/granularsync/SMSSyncProviderImpl.kt
app/src/test/java/org/dhis2/usescases/settings/SettingsRepositoryTest.kt
app/src/test/java/org/dhis2/utils/granularsync/SMSSyncProviderTest.kt
gradle/libs.versions.toml

Adapt to changes in the SDK due to the refactor from Java to Kotlin. They are mainly caused by Kotlin-Java interoperability shortcuts: a java method called "getName()" is suggested as just ".name" by Android Studio in Kotlin code. If the method keeps the signature "getName()" when refactored to Kotlin, the shortcut does not work anymore and the method must be accessed by "getName()" in Kotlin as well.

feat: Update to DHIS2 Android SDK 1.9.1-20231215.100321-10

---

app/src/main/java/org/dhis2/usescases/teiDashboard/ui/TeiDetailDashboard.kt
app/src/main/res/layout-land/fragment_tei_data.xml
app/src/main/res/layout/fragment_tei_data.xml

The scroll functionality on the event list seems to be causing issues, hiding elements beneath the dashboard. This scrolling shouldn't exist.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5663)
We can change the `LazyColumn` to `Column` for the card layout, and we can use nested scroll view to make the events list and card layout scrollable.

fix: [ANDROAPP-5663] Tei dashboard event list scrolling getting clipped

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCatCombo.kt

fix: [ANDROAPP-5821] return null if default cat Combo UID is empty string

---

app/src/androidTest/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/EventInitialTest.kt
app/src/main/java/org/dhis2/usescases/events/ScheduledEventActivity.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCatCombo.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/models/EventCatCombo.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/models/EventCatComboUiModel.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/models/EventInputDateUiModel.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/InputFieldsProvider.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5821)
Added a an empty Category Selector Provider with name and option as parameters and nothing else. 
App will show this when: there is a catCombo with no categories or a category with no options, and will not allow user to create the event

fix: [ANDROAPP-5821] Add no options available category selector

---

app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
app/src/main/java/org/dhis2/usescases/main/program/ProgramUi.kt
app/src/main/java/org/dhis2/usescases/main/program/ProgramView.kt
app/src/main/res/layout/fragment_program.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt

feat: [ANDROAPP-5523] change error access message at home

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.kt
app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/datasetList/DataSetListFragment.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.kt
app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialogProvider.kt
app/src/main/res/values/strings.xml
commons/src/main/java/org/dhis2/commons/sync/OnNoConnectionListener.kt
commons/src/main/java/org/dhis2/commons/sync/SyncComponentProvider.kt
commons/src/main/java/org/dhis2/commons/sync/SyncDialog.kt

fix: [ANDROAPP-5658] Shows snackbar when user does not have connection when trying to sync

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
commons/src/main/java/org/dhis2/commons/data/SearchTeiModel.java

[ANDROAPP-5043] Improve app navigation in search

---

commons/src/main/java/org/dhis2/commons/bindings/Permissions.kt
commons/src/main/java/org/dhis2/commons/data/FileHandler.kt
commons/src/main/java/org/dhis2/commons/dialogs/imagedetail/ImageDetailActivity.kt
commons/src/main/res/values/strings.xml
form/src/main/java/org/dhis2/form/ui/FormView.kt
form/src/main/java/org/dhis2/form/ui/dialog/QRDetailBottomDialog.kt

[ANDROAPP-5857] image download implementation

---

app/src/androidTest/java/org/dhis2/usescases/UseCaseTestsSuite.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/dialogs/scheduling/SchedulingDialogUiTest.kt
app/src/main/java/org/dhis2/data/user/UserComponent.java
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCatCombo.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/InputFieldsProvider.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingComponent.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialog.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialogUi.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingModule.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModelFactory.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt

feat: [ANDROAPP-5802] schedule events after completion

---

app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
app/src/main/res/layout/development_activity.xml
commons/src/main/java/org/dhis2/commons/bindings/ValueExtensions.kt
form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/MultiSelectionInputProvider.kt

[ANDROAPP-1540] Multi selection for option set in programs

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.kt
app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt

fix: [ANDROAPP-5976] crash after discard or delete event

---

app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
form/src/main/java/org/dhis2/form/ui/Form.kt

fix: [ANDROAPP-6040] Remove scroll to first empty item functionality

---

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/usecase/CreateEventUseCase.kt
app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionInjector.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.kt
app/src/test/java/org/dhis2/usescases/programEventDetail/usecase/CreateEventUseCaseTest.kt

When a new event is created set today as event date

[ANDROAPP-6986] Set current day when creating event

---

app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardViewModel.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardViewModelTest.kt

[ANDROAPP-6047] Catch sql exception

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt

This PR fixes the issue where program stages are not shown in the TeiDahsboardMobileActivity

Show Program stages in the TeiDashboadMobileActivity

---

.github/workflows/deploy-release.yml
app/src/dhisPlayServices/java/org/dhis2/utils/granularsync/GranularSyncModule.kt
gradle/libs.versions.toml

ci: [ANDROAPP-6167] deploy release job

---

app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt

…pens
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6057)

Improve scrolling to prevent overlap with save button

---

form/src/main/java/org/dhis2/form/ui/Form.kt

… for event category combo, refactor for cognitive complexity

fix: [ANDROAPP-6137] Category-Combo-section-shows-incorrect-number-of-fields

---

app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardProgramModel.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenterTest.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/ui/mapper/InfoBarMapperTest.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/ui/mapper/TEIDetailMapperTest.kt

fix: [ANDROAPP-6185] dashboard event list not updated

---

app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/dhis2/usescases/login/LoginViewModelTest.kt

fix: [ANDROAPP-6051] Show import successfully message when importing database

---

app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/domain/ConfigureEventCompletionDialog.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/provider/EventCaptureResourcesProvider.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/domain/ConfigureEventCompletionDialogTest.kt
form/src/main/res/values/strings.xml

feat: [ANDROAPP-6101] modify logic for saving completed events 

---

app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowTest.kt
app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt
app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt

test: [ANDROAPP-5987] shouldSuccessfullyFilterByEventStatusOverdue

---

app/src/main/java/org/dhis2/utils/customviews/BreakTheGlassBottomDialog.kt

BreakTheGlassBottomDialog was thoring an exception when trying to use resourceManager which was injected.
Given that this dialog does not have a module, the solution has been to manually instantiate the property.

fix: [ANDROAPP-6210] UninitializedPropertyAccessException on BreakingTheGlassDialog

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialog.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialogUi.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingModule.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModelFactory.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModelTest.kt

fix: [ANDROAPP-6182] crash when rotating scheduling dialog

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/domain/ConfigureEventCompletionDialog.kt
compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt

fix: [ANDROAPP-6101] Do not allow to save form with errors in completed events

---

app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/datasetList/DataSetListViewModel.kt
app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/datasetList/DataSetListViewModelFactory.kt
app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/datasetlist/DataSetListViewModelTest.kt

fix: [ANDROAPP-6273] Moves dataset groups calls to background thread

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt

fix: [ANDROAPP-5869] duplicated indicators table

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
commons/src/main/java/org/dhis2/commons/date/DateUtils.java

fix: [ANDROAPP-6093] crash when overriding cat combo in data sets

---

app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/FieldViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/FieldViewModelFactory.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/FieldViewModelFactoryImpl.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/file/FileViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerViewModel.java
app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/unsupported/UnsupportedViewModel.java
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
app/src/test/java/org/dhis2/usescases/datasets/MapFieldValueToUserTest.kt
app/src/test/java/org/dhis2/usescases/datasets/TableDataToTableModelMapperTest.kt
commons/src/main/java/org/dhis2/commons/date/DateUtils.java
compose-table/src/main/java/org/dhis2/composetable/model/DropdownOption.kt
compose-table/src/main/java/org/dhis2/composetable/model/TableRowModel.kt
compose-table/src/main/java/org/dhis2/composetable/ui/DropDownOptions.kt
compose-table/src/main/java/org/dhis2/composetable/ui/ItemValues.kt
compose-table/src/main/java/org/dhis2/composetable/ui/MultiOptionSelector.kt
compose-table/src/main/java/org/dhis2/composetable/ui/TableCell.kt

fix: {ANDROAPP-5953} Correctly shows options value when code or name include special characters

---

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/SyncFlowRobot.kt
compose-table/src/main/java/org/dhis2/composetable/ui/TableCell.kt
compose-table/src/main/java/org/dhis2/composetable/ui/extensions/StringExtensions.kt
compose-table/src/test/java/org/dhis2/extensions/StringExtensionsTest.kt

fix: [ANDROAPP-6121] Align numeric values to the left in all tables

---

app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.kt

fix: [ANDROAPP-6332] Navigates directly to form when user only have access to one org unit when creating an event

---

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt

fix: [ANDROAPP-6345] Keyboard type is displayed correctly on the stock-usecase module

---

app/src/main/java/org/dhis2/bindings/StringExtensions.kt
commons/src/main/java/org/dhis2/commons/date/DateUtils.java

fix: [ANDROAPP-6379] Adds no zulu date format expression for notes stored date

---

dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RuleEngineExtensions.kt

Show translation of ProgramRuleAction, like Warnings and Errors non-functional, on the  Android app.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6341)

chore: [ANDROAPP-6341] Use displayContent with fallback to content in rule actions

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java

A performance issue within the `SearchTEActivity`:
* When opening a Program with a large numbers (hundreds) on Tracked Entity Instances (TEIs) in an instance with a large number of Organization Units, the list of TEIs takes a long time (up to tens of seconds) to load.
* After adding a new TEI and navigating back to the list, the changes take similarly long time to appear in the list.
The underlying cause: in `SearchRepositoryImpl`, while a TEI is loaded, visibility of its Org Unit is computed non-optimally: Org Units are retrieved from the `d2` data layer and then counted, but can be counted in `d2` directly and then the number retrieved instead.
The affected code was intruduced as part of the [ANDROAPP-5724](https://dhis2.atlassian.net/browse/ANDROAPP-5724) UX improvement feature, the …

fix: Fix for slow counting of org units for search results.

---

app/src/main/java/org/dhis2/data/service/SyncPresenter.java
app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
app/src/main/java/org/dhis2/data/service/SyncRepository.kt
app/src/main/java/org/dhis2/data/service/SyncRepositoryImpl.kt
app/src/test/java/org/dhis2/data/services/SyncPresenterTest.kt

File resources could only be downloaded when syncing from the home page, that lead to issues when trying to sync entities; the file resources were not being downloaded but the entity remained as unsynced.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6361
Added granular sync for file resources when syncing programs (w/ and w/o enrollment ), events and teis.

fix: [ANDROAPP-6361] add file resource download to granular sync

---

app/build.gradle.kts
app/src/androidTest/java/org/dhis2/usescases/teidashboard/dialogs/scheduling/SchedulingDialogUiTest.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialog.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialogUi.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModelTest.kt

Since we were setting the variable for an instance, it's not getting restored after config change. Instead we are passing the data as a argument bundle, so that it can get restored after config change or process death.
We are using Gson to stringify the `LaunchMode` object and then convert it back to type when accessing the launch mode variable in `SchedulingDialog`. This is not a perfect solution, but given `Enrollnment` and `ProgramStage` or not `Parcelable` or `Serializable`, we cannot use Kotlin Parcelize or Serialization.
[jira issue](https://dhis2.atlassian.net/jira/software/c/projects/ANDROAPP/boards/113?selectedIssue=ANDROAPP-6511)

fix: [ANDROAPP-6511] App crashing during config change in scheduling dialog

---

dhis2_android_maps/src/main/java/org/dhis2/maps/extensions/FeatureExtensions.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/layer/types/PlacesMapLayer.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/usecases/MapStyleConfiguration.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/utils/GetMapData.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/utils/MapListeners.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt
dhis2_android_maps/src/main/res/drawable/ic_map_pin_selected_no_shadow.xml
dhis2_android_maps/src/main/res/drawable/ic_map_pin_shadow.xml
dhis2_android_maps/src/main/res/values/strings.xml
dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapSelectorViewModelTest.kt

[ANDROAPP-6329] Coordinates drag and drop capture

---

ui-components/src/main/java/org/dhis2/ui/MetadataIcon.kt

fix: [ANDROAPP-6513] Return default color if parsing fails

---

dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RuleEngineExtensions.kt
dhis2-mobile-program-rules/src/test/java/org/dhis2/mobileProgramRules/RuleEngineExtensionsTest.kt

fix: [ANDROAPP-6505] Handles program rules with calculated values

---

dhis2_android_maps/src/main/java/org/dhis2/maps/managers/MapManager.kt

fix: [ANDROAPP-6567] LocationComponent crash if accessed before activation

---

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/BackdropManager.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/SearchScreenConfigurator.kt
app/src/main/res/layout/activity_search.xml
app/src/main/res/layout/fragment_compose_holder.xml

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6580)

Fix navigation bar animation

---

app/src/main/java/org/dhis2/data/dhislogic/EnrollmentEventGenerator.kt
app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
form/src/main/java/org/dhis2/form/data/EventRepository.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/PeriodSelectorProvider.kt
form/src/main/res/values/strings.xml
gradle/libs.versions.toml
tracker/src/main/kotlin/org/dhis2/tracker/events/CreateEventUseCaseRepository.kt

This pull request includes several changes to the `EnrollmentEventGenerator`, `EnrollmentActivity`, `EnrollmentPresenterImpl`, `EventRepository`, `PeriodSelectorProvider`, and other related files. The main goal of these changes is to improve date handling and ensure that event dates are not set in the future. Additionally, a new string resource was added, and the version name was updated.
Improvements to date handling:
* [`app/src/main/java/org/dhis2/data/dhislogic/EnrollmentEventGenerator.kt`](diffhunk://#diff-76f4dad9e89337f7fe553e250e9210af2404529dfc701468a1f7711a1fa10da7L124-R129): Modified the event date generation logic to ensure that the event date is not set in the future.
* [`app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt`](diffhunk://#diff-9c4f4422db15e6fa …

fix: [ANDROAPP-64659] Implement no periods available functionality

---

.github/workflows/release-generate-notes.yml
.github/workflows/release-start.yml

This PR uses the [DHIS2-bot](https://github.com/dhis2-bot) to create the commit via GH API. In this way, Github automatically signed the commits. 
If makes use of a plugin called [gh-commit](https://github.com/flex-development/gh-commit), which wraps the communication with the GH API via GraphQL API. 
There is a limitation with protected branches: it seems that is not possible to push to protected branches via GraphQL (or GH API) even if the user is included in the Bypass list. As a workaround, the action creates an auxiliary branch to create the commit via API (so the commit is signed) and then it creates the `release/...` branch from this auxiliary branch. And deletes the auxiliary branch. This workaround could be avoided if we manage to push commits to protected branches via GH API. …

Use GH API to push commits in gihtub actions

---

Jenkinsfile

Every night long live branches runs the ci, exclude opened pull requests

ci: Exclude pull requests from con job

---

app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt
app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
app/src/main/java/org/dhis2/usescases/main/MainNavigator.kt

This pull request includes several changes to improve the navigation and testing functionality in the `MainActivity` and related classes. The most important changes include adding a dispatcher provider to `MainNavigator`, refactoring the initialization of `MainNavigator` in `MainActivity`, and enhancing the `MainRobot` and `MainTest` classes for better test reliability.
* [`app/src/main/java/org/dhis2/usescases/main/MainNavigator.kt`](diffhunk://#diff-adf15bf70d6b471a31f04a831e3074485656130a3ee59d37039d0cc36179e534R24): Added a dispatcher provider to `MainNavigator` and refactored the transaction handling to use coroutines for better performance and readability. [[1]](diffhunk://#diff-adf15bf70d6b471a31f04a831e3074485656130a3ee59d37039d0cc36179e534R24) …

fix: [ANDROAPP-6477] surround lateral menu navigation with async call

---

app/src/androidTest/java/org/dhis2/usescases/programevent/robot/ProgramEventsRobot.kt
app/src/main/java/org/dhis2/model/SnackbarMessage.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailScreen.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt
app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
app/src/main/java/org/dhis2/utils/HelpManager.java
app/src/main/res/layout/activity_program_event_detail.xml
commons/src/main/java/org/dhis2/commons/filters/FilterManager.java

fix: [ANDROAPP-6652] null pointer exception attempt to invoke virtual method sentry

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/InputFieldsProvider.kt

fix: [ANDROAPP-6628] input date on schedule dialog

---

app/src/main/java/org/dhis2/bindings/Extensions.kt
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryTest.kt
app/src/test/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapperTest.kt

fix: [ANDROAPP-6480] Tei list card shows overdue label when events are one or more days overdue

---

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
form/src/main/java/org/dhis2/form/data/metadata/FormBaseConfiguration.kt
form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt

fix: [ANDROAPP-6653] options not hiding/showing with program rules

---

app/src/main/java/org/dhis2/utils/customviews/MoreMenuView.kt

fix: [ANDROAPP-6579] set dropdownmenu max width to 70% of screen size

---

app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt
app/src/main/java/org/dhis2/usescases/tracker/TrackedEntityInstanceInfoProvider.kt
dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapScreen.kt
dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/idling/AnalyticsCountingIdlingResource.kt
dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsFragment.kt
dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsViewModel.kt

fix: [ANDROAPP-6457] limit max height of expanded cards in maps

---

app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt
form/src/main/java/org/dhis2/form/ui/provider/FormResultDialogProvider.kt
form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
form/src/test/java/org/dhis2/form/data/RulesUtilsProviderImplTest.kt
form/src/test/java/org/dhis2/form/ui/provider/FormResultDialogProviderTest.kt
ui-components/src/main/java/org/dhis2/ui/dialogs/bottomsheet/BottomSheetDialogContent.kt

fix: [ANDROAPP-6667] Add field to warning list for warning on complete program rule

---

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/models/EventDate.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/models/EventInputDateUiModel.kt
app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/InputFieldsProvider.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialogUi.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt

fix: [ANDROAPP-6628] do not allow schedule when date has error

---

compose-table/src/main/java/org/dhis2/composetable/model/TextInputModel.kt
compose-table/src/main/java/org/dhis2/composetable/ui/TextInput.kt
stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/HomeScreen.kt
stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt

fix: [ANDROAPP-5888] Disallow leading zero input from keyBoard

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt

fix: [ANDROAPP-6509] Use enrolment org unit when creating a new event from TEI detail

---

dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt

fix: [ANDROAPP-6657] add loading in "search on this area" button

---

aggregates/build.gradle.kts
aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/Platform.android.kt
aggregates/src/androidUnitTest/kotlin/org/dhis2/mobile/aggregates/AndroidGreetingTest.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/Greeting.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/Platform.kt
aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/CommonGreetingTest.kt
aggregates/src/iosMain/kotlin/org/dhis2/mobile/aggregates/Platform.ios.kt
aggregates/src/iosTest/kotlin/org/dhis2/mobile/aggregates/IosGreetingTest.kt
app/build.gradle.kts
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.kt
settings.gradle.kts
stock-usecase/build.gradle.kts

build: add aggregate module

---

app/src/main/java/org/dhis2/usescases/general/SessionManagerActivity.kt
commons/src/main/java/org/dhis2/commons/ui/extensions/EdgeToEdgeExtension.kt
stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt

Add window inset for edgeToEdge handling in Android 15
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6763)

fix: [ANDROAPP-6373] fix screen inset in Android 15

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/dhis2/usescases/searchTrackEntity/searchparameters/provider/ParameterSelectorItemProvider.kt
commons/src/main/java/org/dhis2/commons/bindings/FileExtensions.kt
form/src/main/java/org/dhis2/form/model/UiEventType.kt
form/src/main/java/org/dhis2/form/ui/Form.kt
form/src/main/java/org/dhis2/form/ui/FormView.kt
form/src/main/java/org/dhis2/form/ui/dialog/ImagePickerOptionsDialog.kt
form/src/main/java/org/dhis2/form/ui/event/RecyclerViewUiEvents.kt
form/src/main/java/org/dhis2/form/ui/event/UiEventFactoryImpl.kt
form/src/main/java/org/dhis2/form/ui/files/GetFileResource.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/ImageInputProvider.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputFileProvider.kt
form/src/main/res/values/strings.xml

fix: [ANDROAPP-6764] Review MEDIA permissions to comply with Google Play policy

---

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt

The logic for computing if a dataset is expired is currently implemented both in the SDK and in the app (in DataValueRepository). It should be straightforward to replace this logic implementation in the app by a call to the corresponding SDK service, thus avoiding  duplicated logic improving responsibilities.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6799

chore: [ANDROAPP-6799] use sdk service to compute expiration

---

app/build.gradle.kts
compose-table/build.gradle.kts
dhis2_android_maps/build.gradle.kts
dhis2_android_maps/src/main/java/org/dhis2/maps/model/NominatimLocation.kt
gradle/libs.versions.toml
stock-usecase/build.gradle.kts
ui-components/build.gradle.kts

The http client service deserialization tool has been updated from Jacskon to Kotlinx serialization and there is a class in the app that is using the public http client service that needs to be updated accordingly.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6840)

chore: [ANDROAPP-6840] use kotlinx serialization in NominatimLocation

---

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/QuickActionsMapper.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/ui/mapper/QuickActionsMapperTest.kt

fix: [ANDROAPP-6426] hide transfer quickAction when is not available

---

scripts/browserstackJenkins.sh
scripts/browserstackJenkinsCompose.sh
scripts/browserstackJenkinsForm.sh
scripts/browserstackJenkinsLandscape.sh
scripts/config_jenkins.init

This is a proof to know if enabling the singleRunner in Browserstack works and makes the CI faster.

chore: Enable browserstack single runner for Form and Compose tests

---

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.android.kt
aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/ui/UiActionHandlerImpl.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/UiActionHandler.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt
app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetInstanceActivity.kt

Inject UiActionHandler in DataSetInstanceScreen instead of passing the context
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6902)

fix: [ANDROAPP-6902] Inject UIActionHandler instead of passing the context as parameter

---

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt

This PR includes two fixes:
- Do not include 'default' categoryOptionCombo label ([ANDROAPP-6900](https://dhis2.atlassian.net/browse/ANDROAPP-6900))
- Add space between dataElement name and categoryOptionCombo label ([ANDROAPP-6908](https://dhis2.atlassian.net/browse/ANDROAPP-6908))
[ANDROAPP-6900]: https://dhis2.atlassian.net/browse/ANDROAPP-6900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANDROAPP-6908]: https://dhis2.atlassian.net/browse/ANDROAPP-6908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Do not show 'default' categoryOptionCombo label

---

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt
aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/mappers/SectionToDataSetSection.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetSection.kt
aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/NoteRobot.kt
form/src/main/java/org/dhis2/form/ui/FormViewModel.kt

Do not map category option combos with no categories attached
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6977

fix: [ANDROAPP-6977] Crash when loading dataset with empty category option combo

---

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt
aggregates/src/androidUnitTest/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImplTest.kt

the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-6962).

fix: [ANDROAPP-6962] Incorrect separator used in inputDialog for parent-child columns

---

app/src/main/java/org/dhis2/usescases/development/ConflictGenerator.kt
app/src/test/java/org/dhis2/data/filter/FilterRepositoryTest.kt
app/src/test/java/org/dhis2/usescases/about/AboutPresenterTest.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
app/src/test/java/org/dhis2/usescases/teiDashboard/TeiAttributesProviderTest.kt
stock-usecase/src/test/java/org/dhis2/android/rtsm/data/DataElementFactory.kt
stock-usecase/src/test/java/org/dhis2/android/rtsm/data/DestinationFactory.kt
stock-usecase/src/test/java/org/dhis2/android/rtsm/data/FacilityFactory.kt
stock-usecase/src/test/java/org/dhis2/android/rtsm/data/GroupAnalyticsFactory.kt

Remove uses of CoreObject _id  coming from SDK database objects
the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7156).
In the context of upgrading the database to a KMP solution, the explicit index columns “_id” have been removed from the SDK. There are three usages of this column in the App that need to be addressed right after the corresponding PR from the SDK has been merged to avoid blocking the App ci pipelines.

chore: [ANDROAPP-7156] replace use of _id with Primary Keys

---

commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/model/CustomIntentModel.kt
form/src/main/java/org/dhis2/form/data/DataEntryBaseRepository.kt
form/src/main/java/org/dhis2/form/data/EnrollmentRepository.kt
form/src/main/java/org/dhis2/form/data/EventRepository.kt
form/src/main/java/org/dhis2/form/data/metadata/FormBaseConfiguration.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/CustomIntentProvider.kt

This is a draft PR for [ANDROAPP-7164](https://dhis2.atlassian.net/browse/ANDROAPP-7164) just to discuss about the proposed solution. This PR shouldn't be merged as it is.
It uses the DHIS2 Android SDK to evaluate the custom intent request parameters. The purpose of this evaluation is to be able to use variables and different value types in the parameters.
The parameters are evaluated when the form is built, which means that they are not re-evaluated when the form is been filled in. This might be a problem for certain variables: for example, if we add the variable `V{org_unit_id}` and the orgunit changes after the form is built, the parameter will still have the value from the previous orgunit. 
Ideally, this evaluation should be done right before launching the intent. Do you think it …

feat: [ANDROAPP-7164] Evaluate custom intent request parameters

---

.github/dependabot.yml

Ignore DHIS2 Android SDK and DHIS2 Mobile Design system updates, these will be handled manually by us.

fix(dependabot): add additional dependencies to ignore list

---

.github/dependabot.yml

ignore "*-*" versions updates.
These version should denote build metadata. For stability, it is generally recommended to use the official release version without the build metadata

fix: add wildcard ignore "-" for all dependencies in dependabot.yml

---

commons/src/main/java/org/dhis2/commons/ui/ListCardProvider.kt

Link the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7202).
Remove scrollable content to avoid crash when expanding card

fix: [ANDROAPP-7202] remove scrollableContent from ListCardProvider

---

.github/dependabot.yml

This PR enhances the Dependabot configuration to prevent updates to development versions that contain '+dev' suffixes (e.g., 2.9.4 to 2.10.0+dev2995).
- ✅ Add comprehensive version patterns to ignore dev versions (`*+dev*`, `*-dev*`, `*dev*`, `*+*`)
- ✅ Add pre-release version filtering using `update-types: ["version-update:semver-prerelease"]`
- ✅ Specifically target JetBrains Compose dependencies that frequently use dev versions
- ✅ Maintain existing ignore rules for OkHttp and DHIS2 dependencies
Prevents Dependabot from suggesting updates like:
- `org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose` from `2.9.4` to `2.10.0+dev2995`
- `org.jetbrains.compose.material3:material3-window-size-class` from `1.8.2` to `1.10.0+dev2995`
- `org.jetbrains.compose` from `1.9.0` to …

feat: improve dependabot config to ignore development versions

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryTest.kt

Link the [JIRA issue](https://dhis2.atlassian.net/jira/software/c/projects/ANDROAPP/boards/113?selectedIssue=ANDROAPP-7177).
Remove SDK call that sets overdue scheduled events status to overdue, fixing the incorrect pending sync status displayed in tei list after entering and exiting a TEI.
Check for overdue scheduled events in TEI list to properly display TEIs with overdue events.
Update current Unit tests and add one for new functionality.

fix: [ANDROAPP-7177] Display overdue events in TEI list correctly

---

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryTest.kt
commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/customintents/CustomIntentRepositoryImpl.kt
commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/customintents/CustomIntentRepository.kt
form/src/main/java/org/dhis2/form/ui/provider/inputfield/CustomIntentProvider.kt

[JIRA issue](https://dhis2.atlassian.net/jira/software/c/projects/ANDROAPP/boards/113?selectedIssue=ANDROAPP-7234).
With the new custom intent implementation in the Search TEI section, we could not search teiAttributes with a value with a comma in it, in order to adapt this, a new method has been added to the custom intent repository that checks whether that TEI attribute is linked to a custom intent that can return a list of values and then will search by it, if not, it will search with the plain text that was introduced in the search field

fix [ANDROAPP-7234] Allow to search using comma
