dhis2/dhis2-android-capture-app

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
> fix: Scanview multiple binding

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/IndicatorsRobot.kt
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/data/analytics/AnalyticsModel.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsModule.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
- app/src/main/res/drawable/ic_compass.xml
- app/src/main/res/drawable/ic_layers.xml
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/item_section_tittle.xml
- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3544)
> feat: [ANDROAPP-3544] Add feedback and indicator widgets for ruleActions

- app/src/main/java/org/dhis2/animations/ViewAnimations.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3601)
> fix: [ANDROAPP-3601] display attributes when open card on program events

- app/src/androidTest/java/org/dhis2/common/BaseRobot.kt
- buildsystem/dependencies.gradle
> fix: update target version

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderFragment.java
- app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
- app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
- app/src/main/res/values/strings.xml
[ANDROAPP-3623](https://jira.dhis2.org/browse/ANDROAPP-3623)
> fix: [ANDROAPP-3623] Correctly handles camera permission when not granted.

- scripts/browserstackBitrise.sh
- scripts/config.init
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3377)
> feat: [ANDROAPP-3377] Add test sharding 2 paralell devices

- app/src/main/java/org/dhis2/Bindings/Bindings.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3598)
> fix: [ANDROAPP-3598] Fix double focus in text fields

- app/src/main/java/org/dhis2/data/forms/dataentry/StoreResult.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/RowAction.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/main/java/org/dhis2/utils/ValidationUtils.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
> fix: Crash with Int fields and flickering

- app/build.gradle
- app/src/debug/AndroidManifest.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/App.java
- app/src/main/java/org/dhis2/data/appinspector/AppInspector.kt
- app/src/main/java/org/dhis2/data/server/ServerModule.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3494)
> feat: [ANDROAPP-3494] Migrate Stetho to Flipper

- app/src/main/res/layout/item_event.xml
[ANDROAPP-3562](https://jira.dhis2.org/browse/ANDROAPP-3562)
> feat: [ANDROAPP-3562] Add item separator line to events

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/BaseIndicatorRepository.kt
- app/src/main/java/org/dhis2/utils/RulesActionCallbacks.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
This PR updates the rule engine branch used by our develop branch. This will block opening a PR for ANDROAPP-3541 as well.
> feat: Update rule engine

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModel.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/res/layout/item_dataset.xml
- app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3563)
> feat: [ANDROAPP-3563] dataset cards design

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/data/sorting/SearchSortingValueSetter.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/RelationshipLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/res/layout/item_carousel_tei.xml
- app/src/main/res/layout/item_search_tracked_entity.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/data/sorting/SearchSortingValueSetterTest.kt
[ANDROAPP-3039](https://jira.dhis2.org/browse/ANDROAPP-3039)
> feat: [ANDROAPP-3039] Enrolled org. unit is shown in tei cards

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
- app/src/test/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepositoryTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3643)
> fix: [ANDROAPP-3643] Crash when selecting all programs in dashboard

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3642)
> fix: [ANDROAPP-3642] keyboard not closing after saving value

- app/src/main/res/layout/form_check_button.xml
- app/src/main/res/layout/form_radio_button_horizontal.xml
- app/src/main/res/layout/form_toggle.xml
> fix: [ANDROAPP-3652] set enable/disable for radioButton, checkButton and yesToggle via XML

- app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3645)
> fix: [ANDROAPP-3645] Navigation bottom bar selected circle missbehaviour

- app/src/main/res/layout/item_carousel_tei.xml
- app/src/main/res/layout/item_search_tracked_entity.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3550)
> fix: [ANDROAPP-3550] overlap TEI attribute label

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/VisualOptionSetView.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3578)
> fix: [ANDROAPP-3578] Visual option set warning message

- .tx/config
- app/src/main/java/org/dhis2/data/filter/EventProgramFilterSearchHelper.kt
- app/src/main/java/org/dhis2/data/filter/FilterPresenter.kt
- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
- app/src/main/java/org/dhis2/data/filter/TeiWorkingListScope.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/test/java/org/dhis2/data/filter/EventProgramFilterSearchHelperTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3625)
> feat: [ANDROAPP-3625] Add workinglist in events

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-1161)
> feat: [ANDROAPP-1161] separate indicators by section

- app/src/main/java/org/dhis2/Bindings/Bindings.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
> fix: [ANDROAPP-3646] Keyboad not showing for edit texts

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/file/FileViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/unsupported/UnsupportedViewModel.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3664)
> fix: [Androapp-3664] PictureView Nullpointer Exception

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3655)
> feat: [ANDROAPP-3655] Block swipe in tei dashboard

- app/src/main/java/org/dhis2/Bindings/DateExtensions.kt
- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3585)
> fix: [ANDROAPP-3585] Fix Date test

- app/src/main/java/org/dhis2/data/dhislogic/DhisEnrollmentUtils.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
**Note**: A new quality ticket has been opened in order to refactor/clean the enrollmentRepository class so that unit tests can be done easily
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3665)
> fix: [ANDROAPP-3665] filter null attributes in enrollment form

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3579)
> feat: [ANDROAPP-3579] hide ans show bottom nav in events form

- app/src/main/java/org/dhis2/animations/CarouselViewAnimations.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3467)
> fix: [ANDROAPP-3467] Navigation button visibility

- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3563)
> fix: [ANDROAPP-3563] capitalize dataset period

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
[ANDROAPP-3582](https://jira.dhis2.org/browse/ANDROAPP-3582)
> fix: [ANDROAPP-3582] Validations error view reacts to keyboard visibility.

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeView.java
- app/src/main/res/layout/age_custom_view.xml
- app/src/main/res/layout/age_custom_view_accent.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2578)
> feat: [ANDROAPP-2578] display error/warning message on whole field

- app/src/main/res/layout/item_event.xml
[ANDROAPP-3562](https://jira.dhis2.org/browse/ANDROAPP-3562)
> fix: [ANDROAPP-3562] Event card height to fix item divider on tei dashboard.

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3648)
> fix: [ANDROAPP-3648] Map layers button showing on list view mode

- app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
- app/src/main/res/layout/activity_event_capture.xml
- app/src/main/res/menu/event_menu.xml
- app/src/main/res/menu/navigation_event_menu.xml
- app/src/main/res/values/attrs.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3717)
> fix: [ANDROAPP-3717] Review navigation to details section

- app/src/main/res/layout/filter_org_unit.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3675)
> fix: [ANDROAPP-3675] keyboard displayed on home

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinatesView.java
- app/src/main/java/org/dhis2/uicomponents/map/extensions/MapExtensions.kt
- app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/PolygonViewModel.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/MapSelectorActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3677)
> fix: [ANDROAPP-3677] Fix crash on MapSelectorActivity initialization

- app/src/main/res/layout/item_search_tracked_entity.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3661)
> fix: [ANDROAPP-3661] Text overlap in tei search activity

- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
> fix: [ANDROAPP-3690] Separates carousel initialization from activity

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3723)
> fix: [ANDROAPP-3723] crash scrolling carousel

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
> fix: [ANDROAPP-3701] Clear assign to me filter when going back to home screen

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailComponent.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragmentView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListInjector.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListPresenter.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragmentView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapInjector.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapPresenter.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/fragment_program_event_detail_list.xml
- app/src/main/res/layout/fragment_program_event_detail_map.xml
- app/src/main/res/menu/event_list_menu.xml
- app/src/main/res/menu/navigation_event_list.xml
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3718)
> fix: [ANDROAPP-3718] Add navigation bar to ProgramEventDetailActivity

- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/main/java/org/dhis2/utils/filters/dates/FilterPeriodView.kt
> fix: [ANDROAPP-3741] Fix Crash with enrollment date when going to home screen

- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
> fix: [ANDROAPP-3715] Filtering Dates

- app/src/androidTest/java/org/dhis2/common/db/TestingDatabase.kt
- scripts/updateTestingDB.py
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3441)
> feat: [ANDROAPP-3441] Update testing database

- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
- app/src/main/res/layout/item_dataset.xml
> fix: [ANDROAPP-3705] dataset orgunit visibility

- tableview/src/main/res/layout/item_table_cell.xml
- tableview/src/main/res/layout/item_table_header.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3653)
- [ X] My code follows the style guidelines of this project
> fix: [Androapp-3653] Analytics table width changes

- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3746)
> fix: [ANDROAPP-3746] share event values through QR

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
> fix: [ANDROAPP-3747] When image is clicked fields become editable

- app/src/main/java/org/dhis2/Bindings/Bindings.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3711)
> fix: [ANDROAPP-3711] Allow re select selected item in Spinner

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout/activity_search.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3663])
> fix: [ANDROAPP-3663] don't hide filterOpen layout

- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3703)
> fix: [ANDROAPP-3703] Avoid CarouselView crash

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3742)
> fix: [ANDROAPP-3742] Add access control to dashboard catCombo dialog

- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3749)
> fix: [ANDROAPP-3749] Fixed unique value warning

- app/src/main/res/layout/fragment_dataset_section.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3727)
> fix: [ANDROAPP-3727] padding in tableview

- app/src/main/res/values/styles.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3596)
> fix: [ANDROAPP-3596] change dialog button text color

- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapPresenter.kt
- app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3720)
> fix: [ANDROAPP-3720] Map legend applied wrong

- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/utils/filters/DisableHomeFiltersFromSettingsApp.kt
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
> fix: [ANDROAPP-3479] Remove filters when going back to home based on WebApp Config

- scripts/reviewers.py
> feat: make reviewers script choose the devs at random

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3700)
> fix: [ANDROAPP-3700] Reset filters when deactivating working list

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
[ANDROAPP-3721](https://jira.dhis2.org/browse/ANDROAPP-3721)
> fix: [ANDROAPP-3721] deleting selected option on OptionSet produced flickering

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
- app/src/main/res/layout/dialog_age.xml
- app/src/main/res/values/strings.xml
[ANDROAPP-3744](https://jira.dhis2.org/browse/ANDROAPP-3744)
> fix: [ANDROAPP-3744] Prevents crash on Integer (pos, neg,etc) and Age valueType fields in Datasets

- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3746)
> fix: [ANDROAPP-3746] incident date label

- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
- app/src/main/res/layout/fragment_program_event_detail_list.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3648)
>  fix: [ANDROAPP-3648] Crash and empty list visibility

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsController.kt
- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
- app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
- app/src/test/java/org/dhis2/data/services/SyncPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3764)
> feat: [ANDROAPP-3764] Consume matomo configuration from settings

- app/src/main/java/org/dhis2/utils/category/CategoryDialogPresenter.kt
- app/src/main/java/org/dhis2/utils/category/CategoyOptionComboSource.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3742)
> fix  [ANDROAPP-3742] Category sharing settings for autogenerated events

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3708)
> fix: [ANDROAPP-3708] Avoid hiding data set text fields

- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3722)
> fix: [ANDROAPP-3722] add sync error message for events with server problem

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeView.java
- app/src/main/java/org/dhis2/utils/customviews/CatOptionPopUp.kt
- app/src/main/java/org/dhis2/utils/customviews/CategoryOptionPopUp.java
- app/src/main/res/layout/filter_cat_opt_comb.xml
[ANDROAPP-3712](https://jira.dhis2.org/browse/ANDROAPP-3712)
> fix: [ANDROAPP-3712] Removes category combo name from list

- app/src/main/java/org/dhis2/usescases/sync/SyncActivity.kt
- app/src/main/res/color-v19/login_text_color_selector.xml
- app/src/main/res/values-v19/styles.xml
> fix: kitkat login crash

- app/build.gradle
- app/src/main/AndroidManifest.xml
- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3631)
> [Androapp 3631] Sentry setup

- app/build.gradle
- app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
- app/src/main/java/org/dhis2/data/forms/EventRepository.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryModule.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionModule.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryTest.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3768)
> feat: [ANDROAPP-3768] Update rule engine

- app/src/test/java/org/dhis2/data/filter/TrackerFilterSearchHelperTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3773)
> fix: [ANDROAPP-3773] Update SDK to fix TEI download

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3713)
> fix: [ANDROAPP-3713] finish activity when clicking save button

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3775)
> fix: [ANDROAPP-3775] Unique attribute search

- app/src/main/java/org/dhis2/Bindings/Bindings.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3642)
> [ANDROAPP-3642] show keyboard for versions under API 23

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
[ANDROAPP-3744](https://jira.dhis2.org/browse/ANDROAPP-3744)
> fix: [ANDROAPP-3744] Adds integer validation to Integer type fields

- app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/IndicatorsRobot.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/RelationshipLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
> fix: [ANDROAPP-3649] Clear list when chaning program

- RELEASE.md
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/test/java/org/dhis2/data/filter/TrackerFilterSearchHelperTest.kt
- buildsystem/dependencies.gradle
- release.info
- whatsnew/whatsnew-en-US
> feat: Release v2.3.2

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
> fix: [ANDROAPP-3479] Update filters when coming back to home

- app/src/main/java/org/dhis2/data/server/OpenIdSession.kt
- app/src/main/java/org/dhis2/data/server/ServerComponent.java
- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/utils/Constants.java
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3310)
> feat: [ANDROAPP-3310] Handle openId logout

- RELEASE.md
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- buildsystem/dependencies.gradle
- docs/src/commonmark/en/content/capture-app/contribute-to-the-app.md
- release.info
- whatsnew/whatsnew-en-US
> feat: Update with 2.3.2

- app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3746)
> fix: [ANDROAPP-3746] share geometry through QR

- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3700)
> fix: [ANDROAPP-3700] Clear sync state, org unit and cat combo filters when applying working list

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/AnalyticTeiSettingsToSettingsAnalyticsModel.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToValue.kt
> fix: [ANDROAPP-3783] crash on analytics because empty indicators

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
> fix: [ANDROAPP-3793] crash when searching on map

- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
- app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
> fix: add matomo userId and track during debug

- app/src/main/java/org/dhis2/utils/filters/FilterItem.kt
- app/src/main/res/drawable/ic_category_option_combo_filter.xml
[ANDROAPP-3788](https://jira.dhis2.org/browse/ANDROAPP-3788)
> fix: [ANDROAPP-3788] Changes CategoryoptionCombo filter icon

- app/src/main/java/org/dhis2/uicomponents/map/TeiMarkers.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3780)
> fix: [ANDROAPP-3780] Fix map marker image margins

- app/src/main/res/layout-land/activity_login.xml
- app/src/main/res/layout/activity_login.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3779)
> fix: [ANDROAPP-3779] Authenticating message rounded corners

- app/src/main/java/org/dhis2/uicomponents/map/ExternalMapNavigation.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselBinder.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselRelationshipHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/model/EventUiComponentModel.kt
- app/src/main/java/org/dhis2/uicomponents/map/model/RelationshipUiComponentModel.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventViewModel.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/res/layout/item_carousel_event.xml
- app/src/main/res/layout/item_carousel_program_event.xml
- app/src/main/res/layout/item_carousel_relationship.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3799)
> fix: [ANDROAPP-3799] Navigate to any carousel feature

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_event_scheduled.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/main/res/layout/activity_reserved_value.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/menu/event_list_menu.xml
- app/src/main/res/menu/search_menu.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3789)
> fix: [ANDROAPP-3789] remove three dots menu

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
[ANDROAPP-3796](https://jira.dhis2.org/browse/ANDROAPP-3796)
> fix: [ANDROAPP-3796] Use only tracked entity attribute display form name on search attributes

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldUiModel.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
- app/src/main/res/layout/scan_text_view.xml
> fix: [ANDROAPP-3807] ScanTextView on next

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3811)
> fix: [ANDROAPP-3811] Dataset date fields not synced

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinatesView.java
> fix: [ANDROAPP-3809] Disable highlight in polygon textInputLayout

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitView.java
[ANDROAPP-3810](https://jira.dhis2.org/browse/ANDROAPP-3810)
> fix: [ANDROAPP-3810] Org Unit focus handling

- app/src/main/assets/policy.html
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/res/values/strings.xml
> fix: [ANDROAPP-3785] privacy policy on alert dialog

- app/build.gradle
> fix: update testing dependencies and remove roboeletric

- app/src/androidTest/java/org/dhis2/common/viewactions/CommonViewActions.kt
- app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3815)
> test: [ANDROAPP-3815] add test for privacy policy on login

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
> fix: [ANDROAPP-3647] Check if there is access in the current program

- app/build.gradle
> fix: remove findbug dependency

- app/src/main/java/org/dhis2/widgets/DhisCustomLauncher.kt
> fix: crash in DhisCustomLauncher

- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
> fix: [ANDROAPP-3616] polygon selection

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetSelectionView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
[ANDROAPP-3796](https://jira.dhis2.org/browse/ANDROAPP-3796)
> fix: [ANDROAPP-3796] Removes mandatory label from search attributes

- app/src/main/java/org/dhis2/data/dhislogic/DhisEnrollmentUtils.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
> fix: [ANDROAPP-3777] Household ID is unique across org units

- app/src/main/res/layout/form_check_button.xml
- app/src/main/res/layout/form_radio_button_horizontal.xml
- app/src/main/res/layout/form_toggle.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3833)
> fix: [ANDROAPP-3833] show * in  mandatory radio buttons

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
- app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
- app/src/main/res/layout/development_activity.xml
- app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt
> fix: [ANDROAPP-3823] Parse rule action to unsupported if parameters are not valid

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/MatrixOptionSetModel.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3835)
> fix: [ANDROAPP-3835] Hide/Show option rules only working once

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java
> fix: [ANDROAPP-3821] date format to sync

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryInteractor.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3830)
> fix: [ANDROAPP-3830] Unify completion percentage calculation

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/file/FileViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
> fix: [ANDROAPP-3839] add editable to each field

- app/build.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3812)
> feat: [ANDROAPP-3812] exclude dhisUITesting from sentry report

- app/src/main/assets/paperwork.json
> fix: updates sdk

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3762)
> fix: [ANDROAPP-3762] Coordinates field for searching

- app/src/main/res/layout/custom_text_view.xml
- app/src/main/res/layout/form_spinner.xml
> fix: [ANDROAPP-3792] legend height

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
> fix: [ANDROAPP-3816] color of filter counts

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
> fix: [ANDROAPP-3841] Avoid toast duplication

- app/src/main/java/org/dhis2/utils/filters/FilterItem.kt
- app/src/main/java/org/dhis2/utils/filters/FilterManager.java
- app/src/main/res/layout/filter_state.xml
- app/src/test/java/org/dhis2/utils/filters/SyncStateFilterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3700)
> fix: [ANDROAPP-3700] fix clear sync state filter

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableData.kt
- app/src/main/java/org/dhis2/utils/validationrules/ValidationResultViolationFragment.kt
- app/src/main/java/org/dhis2/utils/validationrules/ValidationRuleResult.kt
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3317)
> fix: [ANDROAPP-3317] Hide default catcombo label

- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/main/res/layout/form_bottom_dialog.xml
[ANDROAPP-3845](https://jira.dhis2.org/browse/ANDROAPP-3845)
> test: [ANDROAPP-3845] Adds Warning on complete and Error on complete functional tests 

- app/src/main/java/org/dhis2/data/dhislogic/DhisPeriodUtils.kt
- app/src/main/java/org/dhis2/data/server/ServerComponent.java
- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewModel.kt
- app/src/main/java/org/dhis2/utils/DateUtils.java
- app/src/main/java/org/dhis2/utils/customviews/PeriodAdapter.kt
- app/src/main/java/org/dhis2/utils/customviews/PeriodDialog.java
- app/src/main/java/org/dhis2/utils/customviews/PeriodDialogInputPeriod.java
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/data/dhislogic/DhisPeriodUtilsTest.kt
- app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryTest.kt
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventMapperTest.kt
- app/src/test/java/org/dhis2/utils/DateUtilsTest.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3587)
> fix: [ANDROAPP-3587] Fix period span text generation

- app/src/test/java/org/dhis2/data/filter/FilterRepositoryTest.kt
> fix: [ANDROAPP-3851] Filter unit tests

- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
> test: [ANDROAPP-3847] display text/ keyvalue rules

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
- app/src/main/res/layout/activity_event_capture.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3850)
> fix: [ANDROAPP-3850] Block swipe navigation in event capture forms

- app/src/main/assets/paperwork.json
- app/src/main/res/layout/dialog_cascade_orgunit.xml
> fix: [ANDROAPP-3837] Do not open keyboard automatically when opening the orgUnit dialog in event and enrollment form

- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
[ANDROAPP-2937](https://jira.dhis2.org/browse/ANDROAPP-2937)
> test: [ANDROAPP-2937] Main presenter unit test

- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
[ANDROAPP-3848](https://jira.dhis2.org/browse/ANDROAPP-3848)
> test: [ANDROAPP-3848] Make Mandatory field program rule test added

- app/src/main/java/org/dhis2/data/dhislogic/Authorities.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFieldProvider.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2935)
> test: [ANDROAPP-2935] EventCaptureRepositoryImpl tests

- app/src/test/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImplTest.kt
- scripts/updateTestingDB.py
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3860)
> test: [ANDROAPP-3860] Test attribute name

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3777)
> fix: [ANDROAPP-3777] Unique check refactor

- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/login/LoginModule.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashModule.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt
- app/src/main/java/org/dhis2/utils/SentryOkHttpInterceptor.kt
- app/src/main/java/org/dhis2/utils/reporting/CrashReportController.kt
- app/src/main/java/org/dhis2/utils/reporting/CrashReportControllerImpl.kt
- app/src/main/java/org/dhis2/utils/reporting/SentryOkHttpInterceptor.kt
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
> [ANDROAPP-3853] Sentry performance integration

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapPresenter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3856)
> fix: [ANDROAPP-3856] Fix event map clicks for single events programs

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormView.kt
> fix: [ANDROAPP-3867] Clicking enrollment save button not saving value

- app/src/main/res/layout/view_form.xml
> fix: [ANDROAPP-3871] form padding bottom

- app/src/main/assets/policy.html
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
- app/src/main/res/values/strings.xml
> fix: [ANDROAPP-3838] User policy message should be improved

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetSelectionView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
- app/src/main/res/layout/form_toggle.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3870)
> [ANDROAPP-3870] Unable to clear selection in render type 'checkbox'

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
[ANDROAPP-3861](https://jira.dhis2.org/browse/ANDROAPP-3861)
> fix: [ANDROAPP-3861] Returning from dashboard to map and then to list, tei list is still present

- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3866
> fix: [ANDROAPP-3866] Loop message showing even if no field changed

- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
> test: [ANDROAPP-3849] add hide program stage rule

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
> fix: [ANDROAPP-3861] Loading list when coming back from maps

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryDiff.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
> fix: Add background thread to diff utils

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3874)
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3875)
> fix: [ANDROAPP-3874,ANDROAPP-3875] Fix section completion calculations with optionsets

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
> fix: freeze form

- app/src/main/java/org/dhis2/App.java
> feat: Release 2.4

- app/src/main/AndroidManifest.xml
> fix: upload image legacy store

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/MatrixOptionSetModel.kt
- buildsystem/dependencies.gradle
> fix: override equals

- app/src/androidTest/java/org/dhis2/common/viewactions/CommonViewActions.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/MatrixOptionSetModel.kt
> fix: form fields equals

- app/src/dhis/AndroidManifest.xml
- app/src/dhisNoSMS/AndroidManifest.xml
- buildsystem/dependencies.gradle
> fix: update manifest with SMS permission

- app/src/test/java/org/dhis2/usescases/settingsprogram/SettingsProgramPresenterTest.kt
[ANDROAPP-2953](https://jira.dhis2.org/browse/ANDROAPP-2953)
> test: [ANDROAPP-2953] Adds unit tests on the SettingsProgramPresenter

- app/src/main/java/org/dhis2/Bindings/MeasureExtensions.kt
- app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
- app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/NutritionTestingData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/RuleEngineNutritionDataProviderImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/renderers/NutritionRenderer.kt
**DO NOT REVIEW OR MERGE**
[ANDROAPP-3878](https://jira.dhis2.org/browse/ANDROAPP-3878)
> perf: [ANDROAPP-3878] Remove all extensions warnings

- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
> test: Open and edit dataset 

- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
- scripts/browserstackBitrise.sh
> fix: false positives in CI due to wrong check in build status

- app/build.gradle
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/App.java
- build.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3896)
> fix: [ANDROAPP-3896] Remove Kuyaku dependencies, restart mapbox

- app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
> fix: Map test

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
> fix: [ANDROAPP-3877] crash searching by org unit

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/assets/paperwork.json
> perf: [ANDROAPP-3899] Reduce transaction logs

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
> fix: [ANDROAPP-3910] display image on form when adding it

- app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/enrollment_activity.xml
- app/src/main/res/layout/section_selector_fragment.xml
- app/src/main/res/layout/view_form.xml
> refactor: [ANDROAPP-3753] use FormView on search

- app/src/main/res/layout/activity_main.xml
[ANDROAPP-3895](https://jira.dhis2.org/browse/ANDROAPP-3895)
> fix: [ANDROAPP-3895] Specify DrawerLayout constraints to its parent

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/reporting/CrashReportController.kt
- app/src/main/java/org/dhis2/utils/reporting/CrashReportControllerImpl.kt
> fix: [ANDROAPP-3903] check uid is not null when saving image

- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
> test: remove check for dataset test

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
> fix: [ANDROAPP-3877] copy search orgunit value to enrollment

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetSelectionView.java
> fix: [ANDROAPP-3917] keep option value for translated DE

- app/src/androidTest/java/org/dhis2/common/filters/FiltersRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/filters/FilterTest.kt
- app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
> test: [ANDROAPP-3925] adds home filter tests

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROSDK-1365)
> feat: [ANDROSDK-1365]  Add more info to error messages

- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3852)
> fix: [ANDROAPP-3852] Fix access check when creating a new event

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventRuleEngineRepository.java
- app/src/main/java/org/dhis2/utils/RuleUtilsProviderResult.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3902)
> fix: [ANDROAPP-3902] Warning on Complete does not evaluate expression

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
> fix: [ANDROAPP-3842] table render after pager setCurrentItem

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3983)
> feat: [ANDROAPP-3983] Scan view not working on the search screen

- app/src/main/res/layout/form_check_button.xml
[ANDROAPP-4007](https://jira.dhis2.org/browse/ANDROAPP-4007)
> fix: [ANDROAPP-4007] Yes/no Checkboxes display vertically or horizontally

- app/src/main/java/org/dhis2/data/dhislogic/DhisTrackedEntityInstanceUtils.kt
- app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
> feat: [ANDROAPP-4017] update sdk and date changes 

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- buildsystem/dependencies.gradle
> fix: [ANDROAPP-4005] Change displayName for displayFormName

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3927)
> fix: [ANDROAPP-3927] Allow enrollment if there are no search attributes

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/TimeView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3928)
> feat: [ANDROAPP-3928] Show error in date fields not showing

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/formatters/DateLabelFormatter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3900)
> fix: [ANDROAPP-3900] Axis labels overlap

- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3912)
> fix: [ANDROAPP-3912] add eventStatus to filter by eventDate

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinatesViewBindings.kt
- app/src/main/res/layout/form_coordinates.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4053)
> fix: [ANDROAPP-4053] Static error text not showing in coordinates

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
> fix: [Androapp 4054] Crash in form with onItemAction

- app/src/main/java/org/dhis2/data/dhislogic/OrganisationUnitExtensions.kt
- app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
- app/src/test/java/org/dhis2/data/dhislogic/OrganisationUnitExtensionsTest.kt
> fix: [ANDROAPP-3879] check period and catCombo after changing another value

- app/build.gradle
- app/src/androidTest/java/org/dhis2/usescases/sync/SyncActivityTest.kt
- app/src/main/java/org/dhis2/data/location/LocationProviderImpl.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/MapSelectorActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailActivity.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorInjector.kt
- app/src/main/java/org/dhis2/utils/customviews/DateTableView.java
- app/src/test/java/org/dhis2/usescases/sync/SyncPresenterTest.kt
- buildsystem/dependencies.gradle
- dhis_android_analytics/build.gradle
- form/build.gradle
- tableview/build.gradle
- viewpagerdotsindicator/build.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4014)
> build: [ANDROAPP-4014] upgrade target and build tools version

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenterTest.kt
[ANDROAPP-2934](https://jira.dhis2.org/browse/ANDROAPP-2934)
> test: [ANDROAPP-2934] Event Capture presenter unit test

- app/src/main/java/org/dhis2/utils/reporting/CrashReportControllerImpl.kt
- buildsystem/dependencies.gradle
> fix: Comment log non fatal and messages on Sentry.

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepository.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/res/values/strings.xml
> fix: [ANDROAPP-4076] send programStageUid

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormViewFragmentFactory.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
> fix: [ANDROAPP-4069] Hotfix could not find fragment constructor 

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
> fix: Sync error color

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/service/SyncGranularRxWorker.java
- app/src/main/java/org/dhis2/data/service/SyncPresenter.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4093)
> fix: [ANDROAPP-4093] Sync error message in dashboard and home

- RELEASE.md
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormViewFragmentFactory.kt
- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncGranularRxWorker.java
- app/src/main/java/org/dhis2/data/service/SyncPresenter.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/data/service/SyncResult.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepository.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/settings/SettingsRepository.kt
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- app/src/main/java/org/dhis2/usescases/settings/models/DataSettingsViewModel.kt
- app/src/main/java/org/dhis2/utils/Constants.java
- app/src/main/java/org/dhis2/utils/customviews/OptionSetPopUp.java
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/java/org/dhis2/utils/optionset/OptionSetOptionsHandler.kt
- app/src/main/java/org/dhis2/utils/optionset/OptionSetPresenter.kt
- app/src/main/res/values/strings.xml
- buildsystem/dependencies.gradle
- release.info
- whatsnew/whatsnew-en-US
> build: 2.4.2 release

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
> fix: Enrollment crash

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/TestingData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToPieChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToPieData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/PercentageValueFormatter.kt
> feat: [ANDROAPP-4049] change piechart design

- docs/src/commonmark/en/content/implementation-guide/mobile-device-specs.md
> doc: Add more information about the minimum requirements and deprecation of 4.4 [skip ci]

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/views/MapSelectorActivity.kt
> test: [ANDROAPP-4061] review search tests

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/TimeView.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4096)
> fix: [ANDROAPP-4096] Date fields showing wrong errors from program rules

- docs/src/commonmark/en/content/capture-app/app-android-settings-configuration.md
> docs: Fix layout for program specific pictures [skip ci]

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/main/res/layout/fragment_tei_data.xml
> fix: [Androapp-4099] Not show FAB button to add events in TEI dashboard if is not possible

- app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/TeisMapperExtensions.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
> fix: [ANDROAPP-4075] select relationships on search map

- docs/src/commonmark/en/content/capture-app/features-supported.md
- docs/src/commonmark/en/content/implementation-guide/dhis2-configuration-for-android.md
Add a note in two docs about deleting local TEI not requiring the authorities.
> docs: TEI local delete and authorities [skip ci]

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPageConfigurator.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPageConfiguratorTest.kt
> fix: [ANDROAPP-4237] dashboard on landscape

- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/TrackerAnalyticsRepositoryTest.kt
- commons/src/main/java/org/dhis2/commons/featureconfig/model/Feature.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/TestingData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/AnalyticsTeiSettingsToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/ChartsGlobalStyles.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/DataElementToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToBarEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToPieChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToPieData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/ProgramIndicatorToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProvider.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProviderImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/PeriodStepProvider.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/PeriodStepProviderImpl.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ChartsRepositoryTest.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/data/GraphTest.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntryTest.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProviderImplTest.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/providers/PeriodStepProviderImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4073)
> feat: [ANDROAPP-4073] Link SDK calls with group analytic model

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
[ANDROAPP-4246](https://jira.dhis2.org/browse/ANDROAPP-4246)
> fix: [ANDROAPP-4246] Dataset Row total cell correctly calculates values

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
> fix: [ANDROAPP-4254] Crash with vertical radio button optionSetViewModel

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/LayerConstants.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/FieldMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
> fix: [ANDROAPP-4241] update carousel with event data elements

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4235)
> [ANDROAPP-4235] Update TEI when sync

- app/src/main/res/layout-land/activity_search.xml
> fix: [ANDROAPP-4075] search map crash on landscape

- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
> fix: [Androapp-4267] Logout Crash

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4249)
> fix: [ANDROAPP-4249] Update SDK to fix unique attribute sync error

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
> fix: [ANDROAPP-4246] dataset column totals

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.kt
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.kt
- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionView.kt
- app/src/test/java/org/dhis2/usescases/programstageselection/ProgramStageSelectionPresenterTest.kt
[ANDROAPP-4269](https://jira.dhis2.org/browse/ANDROAPP-4269)
> fix: [ANDROAPP-4269] Fixes future date selection when scheduling a event

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/OnEditionListener.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4271)
> fix: [ANDROAPP-4271] App crashes after exiting an event

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4273)
> fix: [ANDROAPP-4273] App display incorrect screen in Event notes tab

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
[ANDROAPP-4274](https://jira.dhis2.org/browse/ANDROAPP-4274)
> fix: [ANDROAPP-4274] Updates orgUnit selector list when changing report date

- app/src/main/java/org/dhis2/utils/customviews/navigationbar/NavigationBottomBar.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
> fix: [ANDROAPP-4261] analytics bugs

- app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
Please include a summary of the change and include the related if it exists.
[ANDROAPP-3129](https://jira.dhis2.org/browse/ANDROAPP-3129)
> feat: [ANDROAPP-3129] Hide OrgUnit Filter if user has ony one OrgUnit assigned

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/Charts.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepository.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/DhisAnalyticCharts.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/bindings/AnalyticsBindings.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/formatters/CategoryFormatter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsAdapter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/ChartViewHolder.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsFragment.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsViewModel.kt
- dhis_android_analytics/src/main/res/drawable/ic_visualization_filter.xml
- dhis_android_analytics/src/main/res/layout/item_chart.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4262)
> feat: [ANDROAPP-4262] Link SDK calls with visualization filter PERIOD and RESET

- app/src/main/java/org/dhis2/data/tuples/Septet.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/utils/D2EditionMapper.kt
- app/src/main/res/layout/activity_event_initial.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
[ANDROAPP-3565](https://jira.dhis2.org/browse/ANDROAPP-3565)
> feat: [ANDROAPP-3565] Adds a reason why an Event is not editable.

- app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- commons/src/main/java/org/dhis2/commons/filters/LocaleSelector.kt
- commons/src/main/java/org/dhis2/commons/resources/LocaleSelector.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-2925)
> feat: [ANDROAPP-2925] Interface based on DHIS2 user language

- app/src/main/java/org/dhis2/utils/D2ErrorUtils.java
- app/src/main/res/values/strings.xml
> feat: [ANDROAPP-3569] login error messages

- app/src/main/res/layout-land/activity_event_initial.xml
[ANDROAP4281](https://jira.dhis2.org/browse/ANDROAP4281)
> fix: [ANDROAP-4281] Show non editable reason in landscape

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/Charts.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepository.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/DhisAnalyticCharts.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsFragment.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsViewModel.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4236)
> feat: [ANDROAPP-4236] Link SDK calls with analytics filter OU

- dhis_android_analytics/src/main/res/values/strings.xml
> fix: Missing resources in commons module

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
Adapt capture app to Result wrapper in Analytics (ANDROSDK-1423)
> feat: Adapt capture app to sdk changes (androsdk-1423)

- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/BaseIndicatorRepository.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorRepository.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/TrackerAnalyticsRepository.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/AnalyticsTeiSettingsToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/DataElementToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/ProgramIndicatorToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProvider.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProviderImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsAdapter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsFragment.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ChartsRepositoryTest.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProviderImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4276)
> feat: [ANDROAPP-4276] Apply PERIOD and OU filter in TEI dashboard charts

- docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
> chore: fix typos

- docs/src/commonmark/en/content/capture-app/program-indicators.md
> chore: fixed typo & table markup

- docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
> docs: include more cases  + style data field

- app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/FieldMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiEventMapLayer.kt
- app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
[ANDROAPP-4074](https://jira.dhis2.org/browse/ANDROAPP-4074)
> fix: [ANDROAPP-4074] Deselects TEI when selecting relationships layer to be display on the map

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/res/layout-land/activity_event_initial.xml
- app/src/main/res/layout/activity_event_initial.xml
- app/src/main/res/values/strings.xml
[ANDROAPP-4286](https://jira.dhis2.org/browse/ANDROAPP-4286)
> fix: [ANDROAPP-4286] Change non edition reason design and messages

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4278)
> fix: [ANDROAPP-4278] Block edition of detail fields in a read only stage

- .tx/config
> fix(translations): Add source for analytics resources

- app/src/main/java/org/dhis2/data/server/ServerSettingsRepository.kt
- app/src/main/java/org/dhis2/data/server/UserManager.java
- app/src/main/java/org/dhis2/data/server/UserManagerImpl.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4284)
> fix: [ANDROAPP-4284] Allow screen capture if configured

- app/build.gradle
- app/src/test/java/org/dhis2/data/filter/DataSetFilterSearchHelperTest.kt
- app/src/test/java/org/dhis2/data/filter/EventProgramFilterSearchHelperTest.kt
- app/src/test/java/org/dhis2/data/filter/TrackerFilterSearchHelperTest.kt
- buildsystem/dependencies.gradle
> fix: Hotfix/2.4.3 fix jobs

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/SerieColors.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4290)
> fix: [ANDROAPP-4290] Update SerieColor list

- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
> fix: [ANDROAPP-4279] Add clear filter before logout

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
[ANDROAPP-4296](https://jira.dhis2.org/browse/ANDROAPP-4296
> fix: [ANDROAPP-4296] Prevents from closing polygon selection in enrollment form

- commons/src/main/java/org/dhis2/commons/popupmenu/AppMenuHelper.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/extensions/AnalyticModelExtension.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
- dhis_android_analytics/src/main/res/drawable/ic_arrowback_chart.xml
- dhis_android_analytics/src/main/res/drawable/ic_check_chart_white.xml
- dhis_android_analytics/src/main/res/menu/org_unit_menu.xml
- dhis_android_analytics/src/main/res/menu/period_daily_filter_menu.xml
- dhis_android_analytics/src/main/res/menu/period_filter_menu.xml
- dhis_android_analytics/src/main/res/menu/period_monthly_filter_menu.xml
- dhis_android_analytics/src/main/res/menu/period_other_filter_menu.xml
- dhis_android_analytics/src/main/res/menu/period_weekly_filter_menu.xml
- dhis_android_analytics/src/main/res/menu/period_yearly_filter_menu.xml
> fix: [ANDROAPP-4308] Pixel perfect and filter bug's

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepository.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4293)
> feat: [ANDROAPP-4293] Enable dataSet local analytics

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureView.java
> fix: [ANDROAPP-4114] warning message on PictureView

- app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
- app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainNavigator.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventPageConfigurator.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/res/layout/activity_program_event_detail.xml
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPageConfiguratorTest.kt
- app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
[ANDROAPP-4078](https://jira.dhis2.org/browse/ANDROAPP-4078)
> fix: [ANDROAPP-4078] Show map option in Navigation bar if any coordinate field or attribute exist

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/utils/RuleUtilsProviderResult.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
> fix: [ANDROAPP-4259] display warning counter

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeBindings.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeViewModel.java
> fix: [ANDROAPP-4324] handle age format crash

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventPageConfigurator.kt
- commons/src/main/res/menu/navigation_event_list.xml
> feat: [ANDROAPP-4309] enable local analytics in event programs

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/values/strings.xml
[ANDROAPP-4029](https://jira.dhis2.org/browse/ANDROAPP-4029)
> fix: [ANDROAPP-4029] Adds button to display original list when at least 1 attribute is needed to perform a search

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProviderImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableAdapter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableHolder.kt
- dhis_android_analytics/src/main/res/layout/analytics_table_cell.xml
- dhis_android_analytics/src/main/res/layout/analytics_table_fixed_header.xml
- dhis_android_analytics/src/main/res/layout/analytics_table_header.xml
- dhis_android_analytics/src/main/res/values/colors.xml
- tableview/src/main/java/com/evrencoskun/tableview/TableView.java
- tableview/src/main/res/drawable/cell_bg.xml
- tableview/src/main/res/values/colors.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4328)
> fix: [ANDROAPP-4328] Visualization render issues

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3745)
> fix: [ANDROAPP-3745] Show event category options ordered

- app/src/main/res/layout-land/fragment_program.xml
> fix: [ANDROAPP-4330] Adds bottom padding to recyclerview in landscape mode on program list in home

- app/src/main/res/layout-land/activity_search.xml
> fix: [ANDROAPP-4334] hidden bottom bar for landscape

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/res/layout-land/activity_dashboard_mobile.xml
- app/src/main/res/layout/activity_dashboard_mobile.xml
- app/src/main/res/layout/fragment_tei_data.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4283)
> fix: [ANDROAPP-4283] Missing loading spinner in TEI dashboard

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/MatrixOptionSetModel.kt
- app/src/test/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/MatrixOptionSetModelTest.kt
> fix: [ANDROAPP-4342] ShowOptionGroup program rule on matrixOptionSet

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/test/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImplTest.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/main/java/org/dhis2/form/model/FieldUiModel.kt
- form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt
- form/src/main/java/org/dhis2/form/model/RowAction.kt
- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
- form/src/main/java/org/dhis2/form/ui/event/DialogDelegate.kt
- form/src/main/java/org/dhis2/form/ui/provider/DisplayNameProvider.kt
- form/src/main/java/org/dhis2/form/ui/provider/DisplayNameProviderImpl.kt
- form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4110)
> fix: [ANDROAPP-4110] Move storage to FormViewModel

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImplTest.kt
> fix: [ANDROAPP-4367] Indicator tab not showing up

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- form/src/main/java/org/dhis2/form/ui/event/UiEventFactoryImpl.kt
- form/src/main/java/org/dhis2/form/ui/provider/DisplayNameProviderImpl.kt
- form/src/main/res/layout/form_date_time.xml
> fix: [ANDROAPP-4336] search form problems

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/charts/SizeRadarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToRadarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/renderers/RadarRenderer.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4373)
> fix: [ANDROAPP-4373] Increase charts height

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/SerieColors.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/ChartsGlobalStyles.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToBarEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToPieEntry.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToPieChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToPieData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToRadarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToRadarData.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/ChartViewHolder.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4372)
> fix: [ANDROAPP-4372] Highlight visualization serie when clicked

- app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4030)
> fix: [ANDROAPP-4030] Assign blank PRA does not work for DE

- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
> fix: [ANDROAPP-4339] Dataset cells misaligment and crashes

- app/src/main/res/layout-land/fragment_tei_data.xml
[ANDROAPP-4390](https://jira.dhis2.org/browse/ANDROAPP-4390)
> fix: [ANDROAPP-4390] Adds loading progress to tei dashboard event list in landscape

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
- dhis_android_analytics/src/main/res/layout/item_chart.xml
- dhis_android_analytics/src/main/res/values/strings.xml
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ui/AnalyticsModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4379)
> fix: [ANDROAPP-4379] Pie chart with all 0 values does not render

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerContracts.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java
> fix: [ANDROAPP-4412] Clear filters when resetting app

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
[ANDROAPP-4419](https://jira.dhis2.org/browse/ANDROAPP-4419)
> fix: [ANDROAPP-4419] TEI dashboard without program never stops loading

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4420)
> fix: [ANDROAPP-4420] Legends not being updated

- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
> fix: [ANDROAPP-4415] Track custom events when sync is not launch

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepository.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/utils/RuleUtilsProviderResult.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProvider.kt
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImplTest.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4418)
> fix: [ANDROAPP-4418] Apply rule actions in tei dashboard

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3759)
> fix: [ANDROAPP-3759] Stage write access should not depend on program

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/YesNoView.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4030)
> fix: [ANDROAPP-4030] Empty string is parsed as false

- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
> fix: Crash when there is no settings app

- form/src/main/java/org/dhis2/form/ui/validation/validators/FieldMaskValidator.kt
- form/src/test/java/org/dhis2/form/ui/validation/validators/FieldMaskValidatorTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4385)
> feat: [ANDROAPP-4385] Fieldmask validator fix

- app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchMessageResult.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4289)
> fix: [ANDROAPP-4289] Force show message for online error

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4428)
> fix: [ANDROAPP-4428] Check write permissions for tei or program stage

- app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
> fix: Ignore Flaky tests

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchMessageMapper.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchMessageResult.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchResources.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchMessageMapperTest.kt
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4289)
> fix: [ANDROAPP-4289] Search message handler

- commons/src/main/java/org/dhis2/commons/filters/data/EventProgramFilterSearchHelper.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4436)
> fix: [ANDROAPP-4436] Do not show RELATIONSHIP events in program without registration list

- app/src/main/java/org/dhis2/usescases/settings/SettingsRepository.kt
- app/src/test/java/org/dhis2/usescases/settings/SettingsRepositoryTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4437)
> fix: [ANDROAPP-4437] Do not count RELATIONSHIP events in settings

- app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt
- app/src/test/java/org/dhis2/usescases/main/program/ProgramRepositoryImplTest.kt
- commons/src/main/java/org/dhis2/commons/filters/data/EventProgramFilterSearchHelper.kt
- commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4435)
> fix: [ANDROAPP-4435] Do not count RELATIONSHIP events in home

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/data/GraphTest.kt
> fix: [ANDROAPP-4447] Series with empty coordinates exception

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewModel.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROSDK-1466)
> fix: [ANDROSDK-1466] Relationship events not downloaded

- RELEASE.md
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- buildsystem/dependencies.gradle
> fix: Fix crash when checking D2 before logged

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4463)
> fix: [ANDROAPP-4463] not show filters when loading maps view

- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailLiveAdapter.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListPresenter.kt
> test: Remove recyclerview animation and sync with tests

- scripts/change_java_version.sh
> fix: Change java 8/11

- scripts/reviewers.py
[ANDROAPP-4333](https://jira.dhis2.org/browse/ANDROAPP-4333)
> fix: [ANDROAPP-4333] Updates reviewers script.

- app/src/androidTest/java/org/dhis2/usescases/filters/FilterTest.kt
[ANDROAPP-4465](https://jira.dhis2.org/browse/ANDROAPP-4465)
> test: [ANDROAPP-4465] reviews checkSyncFilter test

- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
[ANDROAPP-4469](https://jira.dhis2.org/browse/ANDROAPP-4469)
> fix: [ANDROAPP-4469] Adds check when trying to collapse an open section

- app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt
- app/src/androidTest/java/org/dhis2/usescases/about/AboutTest.kt
- app/src/androidTest/java/org/dhis2/usescases/jira/JiraTest.kt
- app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
- app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
- app/src/androidTest/java/org/dhis2/usescases/pin/PinTest.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/settings/SettingsTest.kt
- app/src/debug/java/org.dhis2/data/appinspector/AppInspector.kt
> test: Add new permissions

- bitrise.yml
> fix: Add bitirse yml [skip ci]

- buildsystem/dependencies.gradle
- release.info
> chore: Updating version code and version name for version 2.5.1 [skip ci]

- bitrise.yml
> chore: Adds bitrise trigger for 2.5.1

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4483)
> fix: [ANDROAPP-4483] Completion percentage error

- scripts/reviewers.py
> chore: Cherry-picks reviewers.py update commit

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
> fix: [ANDROAPP-4464] Events - Avoid dynamic paging with fixed indexes

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4405)
> fix: [ANDROAPP-4405] Bottom Nav. Analytics icon selected color in Event programs

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4470)
> fix: [ANDROAPP-4470] replace default column names by Values

- app/src/main/res/values-sw600dp/booleans.xml
> fix: [ANDROAPP-4396] Update is_tablet value and avoid phones in landscape

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/utils/customviews/navigationbar/NavigationBottomBar.kt
> fix: [ANDROAPP-4497] crash when rotating mapview

- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4490)
> fix: [ANDROAPP-4490] Do not assign value to hidden field

- .gitignore
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt
[ANDROID-4459](https://jira.dhis2.org/browse/ANDROID-4459)
> fix: [ANDROID-4459] Relationships show tei name instead of tei uid.

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
> fix: [ANDROAPP-4496] hide section program rule

- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
> fix: [ANDROAPP-4495] clean mandatory fields when rule is not applied

- app/src/main/java/org/dhis2/data/forms/dataentry/FormViewFragmentFactory.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4492)
> fix: [ANDROAPP-4492] Clicking the TEI coordinate map opens a stage

- bitrise.yml
> ci: [skip ci] Change Nancy Email

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4461)
> fix: [ANDROAPP-4461] Analytics alternative titles are not displayed

- app/build.gradle
> fix: [ANDROAPP-4489] Add other architectures for mapbox NDK

- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4488)
> fix: [ANDROAPP-4488] Section click crashed randomly

- commons/src/main/java/org/dhis2/commons/resources/D2ErrorUtils.kt
- commons/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4430)
> fix: [ANDROAPP-4430] Handle Http response

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchPageConfigurator.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
> fix: [Androapp 4486] ANR Maps UI Thread

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/test/java/org/dhis2/data/filter/FilterRepositoryTest.kt
- commons/src/main/java/org/dhis2/commons/filters/FiltersAdapter.kt
- commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt
> fix: [Androapp-4366] Wrong TET Filters 

- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4402)
> feat: [ANDROAPP-4402] App should terminate syncing process when loging out

- form/src/main/java/org/dhis2/form/ui/binding/CoordinatesBindings.kt
- form/src/main/java/org/dhis2/form/ui/binding/FieldBindings.kt
- form/src/main/res/layout/form_coordinate_custom.xml
> fix: [ANDROAPP-4422] coordinates focus (FORM)

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinatesViewBindings.kt
- app/src/main/res/layout/form_coordinates.xml
- form/src/main/java/org/dhis2/form/ui/binding/FieldBindings.kt
> fix: [ANDROAPP-4422] coordinate focus

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/charts/ChartMarker.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4451)
> fix: [ANDROAPP-4451] Label indicating the value in bar charts not working

- app/build.gradle
- app/src/androidTest/java/org/dhis2/usescases/FlowTestsSuite.kt
- app/src/androidTest/java/org/dhis2/usescases/UseCaseTestsSuite.kt
- bitrise.yml
- scripts/browserstackBitrise.sh
- scripts/config.init
- scripts/flow_tests_configurator.sh
> feat: [Androapp-4302] Split UI test into two different flows

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4490)
> fix: [ANDROAPP-4490] Loop message when assigning before hidding field

- bitrise.yml
> fix: Fix issue with Flow UI Tests

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeView.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeHolder.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
> fix: [ANDROAPP-4516] set hasTotal in adapter

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
> fix: [ANDROAPP-4529] fab visibility after scan

- bitrise.yml
> fix: [skip ci] fix flow test CI

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
> fix: [ANDROAPP-4490] update field value

- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4544)
> fix: [ANDROAPP-4544] Sync re-starts if it takes more than 10 minutes

- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
> feat: [ANDROAPP-4332] Track server when user logged in

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4541)
> fix: [ANDROAPP-4541] Error in the event navigation panel

- form/src/main/res/layout/form_radio_button.xml
- form/src/main/res/layout/form_toggle.xml
> feat: [ANDROAPP-4493] Rremoves 'yes' label with YES_ONLY value type fields.

- buildsystem/dependencies.gradle
> chore: updates sdk to master branch and 1.5.1 version.

- bitrise.yml
> fix: [skip ci] add install basic app

- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
- buildsystem/dependencies.gradle
> fix: update sdk

- bitrise.yml
> feat: add zxing build gradle in script

- commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreePresenter.kt
- commons/src/main/java/org/dhis2/commons/orgunitselector/OrgUnitSelectorHolder.kt
- commons/src/main/res/layout/item_ou_tree.xml
> feat: [ANDROAPP-2520] bold OUs selected on OUs tree

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt
- app/src/main/res/layout/activity_event_initial.xml
- app/src/main/res/layout/fragment_dataset_detail.xml
- app/src/main/res/layout/item_event.xml
- app/src/main/res/layout/item_program_model.xml
- app/src/main/res/layout/item_search_tracked_entity.xml
- app/src/main/res/layout/item_stage_section.xml
- commons/build.gradle
- commons/src/main/java/org/dhis2/commons/bindings/TEICardExtensions.kt
- commons/src/main/java/org/dhis2/commons/resources/ColorUtils.java
- commons/src/main/java/org/dhis2/commons/ui/MetadataIcon.kt
- commons/src/main/java/org/dhis2/commons/ui/MetadataIconData.kt
- dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselTeiHolder.kt
- dhis2_android_maps/src/main/res/layout/item_carousel_tei.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4503)
> feat: [ANDROAPP-4503] New Metadata Icon rendering

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryBaseRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/FieldViewModelFactory.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/FieldViewModelFactoryImpl.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageRow.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- form/src/main/java/org/dhis2/form/ui/FieldViewModelFactory.kt
- form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt
- form/src/main/java/org/dhis2/form/ui/LayoutProviderImpl.kt
- form/src/main/java/org/dhis2/form/ui/provider/LayoutProvider.kt
- form/src/main/java/org/dhis2/form/ui/provider/UiEventTypesProvider.kt
- form/src/main/java/org/dhis2/form/ui/provider/UiEventTypesProviderImpl.kt
[ANDROAPP-4258 ](https://jira.dhis2.org/browse/ANDROAPP-4258)
> feat: [ANDROAPP-4258] Adds renderingTypes to enrollment form

- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewHolder.kt
- app/src/main/res/layout/item_program_stage.xml
- app/src/main/res/layout/item_relationship.xml
- dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselEventHolder.kt
- dhis2_android_maps/src/main/res/layout/item_carousel_event.xml
[ jira issue ](https://jira.dhis2.org/browse/4503)
> fix: missing metadataicon

- bitrise.yml
> build: Update workflows [skip ci]

- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailView.java
- app/src/main/res/layout/activity_dataset_detail.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4559)
> feat: [ANDROAPP-4559] Sync button in Dataset listing

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/res/layout-land/activity_dashboard_mobile.xml
- app/src/main/res/layout/activity_dashboard_mobile.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4560)
> feat: [ANDROAPP-4560] Sync button in TEI dashboard

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/res/layout-land/activity_search.xml
- app/src/main/res/layout/activity_search.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4557)
> feat: [ANDROAPP-4557] Add sync button in search

- app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
- app/src/main/res/layout/activity_program_event_detail.xml
> feat: [ANDROAPP-4558] Add granular sync for program event

- bitrise.yml
> fix: [skip ci] Add WebSettingsApp Job

- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStore.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- form/src/main/java/org/dhis2/form/ui/binding/FieldBindings.kt
> fix: [ANDROAPP-4250] Fix during search when you do not have enrollment yet

- bitrise.yml
> fix: [skip ci] fix settings app job

- app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
- app/src/main/java/org/dhis2/utils/ValueUtils.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4570)
> fix: [ANDROAPP-4570] Option set spinner in search

- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4567)
> fix: [ANDROAPP-4567] Bidirectional relationships wrong directions.

- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
- app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselRelationshipHolder.kt
- app/src/main/java/org/dhis2/uicomponents/map/mapper/MapRelationshipToRelationshipMapModel.kt
- app/src/main/java/org/dhis2/uicomponents/map/model/RelationshipUiComponentModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt
- app/src/test/java/org/dhis2/uicomponents/map/mocks/RelationshipUiCompomentDummy.kt
[ANDROAPP-4568](https://jira.dhis2.org/browse/ANDROAPP-4568)
> fix: [ANDROAPP-4568] Tei-event relantionships are display on Tei dashboard's relationship map

- app/src/main/java/org/dhis2/usescases/main/MainNavigator.kt
- app/src/main/java/org/dhis2/usescases/troubleshooting/TroubleshootingFragment.kt
- app/src/main/res/layout/activity_main.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-1655)
> fix: [ANDROAPP-1655] Improve transition and menu

- app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/EventRepository.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFieldProvider.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt
- form/src/main/java/org/dhis2/form/ui/FieldViewModelFactory.kt
- form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt
- form/src/main/java/org/dhis2/form/ui/provider/LegendValueProvider.kt
- form/src/main/java/org/dhis2/form/ui/provider/LegendValueProviderImpl.kt
- form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
- form/src/test/java/org/dhis2/form/ui/FieldViewModelFactoryImplTest.kt
> feat: [ANDROAPP-4569] update legend values

- app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
> fix: [ANDROAPP-4584] App doesn't capture QR code info in the login screen

- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormView.kt
- app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenterTest.kt
> feat: [Androapp-4613] Hide/show save button

- dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt
- form/src/main/java/org/dhis2/form/model/UiRenderType.kt
- form/src/main/java/org/dhis2/form/ui/binding/CoordinatesBindings.kt
> fix: [ANDROAPP-4585] Crash in maps with polygons:  DecodeResource returning null

- app/build.gradle
- app/src/main/java/org/dhis2/App.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/AccountRepository.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/AccountsActivity.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountsScreen.kt
- app/src/main/java/org/dhis2/utils/Constants.java
- app/src/main/res/layout-land/activity_login.xml
- app/src/main/res/layout/activity_login.xml
[ANDROAPP-455](https://jira.dhis2.org/browse/ANDROAPP-455)
> feat: [ANDROAPP-653] Implements multi-user accounts

- app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt
- whatsnew/whatsnew-en-US
> fix: Remove ServerURLWrapper from BaseTest.kt

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/TeiDownloadResult.kt
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-657)
> feat: [ANDROAPP-657] Break the glass

- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/main/java/org/dhis2/form/model/FieldUiModel.kt
- form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt
- form/src/main/java/org/dhis2/form/model/SectionUiModelImpl.kt
- form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4587)
> feat: [ANDROAPP-4587] Section not hidden if has no fields

- app/src/main/java/org/dhis2/ui/DataEntryBottomDialogContent.kt
- app/src/main/java/org/dhis2/ui/DataEntryDialogUiModel.kt
- app/src/main/java/org/dhis2/ui/DialogButtonStyle.kt
- app/src/main/java/org/dhis2/utils/customviews/DataEntryBottomDialog.kt
- app/src/main/res/drawable/ic_alert.xml
- app/src/main/res/drawable/ic_alert_red.xml
- app/src/main/res/drawable/ic_error_outline.xml
- app/src/main/res/drawable/ic_saved_check.xml
- app/src/main/res/values/strings.xml
- commons/src/main/java/org/dhis2/commons/data/FieldWithIssue.kt
> feat: [ANDROAPP-4591] data entry bottom dialog new design

- app/src/androidTest/java/org/dhis2/AppTest.kt
- app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/settings/SettingsTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureOrgUnit.kt
- app/src/main/res/layout/event_details_fragment.xml
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureOrgUnitTest.kt
> fix: Add testingServerUrl variable

- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
> fix: fix ui test flows

- app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountsScreen.kt
- app/src/main/res/layout/dhis_logo.xml
[ANDROAPP-4627](https://jira.dhis2.org/browse/ANDROAPP-4627)
> fix: [ANDROAPP-4627] Displays Dhis2 logo in manage account screen

- app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataIdlingResourceSingleton.kt
> fix: follow one path when finishing enrollment

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4602)
> fix: [ANDROAPP-4602] Handle change program in search screen

- form/src/main/res/layout/form_check_button.xml
- form/src/main/res/layout/form_option_set_selector.xml
- form/src/main/res/layout/form_radio_button.xml
- form/src/main/res/layout/form_toggle.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4624)
> fix: [ANDROAPP-4624] Warning/Error label placement in radiobutton/checkbox optionSets

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
> fix: [ANDROAPP-4614] discard changes issues

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormViewFragmentFactory.kt
- app/src/main/java/org/dhis2/ui/DataEntryBottomDialogContent.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/enrollment/provider/EnrollmentResultDialogUiProvider.kt
- app/src/main/res/values/strings.xml
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/main/res/values/strings.xml
> feat: [ANDROAPP-4593] implement new dialog in enrollment

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/res/layout-land/activity_search.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4023)
> fix: [ANDROAPP-4023] Hide search FAB in landscape

- app/src/main/java/org/dhis2/usescases/main/HomeRepository.kt
- app/src/main/java/org/dhis2/usescases/main/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
> feat: Track matomo server

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/res/layout/activity_event_capture.xml
- app/src/main/res/layout/activity_program_event_detail.xml
[ANDROAPP-4561](https://jira.dhis2.org/browse/ANDROAPP-4561)
> feat: [ANDROAPP-4561] Implements sync in event detail screen

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/ui/DataEntryBottomDialogContent.kt
- app/src/main/java/org/dhis2/ui/DialogButtonStyle.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/domain/ConfigureEventCompletionDialog.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4643)
> feat: ANDROAPP-4643 Implement back dialog on events

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/provider/EnrollmentResultDialogUiProvider.kt
> build: Update develop branch

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- commons/src/main/java/org/dhis2/commons/extensions/ViewExtensions.kt
- form/src/main/java/org/dhis2/form/ui/binding/FieldBindings.kt
- form/src/main/res/layout/form_edit_text_custom.xml
- form/src/main/res/layout/form_long_text_custom.xml
- form/src/main/res/layout/form_scan.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4582)
> fix: [ANDROAPP-4582] Improved focus handler in forms

- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/main/java/org/dhis2/ui/DataEntryBottomDialogContent.kt
> test: Add tag to compose item for assertion

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
[ANDROAPP-4561](https://jira.dhis2.org/browse/ANDROAPP-4561)
> fix: [ANDROAPP-4561] Crash in the sync dialog

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsViewBindings.kt
- app/src/main/res/layout-land/event_details_fragment.xml
- app/src/main/res/layout/event_details_fragment.xml
> fix: [ANDROAPP-4503] add metadata icon on event details

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToRadarData.kt
> fix: [ANDROAPP-4619] Add empty data for library crash

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/VisualizationToGraph.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/mappers/DimensionRowCombinatorTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4663)
> fix: [ANDROAPP-4663] Single value chart visualization crashing

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4592)
> fix: [ANDROAPP-4592] Remove re open when save completed event.

- app/src/main/java/org/dhis2/data/forms/dataentry/EventRepository.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormView.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCatCombo.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/EventDetailResourcesProvider.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsViewBindings.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsViewModel.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsViewModelFactory.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/ReopenButton.kt
- app/src/main/res/layout-land/event_details_fragment.xml
- app/src/main/res/layout/event_details_fragment.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCatComboTest.kt
- form/build.gradle
- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
- form/src/test/java/org/dhis2/form/ui/FormViewModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4610)
- x ] Smartphone Emulator
> fix: [ANDROAPP-4610] reopen form

- app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/main/java/org/dhis2/usescases/enrollment/provider/EnrollmentResultDialogUiProvider.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/domain/ConfigureEventCompletionDialog.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/provider/EventCaptureResourcesProvider.kt
- app/src/main/res/values/strings.xml
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
> fix: [ANDROAPP-4591] complete/errors dialog fixes

- app/src/main/java/org/dhis2/data/server/UserManager.java
- app/src/main/java/org/dhis2/data/server/UserManagerImpl.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/main/HomeRepository.kt
- app/src/main/java/org/dhis2/usescases/main/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/MainView.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashView.kt
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4616)
> fix: [ANDROAPP-4617] Open account management screen if available

- form/src/main/java/org/dhis2/form/data/DataEntryBaseRepository.kt
- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/main/java/org/dhis2/form/data/RuleUtilsProviderResult.kt
- form/src/main/java/org/dhis2/form/ui/DataEntryHeaderHelper.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4664)
> fix: [ANDROAPP-4664] Show errors, warnings and mandatory in section header

- app/src/main/java/org/dhis2/utils/customviews/QRDetailBottomDialog.kt
- app/src/main/java/org/dhis2/utils/customviews/QRImageController.kt
- app/src/main/java/org/dhis2/utils/customviews/QRImageControllerImpl.kt
- app/src/main/java/org/dhis2/utils/customviews/QRImageViewModel.kt
- app/src/main/java/org/dhis2/utils/customviews/QRImageViewModelFactory.kt
- app/src/test/java/org/dhis2/utils/customviews/QRImageControllerTest.kt
- form/src/main/java/org/dhis2/form/ui/binding/ScanBindings.kt
- form/src/main/java/org/dhis2/form/ui/event/UiEventFactoryImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4667)
> fix: [ANDROAPP-4667] Display QR when value is assigned

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchNavigationConfiguration.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchNavigator.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEUi.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchResult.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchResultHolder.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchNavigationConfigurationTest.kt
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
> fix: [ANDROAPP-4023] Missing flow in landscape

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountItem.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountsScreen.kt
- app/src/main/res/layout-land/activity_login.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values-v19/styles.xml
- app/src/main/res/values/styles.xml
[ANDROAPP-653 ](https://jira.dhis2.org/browse/ANDROAPP-653)
> fix: [ANDROAPP-653] Change appearance of login's disabled fields and manage Accounts shadows and fonts

- app/src/main/assets/paperwork.json
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinatesView.java
- app/src/main/java/org/dhis2/data/location/LocationProvider.kt
- app/src/main/java/org/dhis2/data/location/LocationProviderImpl.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/general/FragmentGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4641)
> refactor: [ANDROAPP-4641] stop location updates on pause

- scripts/uiTests.sh
> fix: Add UI Tests scripts

- app/src/main/res/layout/activity_dataset_detail.xml
- app/src/main/res/layout/activity_dataset_table.xml
- app/src/main/res/layout/activity_event_capture.xml
- app/src/main/res/layout/activity_program_event_detail.xml
[ANDROAPP-4331](https://jira.dhis2.org/browse/ANDROAPP-4331)
> fix: [ANDROAPP-4331] Sync button alignment in different screens

- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
> fix: [ANDROAPP-4684] granular sync on dataset

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEUi.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchResult.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/SearchUIData.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4674)
> fix: [ANDROAPP-4674] Filters in new search flow

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4671)
> fix: [ANDROAPP-4671] Reopen duplicates dataset tables

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/res/layout-land/activity_dashboard_mobile.xml
- app/src/main/res/layout-land/activity_event_initial.xml
- app/src/main/res/layout/activity_dashboard_mobile.xml
- app/src/main/res/layout/activity_dataset_detail.xml
- app/src/main/res/layout/activity_event_initial.xml
- app/src/main/res/layout/activity_program_event_detail.xml
[ANDROAPP-4331](https://jira.dhis2.org/browse/ANDROAPP-4331)
> fix: [ANDROAPP-4331] Title truncation and sync icon placement

- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
> fix: [ANDROAPP-4688, 4691, 653] don't return to login

- app/build.gradle
- bitrise.yml
- build.gradle
> ci: configure sonarcloud

- app/src/main/res/layout-land/event_details_fragment.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3651)
> fix: refactor land layout fragment details

- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
> fix: [ANDROAPP-4591] keyboard when saving form

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
- app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryTest.kt
> fix: [ANDROAPP-4689] dataset filter sections cat combo

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselTeiHolder.kt
> fix: [ANDROAPP-4680] Granular sync in tei dashboard for break the glass

- app/src/main/java/org/dhis2/utils/customviews/QRDetailBottomDialog.kt
> fix: [ANDROAPP-4667] Non editable QR field

- app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/utils/reporting/SentryOkHttpInterceptor.kt
- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4703)
> perf: [ANDROAPP-4703] update Sentry

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4704)
> fix: [ANDROAPP-4704] remove unnecessary assignment

- app/src/main/res/layout-land/event_details_fragment.xml
[ANDROAPP-3651](https://jira.dhis2.org/browse/ANDROAPP-3651)
> fix: [ANDROAPP-3651] Updated landscape mode edition of org unit field in event detail.

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
> fix: [ANDROAPP-4591] back pressed on enrollment

- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
> fix: [ANDROAPP-4709] save button only works once

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt
> fix: [ANDROAPP-4503] event details icon

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCoordinates.kt
- form/src/main/java/org/dhis2/form/data/GeometryController.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4712)
> fix: [ANDROAPP-4712] Clear coordinates on event details

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/res/layout/qr_detail_dialog.xml
> fix: Qr icon fix

- app/src/main/res/layout/activity_search.xml
> fix: [ANDROAPP-4023] Backdrop constraints

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableHolder.kt
[ANDROAPP-4705](https://jira.dhis2.org/browse/ANDROAPP-4705)
> refactor: [ANDROAPP-4705] Remove duplicated condition

- app/src/main/java/org/dhis2/data/server/OpenIdSession.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/AccountsActivity.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountItem.kt
- app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountsScreen.kt
- app/src/main/java/org/dhis2/usescases/main/HomeRepository.kt
- app/src/main/java/org/dhis2/usescases/main/HomeRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/MainView.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashView.kt
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
> fix: [ANDROAPP-653] design and flow fixes to multi-user feature

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchJavaToCompose.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEScreenState.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/SearchScreenConfigurator.kt
- app/src/main/res/layout/fragment_search_list.xml
> fix: Reset search params in landscape not showing

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
[ANDROAPP-653](https://jira.dhis2.org/browse/ANDROAPP-653)
> fix: [ANDROAPP-653] keeps server and user name on fields after a logout

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToBarEntry.kt
> fix: [ANDROAPP-4673] Grouped Bar charts values order

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
> fix: [ANDROAPP-4715] update results on reset search

- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
- form/src/main/java/org/dhis2/form/ui/binding/CoordinatesBindings.kt
> fix: [ANDROAPP-4718] save coordinates

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventCoordinates.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsViewModel.kt
> fix: [ANDROAPP-4718] save coordinates on events

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
> fix: [ANDROAPP-4721] display indicators

- app/src/main/java/org/dhis2/data/dhislogic/CategoryOptionExtensions.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
- app/src/main/java/org/dhis2/utils/customviews/CatOptionPopUp.kt
- app/src/test/java/org/dhis2/data/dhislogic/CategoryOptionExtensionsKtTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-1511)
> fix: [ANDROAPP-1511] filter category options bu org units

- app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventReportDate.kt
- commons/src/main/java/org/dhis2/commons/date/DateUtils.java
> fix: [ANDROAPP-4681] Fix schedule date for event based on enrollment date

- .gitmodules
- app/build.gradle
- buildsystem/dependencies.gradle
- settings.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4732)
> build: [ANDROAPP-4732] Remove zxing submodule

- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt
[ANDROAPP-4719](https://jira.dhis2.org/browse/ANDROAPP-4719)
> fix: [ANDROAPP-4719] Apps redirect user to manage account page after exiting and reopening the app

- .gitmodules
- app/build.gradle
- dhis_android_analytics/build.gradle
- form/build.gradle
- settings.gradle
> build: [ANDROAPP-4733] Remove rule engine submodule

- app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowTest.kt
> test: [ANDROAPP-4666] fix shouldCreateTEIAndFilterByEnrollment

- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
[ANDROAPP-4738](https://jira.dhis2.org/browse/ANDROAPP-4738)
> fix: [ANDROAPP-4738] use postValue() to save a value to a mutableLiveData in a background thread

- app/build.gradle
- buildsystem/dependencies.gradle
- commons/build.gradle
- dhis2_android_maps/build.gradle
- dhis_android_analytics/build.gradle
- form/build.gradle
[ANDROAPP-4734](https://jira.dhis2.org/browse/ANDROAPP-4734)
> chore: [ANDROAPP-4734] Removes duplicated dependencies

- app/src/main/java/org/dhis2/data/server/ServerComponent.java
- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/metadata/usecases/ProgramConfiguration.kt
- app/src/main/java/org/dhis2/metadata/usecases/TrackedEntityTypeConfiguration.kt
- app/src/main/java/org/dhis2/ui/ThemeManager.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListActivity.java
- app/src/test/java/org/dhis2/ui/ThemeManagerTest.kt
- app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4406)
> fix: [ANDROAPP-4406] Dashboard loses its color theme

- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/metadata/usecases/DataSetConfiguration.kt
- app/src/main/java/org/dhis2/ui/ThemeManager.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
- app/src/test/java/org/dhis2/ui/ThemeManagerTest.kt
- app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
> fix: [ANDROAPP-4406] Fix crash when opening data set

- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4683)
> fix: [ANDROAPP-4683] Dataset granular sync is no triggered if error

- form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
- form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4741)
> fix: [ANDROAPP-4741] Mandatory fields cache not been cleared

- app/src/main/java/org/dhis2/data/forms/dataentry/SearchTEIRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
> fix: [ANDROAPP-4737] IsUniqueAttribute crash

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListContract.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenter.java
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialogUiConfig.kt
- app/src/main/res/menu/dashboard_menu.xml
- app/src/main/res/menu/dashboard_menu_group.xml
- app/src/main/res/menu/dashboard_tei_menu.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-uz/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenterTest.kt
- app/src/test/java/org/dhis2/utils/granularsync/SyncStatusDialogUiConfigTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4534)
> fix: [ANDROAPP-4534] Remove TEI term in the app where possible

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormViewFragmentFactory.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4736)
> fix: [ANDROAPP-4736] FormView: Could not find fragment crash

- app/src/androidTest/java/org/dhis2/usescases/form/FormRobot.kt
> fix: Update espresso action for option set spinner

- app/src/main/java/org/dhis2/data/forms/ScanCaptureManager.kt
> fix: Add scan symbology only for GS1 Matrix

- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- tableview/src/main/java/com/evrencoskun/tableview/adapter/recyclerview/holder/AbstractViewHolder.java
- tableview/src/main/java/com/evrencoskun/tableview/handler/SelectionHandler.java
> fix: [ANDROAPP-4046] cell selection between tables

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4406)
> fix: [ANDROAPP-4406] Event loses color

- dhis2_android_maps/src/main/java/org/dhis2/maps/managers/TeiMapManager.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4080)
> fix[ANDROAPP-4080]: Update TEI image in maps when changed

- app/src/main/java/org/dhis2/metadata/usecases/FileResourceConfiguration.kt
- app/src/main/java/org/dhis2/metadata/usecases/ProgramConfiguration.kt
- app/src/main/java/org/dhis2/metadata/usecases/TrackedEntityInstanceConfiguration.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDownload/TeiDownloader.kt
- app/src/test/java/org/dhis2/usescases/teiDownload/TeiDownloaderTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4750)
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4753)
> fix[ANDROAPP-4750, ANDROAPP-4753]: Tei download crashes

- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerAdapter.kt
- app/src/main/java/org/dhis2/utils/OrientationUtils.kt
> fix: [ANDROAPP-4543] blank on multi-window mode

- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/res/values/styles.xml
- commons/src/main/java/org/dhis2/commons/popupmenu/AppMenuHelper.kt
- commons/src/main/res/values/styles.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3650)
> fix: [ANDROAPP-3650] Add horizontal margin to dropdown menu

- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- form/src/main/java/org/dhis2/form/data/EnrollmentRuleEngineRepository.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4609)
> fix: [ANDROAPP-4609] Rule action assign value ui test

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
> fix: [ANDROAPP-4639] dataset validation empty value

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt
[ANDROAPP-4749](https://jira.dhis2.org/browse/ANDROAPP-4749)
> fix: [ANDROAPP-4749] login button enables when adding text to password field 

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java
- app/src/main/java/org/dhis2/utils/customviews/OrgUnitDialog.java
- app/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3872)
> fix: [ANDROAPP-3872] Org Unit dialog wrong label

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchNavigationConfiguration.kt
> fix: [ANDROAPP-4762] update list on search

- app/src/test/java/org/dhis2/data/filter/FilterRepositoryTest.kt
- commons/src/main/java/org/dhis2/commons/filters/FilterResources.kt
- commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt
- commons/src/main/java/org/dhis2/commons/filters/data/TeiWorkingListScope.kt
- commons/src/main/java/org/dhis2/commons/filters/di/FilterModule.kt
- commons/src/main/java/org/dhis2/commons/resources/LocaleSelector.kt
- commons/src/main/java/org/dhis2/commons/resources/ResourceManager.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4615)
> fix: [ANDROAPP-4615] Items translations

- form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt
> fix: [ANDROAPP-4748] Make it Synchronized 

- buildsystem/dependencies.gradle
- release.info
> build: update info to v2.6.1

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiAttributesProvider.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
- app/src/test/java/org/dhis2/usescases/teiDashboard/TeiAttributesProviderTest.kt
[ANDROAPP-4740](https://jira.dhis2.org/browse/ANDROAPP-4740)
> fix: [ANDROAPP-4740] Attributes are shown consistently and ordered in relationships and dashboard screens

- app/src/androidTest/java/org/dhis2/usescases/sync/MockedWorkManagerController.kt
- app/src/androidTest/java/org/dhis2/usescases/sync/SyncActivityTest.kt
- app/src/main/java/org/dhis2/data/service/workManager/WorkManagerController.kt
- app/src/main/java/org/dhis2/data/service/workManager/WorkManagerControllerImpl.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt
- app/src/main/java/org/dhis2/usescases/splash/SplashView.kt
- app/src/main/java/org/dhis2/usescases/sync/SyncActivity.kt
- app/src/main/java/org/dhis2/usescases/sync/SyncPresenter.kt
- app/src/main/java/org/dhis2/usescases/sync/SyncView.kt
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/sync/SyncPresenterTest.kt
- commons/src/main/java/org/dhis2/commons/prefs/Preference.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4765)
> feat: [ANDROAPP-4765] Open home after metadata sync

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
[ANDROAPP-4772](https://jira.dhis2.org/browse/ANDROAPP-4772)
> fix: [ANDROAPP-4772] Single value Bar and Line chart are now display properly

- dhis2_android_maps/src/main/java/org/dhis2/maps/managers/EventMapManager.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4686)
> fix: [ANDROAPP-4686] carousel card not hidden if has no info in active layer

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
- app/src/main/res/layout/fragment_dataset_section.xml
- commons/src/main/java/org/dhis2/commons/featureconfig/model/Feature.kt
- compose-table/src/main/java/org/dhis2/compose_table/ui/DataSetTableUi.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4754)
> feat: [ANDROAPP-4754] Render data sets with Composable TableList

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinatesView.java
- app/src/main/java/org/dhis2/data/location/LocationProvider.kt
- app/src/main/java/org/dhis2/data/location/LocationProviderImpl.kt
- app/src/main/java/org/dhis2/data/location/LocationSettingLauncher.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/mapView/SearchTEMap.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3915)
> fix: [ANDROAPP-3915] Ask user to enable GPS

- scripts/browserstackBitrise.sh
> fix: Fix Browserstack API Changes

- form/src/main/java/org/dhis2/form/ui/DataEntryAdapter.kt
- form/src/main/java/org/dhis2/form/ui/FormViewHolder.kt
- form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
- form/src/main/java/org/dhis2/form/ui/LatitudeLongitudeTextWatcher.kt
- form/src/main/java/org/dhis2/form/ui/binding/CoordinatesBindings.kt
- form/src/main/java/org/dhis2/form/ui/validation/FieldErrorMessageProvider.kt
- form/src/main/res/layout/form_coordinate_custom.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4792)
> fix: [ANDROAPP-4792] Update sdk coordinate validator

- form/src/main/java/org/dhis2/form/ui/binding/CoordinatesBindings.kt
> fix: fix form tests

- app/src/main/java/org/dhis2/data/server/ServerModule.kt
- app/src/main/java/org/dhis2/ui/ThemeManager.kt
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/test/java/org/dhis2/ui/ThemeManagerTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4774)
> fix: [ANDROAPP-4774] Changing server offline does not update app color

- buildsystem/dependencies.gradle
> build: Update sdk to v1.6.1

- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
> fix: klint check

- app/src/main/res/drawable/ic_map_search.xml
- dhis2_android_maps/src/main/java/org/dhis2/maps/managers/MapManager.kt
- dhis2_android_maps/src/main/java/org/dhis2/maps/managers/TeiMapManager.kt
- dhis2_android_maps/src/main/res/drawable/ic_compass.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4770)
> fix: [ANDROAPP-4770] Map compass is hidden behind other icos

- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/ui/DetailsButton.kt
- app/src/main/java/org/dhis2/utils/HelpManager.java
- app/src/main/res/layout/fragment_tei_data_card_front.xml
- app/src/main/res/menu/dashboard_menu.xml
- app/src/main/res/menu/dashboard_menu_group.xml
- app/src/main/res/values/strings.xml
> feat: [ANDROAPP-4653] remove share button on dashboard

- buildsystem/dependencies.gradle
> release: update version code 115 and version name 2.7

- app/build.gradle
- bitrise.yml
- build.gradle
- commons/build.gradle
- compose-table/build.gradle
- compose-table/src/test/java/org/dhis2/compose_table/TableHeaderTest.kt
- dhis2_android_maps/build.gradle
- gradle.properties
- jacoco/jacoco.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4787)
> ci: [ANDROAPP-4787] enable sonar C.I

- app/src/main/java/org/dhis2/utils/customviews/navigationbar/NavigationBottomBar.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4764)
> fix: [ANDROAPP-4764] Transition between views in search Landscape

- build.gradle
> ci: sonar project name

- build.gradle
> ci: branch name

- build.gradle
> ci: fix sonar

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
> fix: [ANDROAPP-4720] filters on global search

- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4801)
> fix: [ANDROAPP-4801] Global sync from home should not trigger metadata

- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/EventDetailsIntegrationTest.kt
- form/src/main/java/org/dhis2/form/ui/binding/DateBindings.kt
- form/src/main/res/layout/form_date_time.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4798)
> fix: [ANDROAPP-4798] Select date field when clicked

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
> fix: Do not set composable tables if not enabled

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
> fix: move view model init. Crash lateinit

- app/src/main/res/layout/item_search_tracked_entity.xml
- app/src/main/res/layout/item_stage_section.xml
- commons/src/main/java/org/dhis2/commons/bindings/TEICardExtensions.kt
- commons/src/main/res/layout/custom_dialog.xml
[ANDROAPP-4728](https://jira.dhis2.org/browse/ANDROAPP-4728)
> fix: [ANDROAPP-4728] Increase clickable space to icons and button

- jenkins/ec2-android.yaml
- jenkins/license_accepter.sh
> feat: [Androapp-4783] EC2 Android Image for Jenkins

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/service/ReservedValuesWorkerModule.java
- app/src/main/java/org/dhis2/data/service/ServiceModule.java
- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncDataWorkerModule.java
- app/src/main/java/org/dhis2/data/service/SyncGranularRxModule.java
- app/src/main/java/org/dhis2/data/service/SyncInitWorkerModule.java
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorkerModule.java
- app/src/main/java/org/dhis2/data/service/SyncPresenter.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/data/service/SyncStatusController.kt
- app/src/main/java/org/dhis2/data/service/SyncStatusData.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramUi.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/mapView/SearchTEMap.kt
- app/src/main/res/drawable/ic_download_error.xml
- app/src/test/java/org/dhis2/data/services/SyncPresenterTest.kt
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/EventDetailsIntegrationTest.kt
- app/src/test/java/org/dhis2/usescases/reservedValues/ReservedValuePresenterTest.kt
- app/src/test/java/org/dhis2/utils/filters/workingLists/TeiFilterToWorkingListItemMapperTest.kt
- commons/src/main/java/org/dhis2/commons/bindings/Bindings.kt
- commons/src/main/java/org/dhis2/commons/bindings/TEICardExtensions.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4800)
> feat: [ANDROAPP-4800] Block programs while data sync is running

- app/src/main/java/org/dhis2/data/dhislogic/EnrollmentEventGeneratorRepositoryImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncModule.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/SMSSyncProvider.kt
- app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
- app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
- app/src/test/java/org/dhis2/utils/granularsync/SMSSyncProviderTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4795)
> fix: [ANDROAPP-4795] SMS Sync

- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- form/src/main/java/org/dhis2/form/data/metadata/OptionSetConfiguration.kt
- form/src/main/java/org/dhis2/form/data/metadata/OrgUnitConfiguration.kt
- form/src/main/java/org/dhis2/form/ui/LayoutProviderImpl.kt
- form/src/main/java/org/dhis2/form/ui/provider/DisplayNameProviderImpl.kt
- form/src/test/java/org/dhis2/form/ui/provider/DisplayNameProviderImplTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4743)
> fix: [ANDROAPP-4743, ANDROAPP-4823] Numeric option sets

- app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
- commons/src/main/java/org/dhis2/commons/resources/LocaleSelector.kt
> fix: infinite login and wrong message

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
> fix: Form view crash 

- app/src/androidTest/java/org/dhis2/usescases/sync/MockedWorkManagerController.kt
- app/src/main/java/org/dhis2/data/service/workManager/WorkManagerController.kt
- app/src/main/java/org/dhis2/data/service/workManager/WorkManagerControllerImpl.kt
- app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
> fix: [ANDROAPP-4801, ANDROAPP-4822] Do not trigger metadata from home sync

- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailViewModel.kt
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailViewModelFactory.kt
- app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetPageConfigurator.kt
- app/src/main/res/layout/activity_dataset_detail.xml
- app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailViewModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4818)
> fix: Black screen when opening a data set

- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramUi.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModelMapper.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListActivity.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListAdapter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListContract.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListEnrollmentViewHolder.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenter.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepository.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/ui/EnrollToProgram.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/ui/teiProgramListBindings.kt
- app/src/main/res/layout/item_tei_programs_programs.xml
[ANDROAPP-4778](https://jira.dhis2.org/browse/ANDROAPP-4778)
> feat: [ANDROAPP-4778] Blocks enroll to program when programs are still syncing

- app/src/main/java/org/dhis2/data/forms/dataentry/ProgramAdapter.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/ProgramSpinnerModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
- app/src/main/res/layout/spinner_program_layout.xml
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
- app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
This PR should wait https://github.com/dhis2/dhis2-android-capture-app/pull/2724 to be merged
> feat: [ANDROAPP-4777] block navigation between tracker programs

- buildsystem/dependencies.gradle
> build: update sdk

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- app/src/main/res/layout/fragment_settings.xml
[ANDROAPP-3115](https://jira.dhis2.org/browse/ANDROAPP-3115)
> fix: [ANDROAPP-3115] Adds animation to settings 

- app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
[ANDROAPP-4740](https://jira.dhis2.org/browse/ANDROAPP-4740)
> fix: [ANDROAPP-4740] relationship's tei dashboard attributes

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormViewFragmentFactory.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/model/EventCompletionDialog.kt
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- form/src/main/java/org/dhis2/form/ui/provider/EnrollmentResultDialogUiProvider.kt
- form/src/main/res/values-ar/strings.xml
- form/src/main/res/values-es/strings.xml
- form/src/main/res/values-vi/strings.xml
- form/src/main/res/values/strings.xml
> refactor: [ANDROAPP-4808] move EnrollmentResultDialogUiProvider to form

- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncPresenter.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/data/service/SyncStatusController.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4434)
> build: [ANDROAPP-4434] Set errors when connection is lost

- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
- app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4199)
> feat: [ANDROAPP-4199] Change TEI ownership for permanent referral

- app/src/main/java/org/dhis2/data/dhislogic/EnrollmentEventGeneratorRepositoryImpl.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/FieldViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/file/FileViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerViewModel.java
- app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/unsupported/UnsupportedViewModel.java
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
- app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/TableCellUiOptions.kt
> feat: [ANDROAPP-4811] table dropdown options

- app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.kt
- app/src/test/java/org/dhis2/usescases/programstageselection/ProgramStageSelectionPresenterTest.kt
> fix: [ANDROAPP-4536] skip program stage selection if only one

- form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt
- form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt
> fix: [ANDROAPP-4825] keep program rule options

- .tx/config
> build: add maps resource for transifex

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/TableCellUiOptions.kt
- dhis_android_analytics/build.gradle
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/ChartViewHolder.kt
- dhis_android_analytics/src/main/res/layout/item_chart.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4828)
> feat: [ANDROAPP-4828] Use new table UI component for analytics tables

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/SelectionState.kt
> feat: Androapp 4829 rebase

- app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
- app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
- app/src/main/java/org/dhis2/usescases/login/LoginModule.kt
- app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
- commons/src/main/java/org/dhis2/commons/dialogs/CustomDialog.java
> fix: [ANDROAPP-4861] No network message on account recovery

- app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableScreen.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/MapFieldValueToUser.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
- app/src/test/java/org/dhis2/usescases/datasets/TableDataToTableModelMapperTest.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableDialogModel.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/TableDialog.kt
- compose-table/src/main/res/values/strings.xml
> fIX: [ANDROAPP-4793] show dialog for DE description

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4865)
> fix: [ANDROAPP-4865] Show botton navigation bar when sync fails

- app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3915)
> fix: [ANDROAPP-3915] Ask user to enable coordinates in event and relationship maps

- app/build.gradle
- app/src/androidTest/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/FakeTableModels.kt
- app/src/dhisUITesting/assets/mocks/dataset/ds_test_dataset_section_a.json
- app/src/dhisUITesting/assets/mocks/dataset/ds_test_dataset_section_b.json
- build.gradle
- buildsystem/dependencies.gradle
- compose-table/build.gradle
- compose-table/src/androidTest/java/org/dhis2/composetable/model/FakeTableModels.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/ui/DataSetTableUiTest.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt
- compose-table/src/main/assets/multi_header_table_list.json
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4848)
> Androapp-4848 Fake classes for compose ui tests

- scripts/browserstackBitrise.sh
> fix: fix browserstackBitrise.sh

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- commons/src/main/java/org/dhis2/commons/animations/ViewAnimations.kt
[ANDROAPP-3115](https://jira.dhis2.org/browse/ANDROAPP-3115)
> fix: [ANDROAPP-3115] Update on settings animation

- app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
- commons/src/main/java/org/dhis2/commons/animations/ViewAnimations.kt
Reverts dhis2/dhis2-android-capture-app#2822
> Revert "fix: [ANDROAPP-3115] Update on settings animation"

- commons/src/main/java/org/dhis2/commons/filters/DisableHomeFiltersFromSettingsApp.kt
[ANDROAPP-4854](https://jira.dhis2.org/browse/ANDROAPP-4854)
> fix: [ANDROAPP-4854] Sync Filter propagates to home screen.

- compose-table/src/androidTest/java/org/dhis2/composetable/ColumnTableTest.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
> test: [Androapp 4850] Column tests

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/AnalyticResources.kt
- dhis_android_analytics/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4883)
> feat: [ANDROAPP-4883] Add analytics exception resources

- dhis2_android_maps/src/main/java/org/dhis2/maps/managers/EventMapManager.kt
> fix: [ANDROAPP-4863] map navigation button

- app/src/main/java/org/dhis2/data/service/SyncStatusData.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4892)
> fix: [ANDROAPP-4892] Block home programs while data is syncing

- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/data/service/SyncStatusController.kt
- app/src/main/java/org/dhis2/data/service/SyncStatusData.kt
- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainModule.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt
- app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java
- app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
- commons/src/main/java/org/dhis2/commons/animations/ViewAnimations.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4865)
> fix: [ANDROAPP-4865] Hide main activity nav bar only if sync is running

- app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
- form/src/main/java/org/dhis2/form/model/SectionUiModelImpl.kt
- form/src/main/res/layout/form_section.xml
- form/src/test/java/org/dhis2/form/model/section/SectionUiModelTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4726)
> feat: [ANDROAPP-4726] Add next button at the end of form section

- app/src/main/java/org/dhis2/data/service/ReservedValuesWorkerModule.java
- app/src/main/java/org/dhis2/data/service/ServiceModule.java
- app/src/main/java/org/dhis2/data/service/SyncDataWorkerModule.java
- app/src/main/java/org/dhis2/data/service/SyncGranularRxModule.java
- app/src/main/java/org/dhis2/data/service/SyncInitWorkerModule.java
- app/src/main/java/org/dhis2/data/service/SyncMetadataWorkerModule.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/data/service/SyncRepository.kt
- app/src/main/java/org/dhis2/data/service/SyncRepositoryImpl.kt
- app/src/test/java/org/dhis2/data/services/SyncPresenterTest.kt
[ANDROAPP-4841](https://jira.dhis2.org/browse/ANDROAPP-4841)
> fix: [ANDROAPP-4841] TEI granular sync checks enrollment events for sync conflict

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableScreen.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt
> feat: [ANDROAPP-4898] save value when losing focus

- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
- app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstractExtensions.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4884)
> fix: [ANDROAPP-4884] Crash on logout

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/MapFieldValueToUser.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
- app/src/test/java/org/dhis2/composetable/ui/TableDimensionsTest.kt
- app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
- commons/src/main/java/org/dhis2/commons/resources/ResourceManager.kt
- commons/src/main/res/values/strings.xml
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4904)
> fix: [ANDROAPP-4904] Design fixes pair programming

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableScreen.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt
> fix: [ANDROAPP-4905] table design fixes

- app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Improve attribute mapping in TEI transform.
[ANDROSDK-1568](https://jira.dhis2.org/browse/ANDROSDK-1568)
1. The solution get the list of TEI attribute values once. It has a performance impact when the list of values is large.
2. Remove the property "withTrackedEntityAttributeValues()" in the relationship method because they are not used.
> feat: [ANDROSDK-1568] Get initial list of attribute values

- form/src/main/java/org/dhis2/form/ui/validation/FieldErrorMessageProvider.kt
- form/src/main/res/values/strings.xml
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4928)
> feat: [ANDROAPP-4928] Add new validation error messages

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableScreen.kt
- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/test/java/org/dhis2/composetable/TableModelTest.kt
> fix: [ANDROAPP-4857] hide text input when cell doesn't need it

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableScreen.kt
- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
> fix: [ANDROAPP-4856] update error when saving

- buildsystem/dependencies.gradle
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4950)
> ci: [ANDROAPP-4950] Update sentry to version 6.4.1

- compose-table/src/androidTest/java/org/dhis2/composetable/BottomBarTableTests.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/model/FakeTableModels.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/utils/KeyboardHelper.kt
- compose-table/src/main/assets/multi_header_table_list.json
> test: [ANDROAPP-4938] Bottom bar dataset test

- form/src/main/java/org/dhis2/form/ui/validation/FieldErrorMessageProvider.kt
- form/src/main/res/values/strings.xml
- form/src/test/java/org/dhis2/form/ui/validation/FieldErrorMessageProviderTest.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4890)
> fix: [ANDROAPP-4890] update SDK and add new validation exceptions

- build.gradle
> style: Exclude SDK from ktlinCheck

- compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
- compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
- compose-table/src/test/java/org/dhis2/composetable/TableModelTest.kt
> fix: [Androapp 4943] Wrong analytics message with image

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
> fix: [ANDROAPP-4945] crash when render analytics table

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/AnalyticsModel.kt
- dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ui/AnalyticsModelTest.kt
> fix: [ANDROAPP-4946] Pie chart showing overlapping errors

- app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
- app/src/main/java/org/dhis2/data/service/SyncGranularWorker.kt
- app/src/main/java/org/dhis2/data/service/SyncPresenter.java
- app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
- app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt
- app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/org/dhis2/data/services/SyncPresenterTest.kt
- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsFragment.kt
- form/src/main/java/org/dhis2/form/ui/FormView.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4965)
> fix: [ANDROAPP-4965] ANR in home screen after syncing

- app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
- app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
- commons/src/main/java/org/dhis2/commons/matomo/Actions.kt
> feat: track jira report click from home

- app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/MapFieldValueToUser.kt
- app/src/test/java/org/dhis2/usescases/datasets/MapFieldValueToUserTest.kt
> fix: [ANDROAPP-4977] username type as unsupported

- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt
- app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
- app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt
- app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4843)
> Androapp 4843 table espresso and integration testing

- dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/ChartViewHolder.kt
> fix: [ANDROAPP-4972] crash changing visualization type

- compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt
> fix: Fix compose test

- compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt
- compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt
> fix: Fix compose tests

- compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt
Comment non deterministic UI test
> test: Comment shouldClearFocusWhenKeyboardIsHidden UI test
