app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt
=> fix: [ANDROAPP-4983] crash on indicators tables

app/src/test/java/org/dhis2/composetable/ui/TableDimensionsTest.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4982)
=> fix: [ANDROAPP-4982] Incorrect sizing of tables in TEI analytics

app/src/dhisUITesting/assets/mocks/dataset/ds_test_dataset_section_a.json, app/src/dhisUITesting/assets/mocks/dataset/ds_test_dataset_section_b.json, app/src/main/java/org/dhis2/data/forms/dataentry/ValueStore.kt, app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt, app/src/main/res/layout/fragment_dataset_section.xml, app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt, compose-table/src/main/assets/mandatory_cell_table_list.json, compose-table/src/main/assets/multi_header_table_list.json, compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
=> fix: [ANDROAPP-4973] Add progress to table screen initialization

scripts/reviewers.py
=> ci: remove jaime from reviewers.py :(

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt, app/src/test/java/org/dhis2/composetable/ui/TableSelectionTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/ColumnTableTest.kt, compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableSelection.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-ANDROAPP-4984)
=> fix: [ANDROAPP-4984] Inconsistency in row hightlights

scripts/flow_tests_configurator.sh
Change device for flows execution
=> flows_change_device

buildsystem/dependencies.gradle
=> [skip ci] update sdk version to snapshot

buildsystem/dependencies.gradle
=> [skip ci] Updates version code

app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
[ANDROAPP-4994](https://dhis2.atlassian.net/browse/ANDROAPP-4994)
=> fix: [ANDROAPP-4994] Delays create new TEI button positioning when bottom navigation bar is displayed

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
=> fix: [ANDROAPP-4934] Vertical overscroll for some cells

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt, app/src/test/java/org/dhis2/usescases/datasets/TableDataToTableModelMapperTest.kt
=> fix: [ANDROAPP-4998] Block cell edition if access data write is false

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/BottomBarTableTests.kt, compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt, compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt, compose-table/src/main/java/org/dhis2/composetable/TableScreenState.kt, compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt, compose-table/src/test/java/org/dhis2/composetable/TableModelTest.kt
=> fix: [ANDROAPP-4856] Error on cell not working properly

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-b+uz+Cyrl/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-lo/strings.xml, app/src/main/res/values-uz/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryTest.kt, commons/src/main/java/org/dhis2/commons/resources/ResourceManager.kt, commons/src/main/res/values-ar/strings.xml, commons/src/main/res/values-b+uz+Cyrl/strings.xml, commons/src/main/res/values-es/strings.xml, commons/src/main/res/values-lo/strings.xml, commons/src/main/res/values-uz/strings.xml, commons/src/main/res/values-vi/strings.xml, commons/src/main/res/values/strings.xml
=> fix: [ANDROAPP-4991] Set default label for dataset section

app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt, app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
=> fix: [ANDROAPP-5002] Improve message regarding sms syn in home screen

app/src/main/res/layout/item_stage_section.xml
=> fix: [ANDROAPP-4956] program stage name overflow

app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java, app/src/main/java/org/dhis2/utils/customviews/MessageAmountDialog.java
=> fix: [ANDROAPP-5003] Get string from project resources

Jenkinsfile
=> fix: Add Jenkinsfile for multibranch pipeline

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ui/GroupAnalyticsFragment.kt
=> fix: [ANDROAPP-5009] crash accessing lateinit variable in GroupAnalyticsFragment

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt
=> fix: [ANDROAPP-4995] Crash when creating event to tei relationship

app/src/main/java/org/dhis2/data/service/SyncDataWorker.java, app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt, app/src/main/java/org/dhis2/data/service/SyncStatusController.kt, app/src/main/java/org/dhis2/data/service/SyncStatusData.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramUi.kt, app/src/main/res/drawable/ic_perm_media.xml, app/src/main/res/layout/fragment_program.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt, app/src/test/java/org/dhis2/usescases/main/program/ProgramRepositoryImplTest.kt
=> fix: [ANDROAPP-4965] UI freeze while syncing file resources

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
=> fix: [ANDROAPP-4994] show button after pageconfiguration

compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-4856)
=> fix: [ANDROAPP-4856] update error only in current cell

Jenkinsfile
=> test: Jenkinsfile

app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramView.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, commons/src/main/java/org/dhis2/commons/filters/FilterManager.java
=> fix: [ANDROAPP-5010] FilterManager publish data when clearing filters

form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5024)
=> [ANDROAPP-5024] Not delete value when program rule fails.

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt
=> fix: [ANDROAPP-5019] navbar and textinput at same time

form/src/main/java/org/dhis2/form/data/FormRepository.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5017)
=> fix: [ANDROAPP-5017] Close keyboard when capturing or showing QR

app/src/androidTest/java/org/dhis2/usescases/main/program/ProgramUiTest.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramUi.kt, app/src/main/res/values/strings.xml
=> feat: [ANDROAPP-5029] When a program has description show the icon

whatsnew/whatsnew-en-US
=> release: whats new

app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
=> fix: [ANDROAPP-5055] wait for view when changing orientation

app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java, app/src/main/java/org/dhis2/utils/DateUtils.java, app/src/main/java/org/dhis2/utils/customviews/PeriodAdapter.kt, app/src/main/java/org/dhis2/utils/customviews/PeriodDialogInputPeriod.java, app/src/test/java/org/dhis2/usescases/datasets/dataSetInitial/DataSetInitialRepositoryImplTest.kt, app/src/test/java/org/dhis2/utils/DateUtilsTest.java
[ANDROAPP-4957](https://dhis2.atlassian.net/browse/ANDROAPP-4957)
=> fix: [ANDROAPP-4957] Corrects showing of input periods in dialog

app/src/main/res/raw/testing_credentials.json, commons/build.gradle, settings.gradle
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5064)
- [x ] Smartphone Emulator
=> refactor: [ANDROAPP-5064] Remove SDK submodule

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsViewModel.kt, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/EventDetailsIntegrationTest.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-4951)
=> [ANDROAPP-4951] Load event details synchronously

app/src/main/java/org/dhis2/Bindings/StringExtensions.kt, app/src/main/java/org/dhis2/utils/DateUtils.java, app/src/test/java/org/dhis2/utils/DateUtilsTest.java
=> fix: [ANDROAPP-5027] Add millis format to date parser

app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/data/RuleUtilsProviderResult.kt, form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
=> fix: [ANDROAPP-5053] Clear cached values for program rules

form/src/main/java/org/dhis2/form/ui/dialog/OptionSetDialogUi.kt
=> fix: [ANDROAPP-5041] long options container

form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: add idling resource

buildsystem/dependencies.gradle
=> chore: Updates sdk version

app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
=> fix: [ANDROAPP-5007] hide sync button in all enrollments screen

commons/src/main/res/values/themes.xml
=> fix: [ANDROAPP-5056] RTL on titles

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
=> fix: [ANDROAPP-5033] keyboard cut on search

app/build.gradle, build.gradle
[ANDROAPP-5066](https://dhis2.atlassian.net/browse/ANDROAPP-5066)
=> chore: [ANDROAPP-5066] Removes more dependencies from jcenter

app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
=> feat: [ANDROAPP-5085] track event QR share

form/src/main/java/org/dhis2/form/data/FormRepository.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: [ANDROAPP-5053] Treat empty string as null value in forms

Jenkinsfile
=> ci: [ANDROAPP-5059] testing pr jenkins job

app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
=> feat: [ANDROAPP-5007] remove sync icon on landscape

app/src/main/java/org/dhis2/usescases/settings/SyncManagerContracts.java, app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java, app/src/main/java/org/dhis2/usescases/settings/SyncManagerModule.java, app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/layout/settings_sms.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/settings/SyncManagerPresenterTest.kt
[ANDROAPP-4940](https://dhis2.atlassian.net/browse/ANDROAPP-4940)
=> fix: [ANDROAPP-4940] Gateway number is needed to enable sms module

app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramRepository.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt
=> fix: [ANDROAPP-5099] Sync ico not displayed when coming back from event program

app/src/test/java/org/dhis2/composetable/ui/TableDimensionsTest.kt, compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt
=> fix: [ANDROAPP-5018] add horizontal padding in cells

app/src/main/java/org/dhis2/Bindings/DialFloatingActionButtonExtensions.kt, buildsystem/dependencies.gradle, compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
=> fix: [ANDROAPP-5020] use bringIntoView for smooth scroll

build.gradle, buildsystem/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties
=> fix: [ANDROAPP-5093] crash rotating screen

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
=> fix: scroll dimensions

app/src/main/assets/paperwork.json, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt, compose-table/src/main/java/org/dhis2/composetable/TableScreenState.kt, compose-table/src/main/java/org/dhis2/composetable/actions/TableInteractions.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
=> feat: [ANDROAPP-5133] Save row header width per dataset and section

Jenkinsfile
=> build: removing jenkins notifications of PRs

dhis2_android_maps/src/main/java/org/dhis2/maps/layer/LayerConstants.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/layer/basemaps/BaseMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/layer/basemaps/BaseMapStyle.kt
=> fix: [ANDROAPP-5061] add glyphs to render text in maps symbol layers

app/src/main/java/org/dhis2/utils/session/PinDialog.kt, app/src/main/res/values/strings.xml
=> fix: [ANDROAPP-5137] logout on 3 pin wrong attempts

form/src/main/java/org/dhis2/form/ui/LayoutProviderImpl.kt
[ANDROAPP-3370](https://dhis2.atlassian.net/browse/ANDROAPP-3370)
[ANDROAPP-3370]: https://dhis2.atlassian.net/browse/ANDROAPP-3370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: [ANDROAPP-3370] Enables options set to every supported value type field

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt, form/src/main/java/org/dhis2/form/ui/provider/HintProviderImpl.kt
=> feat: allow content on table bottom

form/src/main/java/org/dhis2/form/ui/binding/OptionSetSpinnerBindings.kt, form/src/main/res/layout/form_option_set_spinner.xml
=> fix: [ANDROOAPP-5149] dropdown size on label

form/src/main/java/org/dhis2/form/ui/dialog/OptionSetDialogUi.kt, form/src/main/res/values/strings.xml
=> fix: [ANDROOAPP-5150] dropdown progress when search

app/src/debug/AndroidManifest.xml, app/src/main/AndroidManifest.xml, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt, app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
=> fix: [ANDROAPP-5171] Opens schedule activity when autogenerating a schedule event from an enrollment

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
=> fix: [ANDROAPP-5171] Opens dashboard after saving a schedule or skipped event

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt, app/src/main/res/layout/item_stage_section.xml
=> feat: [ANDROAPP-5080] Enable marquee for program stage names in TEI dashboard

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> fix_dataset_test

.tx/config
Adding stock use case to transifex for translations
=> Add stock-usecase to transifex

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/model/DataEntryUiState.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5204)
=> [ANDROAPP-5204] Add EDITING_REVIEWING step

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
=> fix: [ANDROAPP-5194] crash when event is overdue

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5205)
=> [ANDROAPP-5205] Remove discard dialog on back

app/src/androidTest/java/org/dhis2/usescases/pin/PinTest.kt, app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java, app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt, app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt, app/src/main/java/org/dhis2/usescases/main/HomeRepository.kt, app/src/main/java/org/dhis2/usescases/main/HomeRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt, app/src/main/java/org/dhis2/utils/session/PinDialog.kt, app/src/main/java/org/dhis2/utils/session/PinModule.kt, app/src/main/java/org/dhis2/utils/session/PinPresenter.kt, app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt, app/src/test/java/org/dhis2/utils/session/PinPresenterTest.kt
=> fix: [ANDROAPP-5134] support pin with multiaccount

compose-table/src/main/java/org/dhis2/composetable/model/ItemHeaderUiState.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt
=> fix: [ANDROAPP-5153] all items and parent header resize

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/TableModelMapper.kt
=> fix: Set final row in mapper

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5218
- [x ] Smartphone Emulator
- [x ] 11.X - 13.X
- [ x] My code follows the style guidelines of this project
=> [ANDROAPP-5218] Changing durationof the snackBar

app/src/main/res/layout/item_stage_section.xml, form/src/main/res/layout/form_section.xml
=> fix: [ANDROAPP-5080] allow 3 lines max on stage and section

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5116)
=> [ANDROAPP-5116] Replace icons

app/src/androidTest/java/org/dhis2/usescases/settings/SettingsRobot.kt, app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java, app/src/main/java/org/dhis2/usescases/settings/SyncManagerModule.java, app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java, app/src/main/java/org/dhis2/usescases/settings/bindings/SyncManagerBindings.kt, app/src/main/java/org/dhis2/usescases/settings/models/SyncButtonUIModel.kt, app/src/main/res/layout/fragment_settings.xml, app/src/test/java/org/dhis2/usescases/settings/SyncManagerPresenterTest.kt, ui-components/src/main/java/org/dhis2/ui/buttons/TextButton.kt, ui-components/src/main/java/org/dhis2/ui/model/ButtonUiModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5032)
=> [ANDROAPP-5032] [Offline] When working offline the sync button do nothing nor display a message

form/src/main/java/org/dhis2/form/ui/provider/UiEventTypesProviderImpl.kt
=> fix: [ANDROAPP-4623] coordinates render type

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5216
- [ x] Smartphone Emulator
- [x ] 11.X - 13.X
- [ x] My code follows the style guidelines of this project
=> Changing the status, after clear the data

app/src/main/java/org/dhis2/data/server/ServerModule.kt, app/src/main/java/org/dhis2/usescases/login/accounts/ui/AccountsScreen.kt, commons/src/main/java/org/dhis2/commons/Constants.java, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
=> fix: Restore null max account

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, app/src/main/java/org/dhis2/usescases/development/TableTestActivity.kt, compose-table/src/androidTest/java/org/dhis2/composetable/RowTableTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt
=> remove_oncellvaluechange

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardProgramModel.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/DashboardProgramAdapter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/DashboardProgramViewHolder.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListAdapter.java
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-4853)
=> [ANDROAPP-4853] check active enrollments

compose-table/src/main/java/org/dhis2/composetable/model/TextInputModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt
=> [ANDROAPP-5243] set clearable button optional

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
=> feat: [ANDROAPP-5012] display loading on map

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt
Unable to scroll through item list
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5213
Calculate the width and set the new value for the heights
- [ x] Smartphone Emulator
- [ x] 11.X - 13.X
- [ x] My code follows the style guidelines of this project
=> Adding Logic to Scroll the table.

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
=> fix: [ANDROAPP-5220] Concurrent modification crash

ui-components/src/main/java/org/dhis2/ui/dialogs/bottomsheet/BottomSheetDialogContent.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5058)
=> [ANDROAPP-5058] Center title and capitalize buttons

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/DropdownComponents.kt
=> update icon with ui sate

app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt, form/src/main/java/org/dhis2/form/data/FormValueStore.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: [ANDROAPP-5207] Crash when saving missing/wrong file

app/src/main/java/org/dhis2/data/forms/dataentry/ValueStore.kt, app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/main/java/org/dhis2/usescases/development/TableTestActivity.kt, app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt, compose-table/src/main/java/org/dhis2/composetable/TableScreenState.kt, compose-table/src/main/java/org/dhis2/composetable/actions/Validator.kt, compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/main/java/org/dhis2/composetable/model/ValidationResult.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableTheme.kt, dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/TableModelMapper.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt
=> fix: [ANDROAPP-5130] Consecutive clicks can be skipped in table data entry

app/src/test/java/org/dhis2/data/filter/FilterRepositoryTest.kt, app/src/test/java/org/dhis2/utils/filters/workingLists/ProgramStageToWorkingListItemMapperTest.kt, app/src/test/java/org/dhis2/utils/filters/workingLists/WorkingListItemTest.kt, commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt, commons/src/main/java/org/dhis2/commons/filters/di/FilterModule.kt, commons/src/main/java/org/dhis2/commons/filters/workingLists/EventFilterToWorkingListItemMapper.kt, commons/src/main/java/org/dhis2/commons/filters/workingLists/ProgramStageToWorkingListItemMapper.kt, commons/src/main/java/org/dhis2/commons/filters/workingLists/TeiFilterToWorkingListItemMapper.kt, commons/src/main/java/org/dhis2/commons/filters/workingLists/WorkingListItem.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-740)
=> [ANDROAPP-740] Add programStage filters to working lists

app/src/androidTest/java/org/dhis2/common/filters/FiltersRobot.kt, app/src/androidTest/java/org/dhis2/usescases/filters/FilterTest.kt, app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt, app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeRepositoryTest.kt, app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeViewModelTest.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeRepository.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModel.kt, ui-components/src/main/java/org/dhis2/ui/dialogs/orgunit/OrgUnitSelectorDialog.kt
=> fix: fix form test flow

app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
=> fix: fix tests

compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt
=> fix: Increase tappable area in text input

form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: [ANDROAPP-5207] do not clear error on focus change for option sets

form/src/main/java/org/dhis2/form/ui/FormView.kt
=> fix: do not open phone/mail app if value is empty or null

app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
=> Ignore mocker server tests

app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt, app/src/dhisUITesting/assets/mocks/settingswebapp/infosettings_404.json, app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, scripts/browserstackJenkins.sh, scripts/config_jenkins.init
=> fix: missing mock response in login test mock server

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/TableModelMapper.kt
=> Androapp 5280

app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt, form/src/main/java/org/dhis2/form/data/FormValueStore.kt
=> fix: do not try to save image if option set is not null

app/src/main/java/org/dhis2/utils/granularsync/GranularSyncRepository.kt
=> fix: Removes last sync inf from thew sync dialog until sdk provides it

commons/src/main/res/values/themes.xml
=> fix: [ANDROAPP-5274] outline color on cards

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5272)
=> [ANDROAPP-5272] LMIS handling back navigation

compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt, compose-table/src/test/java/org/dhis2/composetable/TableModelTest.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5281)
=> [ANDROAPP-5281] Avoid crash on cell on next when error

app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenter.kt
=> fix: [ANDROAPP-5295] Granular sync dialog not displaying when no errors

form/src/main/java/org/dhis2/form/data/DataEntryBaseRepository.kt, form/src/main/java/org/dhis2/form/data/EnrollmentRepository.kt, form/src/main/java/org/dhis2/form/data/EventRepository.kt
=> fix: [ANDROAPP-5279] Warnings on form should be orange

ui-components/src/main/java/org/dhis2/ui/icons/LoadingIcon.kt
=> fix: [ANDROAPP-5276] Fix sync loading color

stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockManagerImpl.kt
=> fix: [ANDROAPP-5285] Missing transactions

form/src/main/res/layout/form_check_button.xml, form/src/main/res/layout/form_radio_button.xml
=> fix: [ANDROAPP-5302] yes/no vertical height

commons/src/main/res/layout/item_filter_assigned.xml, commons/src/main/res/layout/item_filter_followup.xml, commons/src/main/res/values/styles.xml
=> fix: [ANDROAPP-5300] switch style

app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
=> fix: [ANDROAPP-5296]: return to login when there is an error

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt, app/src/main/java/org/dhis2/usescases/enrollment/TeiInfo.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/enrollment/TeiInfoTest.kt, commons/src/main/java/org/dhis2/commons/bindings/SdkExtensions.kt
=> fix: [ANDROAPP-5247] Set default enrollment toolbar title

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
=> fixing ANDROAPP-5311 (Unable to delete value from "Quantity" field)

form/build.gradle, form/src/main/AndroidManifest.xml, form/src/main/java/org/dhis2/form/data/FormProvider.kt, form/src/main/res/xml/file_paths.xml
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5313)
=> [ANDROAPP-5313] Crash when adding image in form

app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeRepositoryTest.kt, commons/src/main/java/org/dhis2/commons/bindings/CommonExtensions.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OURepositoryConfiguration.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeFragment.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeModule.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeRepository.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModel.kt
=> fix: [ANDROAPP-5297] App allows new enrollment in forbidden OU

app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java, app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
=> fix: [ANDROAPP-5308] program theme through sync flow

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt
=> fix: [ANDROAPP-5262] mandatory icon

form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5207)
- [] Tablet
=> [ANDROAPP-5207] validate image and file valuetypes

app/src/dhis/AndroidManifest.xml, app/src/main/AndroidManifest.xml, app/src/main/java/org/dhis2/data/service/VersionRepository.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
5315
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5315)
=> [ANDROAPP-5315] Exclude App distribution feature from Google Play flavour

app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java, app/src/main/java/org/dhis2/usescases/main/program/StockManagementMapper.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java, app/src/main/java/org/dhis2/utils/granularsync/GranularSyncRepository.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialogNavigator.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialogProvider.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncUiState.kt, commons/src/main/java/org/dhis2/commons/bindings/SdkExtensions.kt, commons/src/main/java/org/dhis2/commons/bindings/SdkModelsExtensions.kt, commons/src/main/java/org/dhis2/commons/sync/OnSyncNavigationListener.kt, commons/src/main/java/org/dhis2/commons/sync/SyncComponentProvider.kt, commons/src/main/java/org/dhis2/commons/sync/SyncDialog.kt, commons/src/main/java/org/dhis2/commons/sync/SyncStatusItem.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt
=> fix: [ANDROAPP-5289] Block backdoor to tracker dashboard from stock managment flow

compose-table/src/main/java/org/dhis2/composetable/model/TextInputModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TextInputUi.kt
=> fix: [ANDROAPP-5260] cursor position on table input

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/FixedStickyHeader.kt
=> fix: [ANDROAPP-5164] Disables sticker header when keyboard is open

app/src/main/java/org/dhis2/Bindings/StringExtensions.kt, app/src/main/java/org/dhis2/data/service/VersionRepository.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt, app/src/test/java/org/dhis2/bindings/StringExtensionsTest.kt
=> fix: [ANDROAPP-3288] version dialog displaying in home

app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
=> chore: Ignores tests for further investigation

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5314)
=> [ANDROAPP-5314] Under review label is not visible when list is long

app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt
=> fix: [ANDROAPP-5317] set credentials on logout

app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
=> fix: updates login test with recent changes in the API calls.

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiAttributesProvider.kt, app/src/test/java/org/dhis2/usescases/enrollment/TeiAttributesInfoTest.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/TeiAttributesProviderTest.kt, commons/src/main/java/org/dhis2/commons/data/TeiAttributesInfo.kt
=> fix: [ANDROAPP-5247] Shows tei attributes in tei dashboard if there are any o tei type details otherwise.

compose-table/src/main/java/org/dhis2/composetable/model/ItemHeaderUiState.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt
=> fix: [ANDROAPP-5249] column resizing use

app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt, commons/src/main/java/org/dhis2/commons/bindings/ValueTypeFormatter.kt, form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt
=> fix: [ANDROAPP-5306] Format rule engine result before assigning

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.kt
=> fix: [ANDROAPP-5325] dataset section duplicated

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, compose-table/src/androidTest/java/org/dhis2/composetable/BottomBarTableTests.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableUi.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt
=> fix: [ANDROAPP-5322] last column resize icon

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.kt
=> fix: [ANDROAPP-5325] do not relaunch sections

form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5336)
=> [ANDROAPP-5336] skip validation for images and files

app/src/main/res/layout/dial_fab_item.xml
=> fix: [ANDROAPP-5337] dial fab icon click

form/src/main/java/org/dhis2/form/ui/FormView.kt
=> fix: [ANDROAPP-5338] close keyboard on value action

app/src/main/AndroidManifest.xml, form/src/main/java/org/dhis2/form/ui/FormView.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5431)
=> [ANDROAPP-5341] Update media file permission request for Android 13

dependencies.gradle
=> update SDK to 1.8.0

form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt
=> fix: [ANDROAPP-5338] do not get focus on value action

form/src/main/res/xml/file_paths.xml
=> Crash when adding QR codes

app/src/debug/AndroidManifest.xml, app/src/dhis/AndroidManifest.xml, app/src/main/AndroidManifest.xml, app/src/main/res/xml/data_extraction_rules.xml, app/src/main/res/xml/old_backup_config.xml, dhis2_android_maps/src/main/AndroidManifest.xml, dhis_android_analytics/src/main/AndroidManifest.xml, ui-components/src/main/AndroidManifest.xml
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5352)
=> [ANDROAPP-5352] Clear manifests

compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt
=>  test: fix compose test

app/src/main/java/org/dhis2/usescases/troubleshooting/TroubleshootingRepository.kt, app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt, dependencies.gradle, form/src/main/java/org/dhis2/form/bindings/RuleExtensions.kt, form/src/main/java/org/dhis2/form/data/RulesRepository.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/rules/RuleValidationHelperImpl.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/utils/RuleExtensions.kt, stock-usecase/src/test/java/org/dhis2/android/rtsm/services/ProgramRuleTests.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5355)
=> [ANDROAPP-5355] Update rule engine to 2.1.7

Jenkinsfile
=> chore: [ANDROAPP-5357] Adds steps to run unit test on all modules

app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.java, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt
=> Androapp 5361 android capture tracker infinite loading for program stage

dependencies.gradle
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5365)
=> ANDROAPP-5365-update-rule-engine-to-2-1-8

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt
=> fix: [ANDROAPP-5018] Row header cell wraps 3 lines and then ellipsized text

app/src/main/java/org/dhis2/usescases/searchTrackEntity/EnrollmentContract.kt
=> fix: [ANDROAPP-5359] remove unused enrollmentUid variable

commons/src/main/java/org/dhis2/commons/bindings/ValueTypeFormatter.kt, form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt
=> fix: [ANDROAPP-5358] avoid formatting of incorrect value type

dependencies.gradle
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5371)
=> ANDROAPP-5371 update sdk to 1.8.2

app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialogNavigator.kt
=> fix: [ANDROAPP-5343] sync flow backwards

compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt, compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt
=> test: fix ignored test

app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
=> fix: [ANDROAPP-5255] Hide loading progress bar when loading all program enrollments of a TEI

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchNavigator.kt
=> fix: [ANDROAPP-5323] define getter for activity launchers

Jenkinsfile, app/build.gradle, app/src/main/java/org/dhis2/data/fingerprint/FingerPrintController.kt, app/src/main/java/org/dhis2/data/fingerprint/FingerPrintControllerImpl.kt, app/src/main/java/org/dhis2/data/fingerprint/FingerPrintMapper.kt, app/src/main/java/org/dhis2/data/fingerprint/FingerPrintModule.kt, app/src/main/java/org/dhis2/data/fingerprint/FingerPrintResult.kt, app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt, app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt, app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/main/res/layout/fragment_jira.xml, app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt, build.gradle, commons/build.gradle, commons/src/main/java/org/dhis2/commons/prefs/PreferenceProviderImpl.kt, dependencies.gradle
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5386)
=> [ANDROAPP-5386] Remove securestoragelibrary

app/src/main/java/org/dhis2/usescases/searchTrackEntity/LegacyInteraction.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTeiViewModelFactory.kt, app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
=> fix: [ANDROAPP-5380] ViewModel preserving destroyed activity reference

form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/event/RecyclerViewUiEvents.kt, form/src/main/java/org/dhis2/form/ui/event/UiEventFactoryImpl.kt, form/src/main/java/org/dhis2/form/ui/intent/FormIntent.kt, form/src/test/java/org/dhis2/form/ui/FormViewModelTest.kt
=> fix: [ANDROAPP-5342] actions with current value

commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeRepository.kt
=> fix: [ANDROAPP-5368] org units tree

scripts/pre-commit_unix.sample, scripts/pre-commit_windows.sample
=> chore: updates pre-commit hook script to check all modules of project

app/src/main/java/org/dhis2/utils/granularsync/GranularSyncRepository.kt
=> fix: [ANDROAPP-5363] Wrong label displayed while navigating an error or warning

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, form/src/main/java/org/dhis2/form/data/RulesUtilsProviderImpl.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5395)
=> ANDROAPP-5395 Improve reliability analyisis

commons/src/main/java/org/dhis2/commons/utils/OrgUnitHolder_2.java
=> Replace & by &&

app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt, app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/test/java/org/dhis2/usescases/login/LoginViewModelTest.kt
=> fix: [ANDROAPP-5376 ] Login button doesn't work and doesn't present any error

commons/src/main/java/org/dhis2/commons/filters/data/FilterRepository.kt, commons/src/main/java/org/dhis2/commons/filters/data/TrackerFilterSearchHelper.kt
=> fix: [ANDROAPP-5385] event filters

app/src/test/java/org/dhis2/composetable/ui/TableSelectionTest.kt, compose-table/src/main/java/org/dhis2/composetable/ui/Table.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableSelection.kt
=> fix: [ANDROAPP-5329] correctly scrolls automatically to selected cell

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/SyncFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
=> fix: ANDROAPP-4443 [Espresso] Review shouldSuccessfullySyncAChangedTEI Test

app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
=> fix: ANDROAPP-4508 [Espresso] Review shouldApplyHideProgramStage

commons/src/main/java/org/dhis2/commons/filters/FilterManager.java
=> fix: [ANDROAPP-5401] do not load status filters if not changing

app/src/main/res/layout/item_dashboard_program.xml
=> fix: [ANDROAPP-5334] incident date visibility

build.gradle.kts
=> [ANDROAPP-5411] remove autonomus apps dependencies

app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeRepositoryTest.kt, app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeViewModelTest.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OURepositoryConfiguration.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeRepository.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModel.kt
=> refactor: [ANDROAPP-5368] optimize orgUnit tree

ui-components/build.gradle.kts
=> fix: [ANDROAPP-5375] support vector drawable in ui module

commons/src/main/java/org/dhis2/commons/extensions/ViewExtensions.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5403)
=> [ANDROAPP-5403] post closeKeyboard

compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
=> fix: [ANDROAPP-5330] deleting values in stock use case

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, commons/src/main/java/org/dhis2/commons/bindings/ValueExtensions.kt, form/src/main/java/org/dhis2/form/data/FormValueStore.kt, form/src/main/java/org/dhis2/form/data/metadata/FileResourceConfiguration.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/binding/PictureBindings.kt, form/src/main/java/org/dhis2/form/ui/provider/DisplayNameProviderImpl.kt, form/src/test/java/org/dhis2/form/data/metadata/FileResourceConfigurationTest.kt, form/src/test/java/org/dhis2/form/ui/provider/DisplayNameProviderImplTest.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5340)
=> [ANDROAPP-5340] parse resource value uid to patch before rendering

app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt, commons/src/main/java/org/dhis2/commons/reporting/CrashReportController.kt, commons/src/main/java/org/dhis2/commons/reporting/CrashReportControllerImpl.kt
=> [ANDROAPP-5423] Send server version to sentry

compose-table/src/main/java/org/dhis2/composetable/TableScreenState.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockTableDimensionStore.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/TableModelMapper.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt, stock-usecase/src/test/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModelTest.kt
=> [ANDROAPP-5384] Persist dataset column size when adjusted by the user

form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: [ANDROAPP-5348] compose fields before finish

app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt, app/src/test/java/org/dhis2/bindings/TEICardExtensionsTest.kt, commons/src/main/java/org/dhis2/commons/bindings/TEICardExtensions.kt, commons/src/main/java/org/dhis2/commons/data/EnrollmentIconData.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselTeiHolder.kt, ui-components/src/main/java/org/dhis2/ui/MetadataIcon.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5377
=> fix: [ANDROAPP-5377 ] A TEI enrolled in many programs display to many icons blocking the TEI info card

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepositoryTest.kt, app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt, commons/src/main/java/org/dhis2/commons/resources/D2ErrorUtils.kt, commons/src/main/java/org/dhis2/commons/resources/ResourceManager.kt, commons/src/main/res/values/strings.xml
=> [ANDROAPP-5396] string error updated

scripts/readReleaseInfo.py
=> Update release jobs

compose-table/src/main/java/org/dhis2/composetable/ui/CellStyle.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableColors.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt
=> fix: [ANDROAPP-5384] keep table when action changes

app/src/main/java/org/dhis2/Bindings/ValidationStrategyExtensions.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventIntegrationTest.kt
=> fix: [ANDROAPP-4710] Mandatory fields in validation strategy check

stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
=> fix: [ANDROAPP-5384] refresh config after resize

app/src/main/java/org/dhis2/utils/analytics/AnalyticsInterceptor.kt
=> fix: [ANDROAPP-5463] wrong credentials error

gradle/libs.versions.toml
=> [ANDROAPP-5424] Update rule engine

app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, app/src/main/res/values/strings.xml
=> fix: [ANDROAPP-5452] Notifications not displayed on android 13

app/build.gradle.kts, app/src/debug/AndroidManifest.xml, app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java, app/src/main/java/org/dhis2/usescases/development/UIComponentsView.kt, app/src/main/res/layout/development_activity.xml, build.gradle.kts, gradle/libs.versions.toml
Add section in development Activity to show UI components
=> Test UI components

app/src/main/java/org/dhis2/usescases/development/UIComponentsView.kt
=> Remove inputshell

ui-components/src/main/java/org/dhis2/ui/dialogs/orgunit/OrgUnitTreeItem.kt
=> Remove the "(1)" text from last level orgunit in the OrgUnit selector dialog

app/build.gradle.kts, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.kt, commons/build.gradle.kts, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/main/java/org/dhis2/form/model/FormSection.kt, form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
=> Androapp 5151 form display program stage section description

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
=> ANDROAPP-5539 Use displayFormName in validation dialog

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt, dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/data/GraphTest.kt
=> ANDROAPP-5546 Fix crash in charts

app/build.gradle.kts
=> fix: [ANDROAPP-5501] fix sdk version appearing on about screen

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/main/java/org/dhis2/form/extensions/SupportingTextExtensions.kt, form/src/main/java/org/dhis2/form/model/FormSection.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/provider/FieldProvider.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt
ANDROAPP-5553, ANDROAPP-5554, ANDROAPP-5555, ANDROAPP-5552, ANDROAPP-5551, ANDROAPP-5550, ANDROAPP-5549, ANDROAPP-5548
=> Add inputs to compose form

app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java, app/src/main/res/layout/fragment_settings.xml
=> make sure setting item visible when selected

app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockManagerImpl.kt
=> ANDROAPP-5148 - fix single program screen opening twice

app/src/main/res/layout/fragment_program_event_detail_map.xml, app/src/main/res/layout/fragment_relationships.xml, app/src/main/res/layout/fragment_search_map.xml, dhis2_android_maps/src/main/java/org/dhis2/maps/attribution/AttributionManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/camera/CameraExtension.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/extensions/MapExtensions.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt, dhis2_android_maps/src/main/res/values/strings.xml, gradle/libs.versions.toml
=> Androapp-5489-[Maps]-Black-screen

form/src/main/java/org/dhis2/form/data/EventRepository.kt
=> fix: [ANDROAPP-5151] displays section's description

app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
=> ANDROAPP-5525 Ask for permission to save file

app/src/main/AndroidManifest.xml, form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/CheckBoxProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/RadioButtonProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/SwicthProvider.kt
=> feat: [ANDROAPP-5595] improve scrolling in forms

app/src/test/java/org/dhis2/composetable/ui/TableDimensionsTest.kt, compose-table/src/main/java/org/dhis2/composetable/model/TableCornerUiState.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataTable.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableCorner.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableItemRow.kt
=> feat: [ANDROAPP-5250] resizing in single value tables

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> Androapp-5580-implement-input-email 

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> ANDROAPP-5566-Implement-InputPhoneNumber

form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> ANDROAPP-5583-Implement-InputLink

form/src/main/java/org/dhis2/form/ui/Form.kt
=> fix: [ANDROAPP-5393] scroll when changing section

app/src/main/java/org/dhis2/usescases/teiDashboard/ui/NewEventOptionsMenu.kt, app/src/main/res/layout/item_stage_section.xml
=> feat:[ANDROAPP-5599] change new event button

app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt, app/src/main/res/values/strings.xml
=> feat: [ANDROAPP-5618] dismiss on sync success

commons/src/main/res/values/themes.xml
=> fix: [ANDROAPP-5638] card borders

form/src/main/java/org/dhis2/form/ui/dialog/QRDetailBottomDialog.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputsForTextValueTypeProvider.kt, form/src/main/res/values/strings.xml
=> implement BarCode component

form/src/main/java/org/dhis2/form/ui/provider/inputfield/DropdownProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> fix: [ANDROAPP-5622] implement input dropdown

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/test/java/org/dhis2/utils/optionset/OptionSetPresenterTest.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/main/java/org/dhis2/form/extensions/FieldUiModelExtensions.kt, form/src/main/java/org/dhis2/form/model/FieldUiModel.kt, form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt, form/src/main/java/org/dhis2/form/model/SectionUiModelImpl.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactory.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt, form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/FormViewModelFactory.kt, form/src/main/java/org/dhis2/form/ui/provider/AutoCompleteProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/AutoCompleteProviderImpl.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputsForTextValueTypeProvider.kt, form/src/test/java/org/dhis2/form/data/FieldUiModelTest.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt, form/src/test/java/org/dhis2/form/data/RulesUtilsProviderImplTest.kt, form/src/test/java/org/dhis2/form/ui/FieldViewModelFactoryImplTest.kt, form/src/test/java/org/dhis2/form/ui/FormViewModelTest.kt, form/src/test/java/org/dhis2/form/ui/event/UiEventFactoryImplTest.kt, gradle/libs.versions.toml
=> feat: [ANDROAPP-5625] Implement Autocomplete input type

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, gradle/libs.versions.toml
=> ANDROAPP-5581-Implement-InputOrgUnit

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputFileProvider.kt, gradle/libs.versions.toml
=> Androapp 5584 implement input file resource

form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/SignatureProvider.kt
=> feat: [ANDROAPP-5624] implement InputSignature

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/UnitIntervalInputProvider.kt
=> Initial commit

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/ImageInputProvider.kt
=> Androapp 5587 implement input image

form/src/main/java/org/dhis2/form/ui/provider/inputfield/CoordinatesProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> feat: [ANDROAPP-5616] implement input polygon

gradle/libs.versions.toml
Update sdk version to 1.9.0-SNAPSHOT-59
=> Update to DHIS2 SDK 1.9.0-59

gradle/libs.versions.toml
=> build: change development name

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt, commons/src/main/java/org/dhis2/commons/bindings/TEICardExtensions.kt
=> fix: [ANDROAPP-5646] handle online TEIs mapping

gradle/libs.versions.toml
=> fix: [ANDROAPP-5550] long text bottom line

app/src/main/AndroidManifest.xml, app/src/main/java/org/dhis2/data/service/SyncDataWorker.java, app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
=> fix: [ANDROAPP-5654] foregroundService on API 34

form/src/main/java/org/dhis2/form/model/UiRenderType.kt, form/src/main/java/org/dhis2/form/ui/dialog/QRDetailBottomDialog.kt, form/src/main/java/org/dhis2/form/ui/provider/UiEventTypesProviderImpl.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputsForTextValueTypeProvider.kt, gradle/libs.versions.toml
=> feat: [ANDROAPP-5626] implement gs1 component

form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: [ANDROAPP-5625]  fix autocomplete style

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
=> fix: [ANDROAPP-5318] Table cells randomly deleting previously saved values

form/src/main/java/org/dhis2/form/ui/provider/inputfield/MatrixInputProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/SequentialInputProvider.kt
=> fix: ANDROAPP-5563 Input Matrix and Sequential corrections

form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> feat: [ANDROAPP-5670] not supported field

app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/TeiDetailDashboard.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt, app/src/main/res/layout-land/activity_dashboard_mobile.xml, app/src/test/java/org/dhis2/usescases/teiDashboard/ui/mapper/TEIDetailMapperTest.kt
=> fix: [ANDROAPP-4019] Tei Dashboard detail card

form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/CheckBoxProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/CoordinatesProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/RadioButtonProvider.kt
=> fix: [ANDROAPP-5689] form focus

form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/ImageInputProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/SignatureProvider.kt
=> fix: [ANDROAPP-5659] Null pointer exception trying to view image from gallery

form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputFileProvider.kt
=> fix name overload for CI 

gradle/libs.versions.toml
=> feat: Update SDK to snapshot 1.9.0-66

app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt, app/src/main/java/org/dhis2/usescases/events/ScheduledEventActivity.kt, app/src/main/java/org/dhis2/usescases/events/ScheduledEventContract.kt, app/src/main/java/org/dhis2/usescases/events/ScheduledEventPresenterImpl.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/InputFieldsProvider.kt, app/src/main/res/layout/activity_event_scheduled.xml, gradle/libs.versions.toml
=> feat: [ANDROAPP-5709] Implement new Components in ScheduledEventActivity.

app/src/main/java/org/dhis2/data/service/SyncStatusController.kt, app/src/main/java/org/dhis2/data/service/SyncStatusData.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
=> fix: [ANDROAPP-5627] fix double navigation to view on single program servers

form/src/main/java/org/dhis2/form/ui/Form.kt
=> fix: [ANDROAPP-5596] form padding

form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/DateProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputsForTextValueTypeProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/UnitIntervalInputProvider.kt
=> fix: [ANDROAPP-5729] move to next section from last field focus

form/src/main/java/org/dhis2/form/ui/validation/FieldErrorMessageProvider.kt, form/src/main/res/values/strings.xml
=> ANDROAPP-5708-Error-message-for-Yes-No-field-is-incorrect

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
=> fix: [ANDROAPP-5723] hide program stages with HideProgramStage rule

app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt
=> fix: [ANDROAPP-4019] Filter image valueType trackedEntityAttribute from title

form/src/main/java/org/dhis2/form/ui/Form.kt
=> fix: [ANDROAPP-5689] next section scroll

commons/src/main/java/org/dhis2/commons/filters/workingLists/WorkingListChipGroup.kt
=> fix: [ANDROAPP-5713] Workinglist chip persist selection

app/src/main/java/org/dhis2/data/service/SyncStatusController.kt, app/src/main/java/org/dhis2/data/service/SyncStatusData.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
=> fix: ANDROAPP-5627 double  navigation on single program servers

app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt, commons/src/main/java/org/dhis2/commons/data/SearchTeiModel.java
=> fix: [ANDROAPP-4019] Tei's enrolled programs list on Tei Card list and Tei Dashboard

app/src/main/java/org/dhis2/utils/customviews/BreakTheGlassBottomDialog.kt, commons/src/main/java/org/dhis2/commons/data/SearchTeiModel.java
=> fix: [ANDROAPP-5756] Fix search outside program crash

app/src/main/res/values-es/strings.xml, compose-table/src/main/java/org/dhis2/composetable/ui/DataTable.kt
=> fix: [ANDROAPP-5719] empty table crash

RELEASE.md, gradle/libs.versions.toml, whatsnew/whatsnew-en-US
=> build: 2.9 release

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java, form/src/main/java/org/dhis2/form/data/EnrollmentRepository.kt, form/src/main/java/org/dhis2/form/model/FieldUiModel.kt, form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt, form/src/main/java/org/dhis2/form/model/SectionUiModelImpl.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactory.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/event/RecyclerViewUiEvents.kt, form/src/main/java/org/dhis2/form/ui/event/UiEventFactoryImpl.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> fix: [ANDROAPP-5700] add orgUnit scope in enrollment

app/src/test/java/org/dhis2/utils/filters/FilterManagerTest.kt, commons/src/main/java/org/dhis2/commons/filters/FilterManager.java
=> fix: [ANDROAPP-5606] working list filter count

commons/src/main/java/org/dhis2/commons/bindings/FileExtensions.kt
=> fix: [ANDROAPP-5746] Adding file from device's public Download folder crash

app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt, form/src/main/java/org/dhis2/form/bindings/RuleExtensions.kt
=> ANDROAPP-5743-Bug-Calculated-variables-save-integer-values-with-.0

form/src/main/java/org/dhis2/form/data/FormValueStore.kt, form/src/test/java/org/dhis2/form/data/FormValueStoreTest.kt
=> fix: [ANDROAPP-5700] save enrollment orgUnit

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/AnalyticsTeiSettingsToGraph.kt
=> fix: [ANDROAPP-5742] get date position for analytics graph

app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/providers/InputFieldsProvider.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/intent/FormIntent.kt, form/src/main/java/org/dhis2/form/ui/provider/DisplayNameProviderImpl.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/AgeProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/DateProvider.kt, form/src/test/java/org/dhis2/form/ui/provider/DisplayNameProviderImplTest.kt
=> fix: [ANDROAPP-5740] Display error correctly when date or time is incomplete

app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
=> fix: [ANDROAPP-5604] set state when sharing QR

form/src/main/java/org/dhis2/form/data/EnrollmentRuleEngineRepository.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/InputsForTextValueTypeProvider.kt
=> fix: [ANDROAPP-5570] Program rules execute when enrollment data is updated

stock-usecase/src/main/java/org/dhis2/android/rtsm/data/models/TransactionItem.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/MetadataManager.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/MetadataManagerImpl.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/model/SettingsUiState.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/HomeScreen.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/DropdownComponents.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/FilterComponents.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/MainContent.kt, stock-usecase/src/main/res/values/strings.xml, stock-usecase/src/test/java/org/dhis2/android/rtsm/data/DataElementFactory.kt, stock-usecase/src/test/java/org/dhis2/android/rtsm/ui/home/HomeViewModelUnitTest.kt
=> feat: [ANDROAPP-5726] RTS workflow needs to allow for translating the 3 transaction types

stock-usecase/src/main/java/org/dhis2/android/rtsm/coroutines/StockDispatcherProvider.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/data/models/SearchResult.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockManager.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockManagerImpl.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
=> fix: [ANDROAPP-5567] Stock use-case table now show full list of teis

commons/build.gradle.kts, dhis2_android_maps/build.gradle.kts, gradle/libs.versions.toml
=> feat [ANDROAPP-5824] Update-SDK-to-1.9.1-20231228.075857-13

app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt, commons/src/main/java/org/dhis2/commons/filters/workingLists/WorkingListChipGroup.kt
=> fix: [ANDROAPP-5716] responsive filters on events list

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepositoryTest.kt
=> fix: [ANDROAPP-5803/5630] ignore deleted events on schedule creation

form/src/main/java/org/dhis2/form/ui/Form.kt
=> fix: [ANDROAPP-5749] focus when changing section

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt, commons/src/main/java/org/dhis2/commons/data/EventViewModel.kt
=> feat: [ANDROAPP-5568] hide program stage behavior

release.info, scripts/generateReleaseNotes.py
=> [Update release notes] Correct typos and delete unnecessary release.info file

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt, compose-table/src/androidTest/java/org/dhis2/composetable/data/TableInputUiData.kt, compose-table/src/androidTest/java/org/dhis2/composetable/ui/TextInputUiTest.kt, compose-table/src/main/java/org/dhis2/composetable/model/TextInputModel.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TextInput.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
=> feat: [ANDROAPP-5290] Adds helpertext to table's input field

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
=> fix: [ANDROAPP-5802] scheduling dialog not displayed

app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
=> fix: CI fix for new date picker selection

app/src/androidTest/java/org/dhis2/usescases/form/FormIntents.kt, app/src/androidTest/java/org/dhis2/usescases/form/FormTest.kt
=> fix FormTest

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java, commons/src/main/java/org/dhis2/commons/featureconfig/data/FeatureConfigRepositoryImpl.kt
=> feat: [ANDROAPP-5984] Set compose forms as default

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
=> fix: [ANDROAPP-5802] scheduling program stages

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
=> [ANDROAPP-5823] fix black screen when qr is read

app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java, app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java, app/src/main/res/layout/enrollment_activity.xml, commons/src/main/java/org/dhis2/commons/date/DateUtils.java, form/src/main/java/org/dhis2/form/data/DataEntryRepository.kt, form/src/main/java/org/dhis2/form/data/EnrollmentRepository.kt, form/src/main/java/org/dhis2/form/data/EventRepository.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/data/FormValueStore.kt, form/src/main/java/org/dhis2/form/data/metadata/EnrollmentConfiguration.kt, form/src/main/java/org/dhis2/form/model/FieldUiModel.kt, form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt, form/src/main/java/org/dhis2/form/model/SectionUiModelImpl.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactory.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt, form/src/main/java/org/dhis2/form/ui/Form.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/DateProvider.kt, form/src/test/java/org/dhis2/form/data/EnrollmentRepositoryTest.kt
=> feat: [ANDROAPP-5930] move details information to the registration form

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/AgeProvider.kt
=> fix: [ANDROAPP-5800] search page corrections

app/src/androidTest/java/org/dhis2/common/filters/FiltersRobot.kt, app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt, app/src/androidTest/java/org/dhis2/usescases/filters/FilterTest.kt, app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/EventWithoutRegistrationRobot.kt, app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/SyncFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt, app/src/androidTest/java/org/dhis2/usescases/programevent/robot/ProgramEventsRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListIdlingResourceSingleton.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListPresenter.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
=> [ANDROAPP-5911] Fix paging3 mapping

form/src/main/java/org/dhis2/form/data/EventRepository.kt, form/src/test/java/org/dhis2/form/data/EventRepositoryTest.kt
=> [ANDROAPP-5931] Collapse event details and cat combo sections if completed

app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardViewModel.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5974)
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5996)
=> Androapp 5996 error in timeline view when there are no events created

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
=> fix: [ANDROAPP-5988] crash when returning to dashboard event list

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailLiveAdapter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/ui/mapper/TEIEventCardMapper.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/TeiDetailDashboard.kt, app/src/main/res/layout/item_event.xml
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5790)
=> fix event card item margins

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
=> fix: [ANDROAPP-5982] "All [TE Type]" search and relationship search crash

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
=> ANDROAPP-6005-defect-program-stages-cards-missalignement

app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardViewModel.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/res/layout-land/fragment_tei_data.xml, app/src/main/res/layout/fragment_tei_data.xml, app/src/main/res/layout/fragment_tei_data_card_front.xml
=> fix: [ANDROAPP-5923] All enrollment screen crash

.github/workflows/release-start.yml
=> Update release start job

app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt, app/src/main/java/org/dhis2/data/forms/dataentry/ValueStore.kt, app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RuleEngineExtensions.kt, dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RulesRepository.kt, form/src/main/java/org/dhis2/form/bindings/RuleExtensions.kt, form/src/main/java/org/dhis2/form/data/FormValueStore.kt, form/src/main/java/org/dhis2/form/data/RulesRepository.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/rules/RuleValidationHelperImpl.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/utils/RuleExtensions.kt
=> fix: [ANDROAPP-5981]  the app crashes randomly when scheduling new events in tracker program

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt
=> fix: [ANDROAPP-6006] update changes on dashboard

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt, ui-components/src/main/java/org/dhis2/ui/MetadataIcon.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6018)
=> fix icon size and alignment of program stage item

app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchResult.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt, commons/src/main/java/org/dhis2/commons/data/SearchTeiModel.java
=> fi: [ANDROAPP-6004] All {TE Type} search now show too many result.

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/searchparameters/model/SearchParametersUiState.kt
=> fix: [ANDROAPP-6017] only searched fields on searched bar

app/src/main/java/org/dhis2/App.java
=> add anr reports in sentry

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/domain/ConfigureEventDetails.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt, app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/troubleshooting/TroubleshootingRepository.kt, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImplTest.kt, app/src/test/java/org/dhis2/usescases/main/program/ProgramRepositoryImplTest.kt, app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventMapperTest.kt, app/src/test/java/org/dhis2/usescases/programstageselection/ProgramStageSelectionPresenterTest.kt, commons/src/main/java/org/dhis2/commons/resources/MetadataIconProvider.kt, form/src/main/java/org/dhis2/form/data/EventRepository.kt, form/src/main/java/org/dhis2/form/data/metadata/EnrollmentConfiguration.kt
=> [ANDROAPP-6007] Use default color in metadata icons

compose-table/src/main/java/org/dhis2/composetable/ui/ItemValues.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableItemRow.kt
=> fix: [ANDROAPP-6024] table resize dimensions

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt
=> fix: [ANDROAPP-5923] All enrollments page not displaying

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeFragment.kt
=> fix: [ANDROAPP-6038] improved management for  Cancel event in OU dialog 

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardViewModel.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardViewModelTest.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt, commons/src/main/java/org/dhis2/commons/data/EventViewModel.kt
=> fix: [ANDROAPP-6011] freeze getting dashboard events

app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
=> [ANDROAPP-6055] ANR: access localdatastore in background thread

app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt, commons/src/main/java/org/dhis2/commons/date/DateExtensions.kt
=> fix: [ANDROAPP-6091] days to scheduled day

app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/datasetList/DataSetListViewModel.kt
=> fix: [ANDROAPP-6053] ANR on dataset list

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/main/java/org/dhis2/data/service/SyncGranularWorker.kt, app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenter.kt, app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
=> [ANDROAPP-5712] Update sync dialog when reopened

app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt, app/src/test/java/org/dhis2/bindings/TEICardExtensionsTest.kt, commons/src/main/java/org/dhis2/commons/bindings/TEICardExtensions.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselTeiHolder.kt, ui-components/src/main/java/org/dhis2/ui/MetadataIconData.kt
=> fix: [ANDROAPP-6110] crash in program default metadata icon

form/src/main/java/org/dhis2/form/ui/provider/inputfield/CheckBoxProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/CoordinatesProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/RadioButtonProvider.kt
This PR fix the focus handling of ui components.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5951)
=> fix component focus requester

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/res/values/strings.xml
=> [ANDROAPP-6106] Replace enrollment label with custom one

app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
=> Fix IndexOutOfBounds exception in SyncStatusDialog

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
=> [ANDROAPP-6012] Display validation errors

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepository.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6061)
=> Skip OU selection for single option in event creation

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
=> fix: [ANDROAPP-6081] set current date for new enrollment

app/src/main/res/layout/activity_login.xml
=> [ANDROAPP-5949] OpenID login button overlaps with "Manage accounts" button

commons/src/main/java/org/dhis2/commons/bindings/FileExtensions.kt
IndexoutofBoundsException when finding public download
=> Crash on file download for public folders

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepository.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt, app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/data/EventDetailsRepositoryTest.kt
=> [ANDROAPP-5787] Use search scope in a referral

Jenkinsfile, scripts/browserstackJenkins.sh, scripts/browserstackJenkinsCompose.sh, scripts/browserstackJenkinsForm.sh
=> browserstack build tag

compose-table/src/main/java/org/dhis2/composetable/ui/extensions/LazyListScopeExtensions.kt
=> [ANDROAPP-5869] Provide different keys for fixedStickyHeader

app/src/main/java/org/dhis2/utils/customviews/PeriodDialogInputPeriod.java
=> fix: [ANDROAPP-5883] periods when orgunit is closed

form/src/main/java/org/dhis2/form/extensions/FieldUiModelExtensions.kt
=> [ANDROAPP-5757] Field with error can't be disabled

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/searchparameters/SearchParametersScreen.kt, app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt
=> fix: [ANDROAPP-6062] clear search fields when required attributes to search

dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselLayoutManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/carousel/CarouselTeiHolder.kt, dhis2_android_maps/src/main/res/layout/item_carousel_tei.xml
=> fix: [ANDROAPP-5956] Map features usable after expanding and collapsing a card

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
=> fix: [ANDROAPP-6050] remove program name when scheduling event

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt
=> chore: [ANDROAPP-6139] Ignore flaky test

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/SyncFlowRobot.kt, app/src/main/java/org/dhis2/usescases/development/ConflictGenerator.kt
=> test: [ANDROAPP-6139] fix sync flow test

.github/workflows/continuous-delivery.yml
=> ci: [ANDROAPP-6165] add continuous-delivery job to github

app/src/main/java/org/dhis2/usescases/settings/ui/ExportOption.kt, ui-components/src/main/java/org/dhis2/ui/dialogs/alert/AlertDialog.kt
…ontainer, change dp paddings to mobile ui Spacings, change Drawable resource Icon to Material Icon
=> fix: [ANDROAPP-6146] modify start padding for download share button

app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt
=> fix: [ANDROAPP-6175] TeiDataFragment keeps reloading in landscape

app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt, commons/src/main/java/org/dhis2/commons/date/DateExtensions.kt
=> fix: [ANDROAPP-6174] Schedule date on tei card is formatted correctly

app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
=> fix: [ANDROAPP-6088] scroll to top when update list

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/TableDataToTableModelMapper.kt, app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt
=> fix: [ANDROAPP-5869] duplicated indicators table

app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
=> fix: [ANDROAPP-6184] Prevent app crashes when delete local data dialog in shown and device is rotated

app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt
=> fix: [ANDROAPP-6197] Incorrect header in TEI Dashboard card

form/src/main/java/org/dhis2/form/ui/provider/inputfield/DateProvider.kt
=> fix: [ANDROAPP-6179] Missing date edition warning

app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/SearchScreenConfigurator.kt
=> fix: [ANDROAPP-6183] Don't load analytics if map tab is selected

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipRepositoryImpl.kt
=> fix: [ANDROAPP-6116] respect relationship constraints

app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
=> fix: [ANDROAPP-6184] crash on delete data dialog callback

form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
=> fix: [ANDROAPP-6179] Do not save value if it has not changed in form on focus event

commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeFragment.kt
=> fix: [ANDROAPP-6225] Org. Unit dialog crashes on device rotation

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt, app/src/main/res/values/strings.xml, compose-table/src/androidTest/java/org/dhis2/composetable/TableRobot.kt, compose-table/src/androidTest/java/org/dhis2/composetable/ui/DataSetTableUiTest.kt, compose-table/src/main/java/org/dhis2/composetable/TableScreenState.kt, compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/ManageStockViewModel.kt
…with misconfiguration message
=> fix: [ANDROAPP-6158] Shows messages when data set section is empty

.gitignore, app/build.gradle.kts, app/src/androidTest/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/EventInitialTest.kt, build.gradle.kts, commons/build.gradle.kts, compose-table/build.gradle.kts, compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt, dhis2-mobile-program-rules/build.gradle.kts, dhis2_android_maps/build.gradle.kts, dhis_android_analytics/build.gradle.kts, form/build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, stock-usecase/build.gradle.kts, ui-components/build.gradle.kts, ui-components/src/main/java/org/dhis2/ui/inputs/FileInput.kt, viewpagerdotsindicator/build.gradle.kts
=> fix: [ANDROAPP-6169] Update gradle and kotlin version

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt
=> fix: [ANDROAPP-6277] Working lists not filtering search results

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/mapView/SearchTEMap.kt
=> fix: [ANDROAPP-6285] Crash when selecting map in landscape search screen

commons/src/main/java/org/dhis2/commons/date/DateUtils.java, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt
…oth in field and in save pop up
=> fix: [ANDROAPP-6305] show error if date has incorrect date Format 

RELEASE.md, gradle/libs.versions.toml, whatsnew/whatsnew-en-US
=> build: update 3.0.0.2 release notes

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/programevent/robot/ProgramEventsRobot.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTestNoComposable.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/ui/mapper/EventCardMapper.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTeiViewModelFactory.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/ui/mapper/TEIEventCardMapper.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt, app/src/main/res/layout/item_dashboard_program.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModelTest.kt, commons/src/main/res/values/strings.xml
=> fix: [ANDROAPP-6315] adapt List card mappers to new mobile ui key value functionality

app/src/main/java/org/dhis2/usescases/settings/ui/ExportOption.kt
=> fix: [ANDROAPP-6212] write permission in android 13

app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListViewModel.kt, app/src/test/java/org/dhis2/usescases/programEventDetail/eventList/EventListViewModelTest.kt
=> fix: [ANDROAPP-6272] update displayOrgUnitName value using mutable live data

app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.kt
=> fix: [ANDROAPP-6346] ANR when check item on getItemViewType

app/src/main/java/org/dhis2/usescases/searchTrackEntity/searchparameters/SearchParametersScreen.kt, app/src/main/res/values/strings.xml, compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt
=> fix: [ANDROAPP-6037] Show message when TrackedEntity Type does not have searchable attributes

compose-table/src/main/java/org/dhis2/composetable/ui/TableCell.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TableDimensions.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TextInput.kt
=> fix: [ANDROAPP-6380] table cell bringIntoView margin

app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt
Following https://dhis2.atlassian.net/wiki/spaces/AQ/pages/433946636/Plan+Automatize+Testing document align Test cases with instrumentation testing, This is the refactor to the login screen which reduces potentially Login test execution time from 74 seg to 28 seg
=> test: [ANDROAPP-6393] Refactor Logint test to match Test cases

app/src/androidTest/java/org/dhis2/common/matchers/RecyclerviewMatchers.kt, app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/robot/FilterRobot.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTestNoComposable.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.kt, commons/src/main/res/layout/filter_enrollment_status.xml
=> test: [ANDROAPP-6340] remove recycler of search and fix SearchTETest

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java, app/src/main/java/org/dhis2/usescases/searchTrackEntity/listView/SearchTEList.kt
=> [ANDROAPP-6318] Restore recyclerview scroll state

app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListViewModel.kt
=> [ANDROAPP-6417] Can't click same card twice in event list

app/src/main/AndroidManifest.xml
=> [ANDROAPP-6415] Login crash after rotation

app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/mapView/SearchTEMap.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.kt, commons/src/main/java/org/dhis2/commons/featureconfig/model/Feature.kt, commons/src/main/java/org/dhis2/commons/featureconfig/model/FeatureState.kt, commons/src/main/java/org/dhis2/commons/locationprovider/LocationProviderImpl.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/location/AccuracyIndicator.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/location/AccuracyIndicatorState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/location/MapLocationEngine.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/DefaultMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/EventMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/MapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/RelationshipMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/TeiMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt, dhis2_android_maps/src/main/res/layout/activity_map_selector.xml
=> [ANDROAPP-5165] fix accuracy indicator comments

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/androidTest/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorRobot.kt
=> ci: [ANDROAPP-6443] fix flaky tests

app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt, app/src/androidTest/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorRobot.kt
https://dhis2.atlassian.net/browse/ANDROAPP-6455
=> test: [ANDROAPP-6455] Update login flow

form/src/main/java/org/dhis2/form/data/FormRepository.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/provider/LegendValueProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/LegendValueProviderImpl.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/test/java/org/dhis2/form/ui/DataEntryIntegrationTest.kt
=> feat: [ANDROAPP-5688] update legend value after half second

app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowTest.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardProgramModel.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/ui/mapper/TeiDashboardCardMapper.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/teiDashboard/ui/mapper/InfoBarMapperTest.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/ui/mapper/TEIDetailMapperTest.kt
=> feat: [ANDROAPP-5244] add TEI owned by org unit

app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeRepositoryTest.kt, app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeViewModelTest.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OURepositoryConfiguration.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeRepository.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModel.kt
=> fix: [ANDROAPP-6424] Show parents when expanding org unit branches

app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModelFactory.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModelTest.kt
Fixes: https://dhis2.atlassian.net/browse/ANDROAPP-6229?focusedCommentId=202990
=> Set current date as event date when entering event in `SchedulingDialog`

commons/src/main/java/org/dhis2/commons/featureconfig/data/FeatureConfigRepositoryImpl.kt
=> fix: [ANDROAPP-6479] fix crash when logging out

stock-usecase/build.gradle.kts, stock-usecase/src/main/java/org/dhis2/android/rtsm/di/AppModule.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/AnalyticsDependencies.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/HomeViewModel.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/model/SettingsUiState.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/AnalyticsScreen.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/HomeScreen.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/BackdropComponent.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/Toolbar.kt, stock-usecase/src/test/java/org/dhis2/android/rtsm/data/GroupAnalyticsFactory.kt, stock-usecase/src/test/java/org/dhis2/android/rtsm/ui/home/HomeViewModelUnitTest.kt
=> feat: [ANDROAPP-5841] Add BottomNavigation bar for analytics screen

app/src/main/java/org/dhis2/data/server/ServerModule.kt, app/src/main/java/org/dhis2/data/service/SyncStatusController.kt, app/src/main/java/org/dhis2/data/service/SyncStatusData.kt, app/src/main/java/org/dhis2/usescases/general/SessionManagerActivity.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt, app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramUi.kt, app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListActivity.java, app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java, app/src/main/res/drawable/ic_download_off.xml, app/src/test/java/org/dhis2/usescases/main/program/ProgramViewModelTest.kt
=> fix: [ANDROAPP-5394] home screen design fixes

app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
=> ci: ignore flaky test

app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialogUi.kt
=> fix: [ANDROAPP-6525] Scheduling dialog's header fix

app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinatesView.java, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/EventDetailsFragment.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/domain/GetNewEventCreationTypeOptions.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/ProgramConfigurationRepositoryTest.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/domain/GetNewEventCreationTypeOptionsTest.kt, commons/src/main/java/org/dhis2/commons/data/ProgramConfigurationRepository.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/di/Injector.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/usecases/MapStyleConfiguration.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt, dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapSelectorViewModelTest.kt, dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapStyleConfigurationTest.kt, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/FormViewFragmentFactory.kt
=> feat: [ANDROAPP-6230] Disable manual location capturing when configured 

dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/usecases/MapStyleConfiguration.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt
=> feat: [ANDROAPP-6115] implement forced location accuracy

form/src/main/java/org/dhis2/form/ui/FormView.kt
=> fix: [ANDROAPP-6555] don't allow to save form with mandatory fields missing

dhis2_android_maps/src/main/java/org/dhis2/maps/api/NominatimGeocoderApi.kt, gradle/libs.versions.toml
The SDK changed how attributes for building http requests are provided, causing some lines in the app to be updated accordingly.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6583
Update required parameters of attribute function
=> fix: [ANDROAPP-6583] fix usage of http service attribute function due to changes in the sdk

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
=> fix: [ANDROAPP-6532] Set online/offline parameter for teis in search repository correctly

app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.kt
=> fix: [ANDROAPP-6507] IndexOutOfBounds exception on search

form/src/main/java/org/dhis2/form/data/FormRepository.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/data/FormValueStore.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/FormViewModelFactory.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryImplTest.kt, form/src/test/java/org/dhis2/form/data/FormRepositoryIntegrationTest.kt, form/src/test/java/org/dhis2/form/integration/ProgramRulesTest.kt, form/src/test/java/org/dhis2/form/ui/DataEntryIntegrationTest.kt, form/src/test/java/org/dhis2/form/ui/FormViewModelTest.kt
=> fix: [ANDROAPP-6520] save complete event to Preferences from form module

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt
=> fix: [ANDROAPP-6539] Online search nows executes

.tx/config
map new languages: ar_EG: ar-rEG, sw_TZ: sw-rTZ, hi_IN: hi, en_US: en-rUS, ar_IQ: ar-rIQ,
ko_KR: ko-rKR, zh_HK: zh-rHK, ar_SD: ar-rSD
=> ci: [ANDROAPP6607] Update new languages in transifex

app/build.gradle.kts, build.gradle.kts, dhis2_android_maps/src/main/java/org/dhis2/maps/api/GeocoderApi.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/api/NominatimGeocoderApi.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/camera/CalculateCameraAnimationDuration.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/camera/CameraExtension.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/camera/MapSelectorZoomHandler.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/extensions/MapExtensions.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/geometry/FeatureExtensions.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/DefaultMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/CameraUpdateData.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapData.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/usecases/GeocoderSearch.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/usecases/GeocoderSearchImpl.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/utils/GetMapData.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/utils/MapListeners.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/SelectedLocation.kt, dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapSelectorViewModelTest.kt
=> Androapp 6551

gradle.properties
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6592)
Remove keystore credentials
=> chore: [ANDROAPP-6592] Remove keystore credentials

dhis2_android_maps/src/main/java/org/dhis2/maps/extensions/FeatureExtensions.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/layer/types/PlacesMapLayer.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt
=> fix: [ANDROAPP-6604] pin duplicated

dhis2_android_maps/src/main/java/org/dhis2/maps/api/NominatimGeocoderApi.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/DefaultMapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt
=> fix: [ANDROAPP-6606] Improve map search and search results

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/model/StoreResult.kt, form/src/test/java/org/dhis2/form/integration/ProgramRulesTest.kt
=> fix: [ANDROAPP-6565] Rebuild rule engine context

dhis2_android_maps/src/main/java/org/dhis2/maps/camera/MapSelectorZoomHandler.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/geometry/polygon/PolygonAdapter.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt, dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapSelectorViewModelTest.kt
=> fix: [ANDROAPP-6612] Fix zoom on polygon coordinates

commons/src/main/AndroidManifest.xml, commons/src/main/java/org/dhis2/commons/locationprovider/LocationProviderImpl.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/managers/MapManager.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorActivity.kt
=> fix: [ANDROAPP-6605] Use Network provider for location services

dhis2_android_maps/src/main/java/org/dhis2/maps/api/NominatimGeocoderApi.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/NominatimLocation.kt
=> rename displayName property on NominatimLocation

app/src/main/java/org/dhis2/usescases/main/MainModule.kt
=> fix: [ANDROAPP-6617] inject FilterManager on provideDeleteUserData

dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt
=> fix: [ANDROAPP-6635] allow manual selection when gps is off

dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt
Hide search on polygons
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6647)
=> fix: [ANDROAPP-6647] hide search on polygons

app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/BackdropManager.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/SearchScreenConfigurator.kt, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/fragment_compose_holder.xml
integrate navigation bar animation in release 3.1.0
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6580)
=> Fix navigation bar animation (#3859)

commons/src/main/java/org/dhis2/commons/dialogs/imagedetail/ImageDetailActivity.kt, commons/src/main/res/values-es/strings.xml, commons/src/main/res/values/strings.xml, form/src/main/java/org/dhis2/form/ui/FormView.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/dialog/QRDetailBottomDialog.kt, form/src/main/res/values/strings.xml
=> fix: [ANDROAPP-6508] Files and images downloaded on devices lower than Android 10

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipMapsRepository.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipMapsRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapItemHorizontalList.kt
=> fix: [ANDROAPP-6634] relationship map navigation

dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RuleEngineHelper.kt
When attributes updates, program rules where not executing, now program rules runs when attributes changes.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6565)
=> fix: [ANDROAPP-6565] refresh program rules update

commons/build.gradle.kts, dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt, dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapSelectorViewModelTest.kt
=> fix: [ANDROAPP-6622] Add progress to search location

dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt
=> fix: [ANDROAPP-6646] Location/accuracy visibility does not affect map size

app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/troubleshooting/TroubleshootingRepository.kt, dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RuleEngineExtensions.kt, dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RulesRepository.kt, dhis2-mobile-program-rules/src/test/java/org/dhis2/mobileProgramRules/RuleEngineExtensionsTest.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/services/rules/RuleValidationHelperImpl.kt
=> fix: [ANDROAPP-6398] Tei dashbard takes too long to load if option set is too big

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6650)
=> fix: [ANDROAPP-6650] search outside program crash

.github/workflows/deploy-release.yml
Remove auto generate release notes for patch and read from RELEASE.MD file
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6339)
=> ci: [ANDROAPP-6339] Generate Github release through RELEASE.MD

dhis2_android_maps/src/main/java/org/dhis2/maps/camera/MapSelectorZoomHandler.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/model/MapSelectorScreenState.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/utils/GetMapData.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt, dhis2_android_maps/src/test/java/org/dhis2/maps/usecases/MapSelectorViewModelTest.kt
=> fix: [ANDROAPP-6645] Search results are lost when moving or selecting another point

.github/workflows/deploy-release.yml
=> ci: fix deploy release job

app/src/main/java/org/dhis2/usescases/events/EventInfoProvider.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/ui/mapper/TEIEventCardMapper.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt, commons/src/androidTest/java/org/dhis2/commons/date/DateUtilsTest.java, commons/src/main/java/org/dhis2/commons/date/DateUtils.java
=> fix: [ANDROAPP-6644] Display correct style for scheduled overdue events

RELEASE.md, whatsnew/whatsnew-en-US
=> build: 3.1.0.1 Release

form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/MatrixInputProvider.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/MatrixSequentialUtilites.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/SequentialInputProvider.kt
=> fix: [ANDROAPP-6703] refresh selected item when inputCardData list is modified

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt, dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/bindings/LineListingExtensions.kt, dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/bindings/LineListingExtensionsTest.kt
=> fix: [ANDROAPP-6354] line listing filters for orgUnit and category

compose-table/src/main/java/org/dhis2/composetable/ui/DataSetTableScreen.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/managestock/components/ManageStockTable.kt
=> fix: [ANDROAPP-6549] clear input when click save button

compose-table/src/main/java/org/dhis2/composetable/model/TableModel.kt
=> fix: [ANDROAPP-6519] Crash when accessing cell

form/src/main/java/org/dhis2/form/ui/FormView.kt, ui-components/src/main/java/org/dhis2/ui/dialogs/bottomsheet/FieldWithIssue.kt
=> fix: [ANDROAPP-6707] Unable to complete event

Jenkinsfile
=> fix: fix ci

app/src/main/java/org/dhis2/usescases/searchTrackEntity/mapView/SearchTEMap.kt, app/src/main/java/org/dhis2/utils/granularsync/GranularSyncRepository.kt
=> fix: [ANDROAPP-6717] Crash when syncing a TEI from map

.tx/config
Transifex is not updating translations remove new ones
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6607)
=> ANDROAPP-6607

form/src/main/java/org/dhis2/form/ui/FormView.kt
=> fix: [ANDROAPP-6667] form action with warning

dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/bindings/LineListingExtensions.kt, dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/GraphFilters.kt
=> fix: [ANDROAPP-6354] line listing filters

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
=> fix: [ANDROAPP-6418] do not get syncState if there are no conflicts

app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/events/EventInfoProvider.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.kt
=> fix: [ANDROAPP-6753] Event program takes too long to load

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.kt
=> fix: [ANDROAPP-6696] crash when replacing fragment

app/src/main/java/org/dhis2/bindings/StringExtensions.kt, app/src/test/java/org/dhis2/bindings/StringExtensionsTest.kt
=> fix: [ANDROAPP-6759] adapt software update new version check 

app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingDialogUi.kt, form/src/main/java/org/dhis2/form/ui/dialog/QRDetailBottomDialog.kt, tracker/src/main/kotlin/org/dhis2/tracker/relationships/ui/RelationshipsScreen.kt, ui-components/src/main/java/org/dhis2/ui/dialogs/bottomsheet/BottomSheetDialog.kt, ui-components/src/main/java/org/dhis2/ui/dialogs/bottomsheet/DeleteBottomSheetDialog.kt
Add bottom paddings to BottomBar buttons
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6774)
=> fix: [ANDROAPP-6774] add bottom sheet paddings

app/src/main/java/org/dhis2/usescases/searchTrackEntity/ui/mapper/TEICardMapper.kt, commons/src/main/java/org/dhis2/commons/bindings/FileExtensions.kt
=> fix: [ANDROAPP-6771] Crash when creating a tei after searching through org unit

app/src/main/res/layout/activity_dataset_initial.xml, app/src/main/res/layout/activity_event_scheduled.xml
=> fix: [ANDROAPP-6766] correct background color in ScheduledEventActivity

RELEASE.md, gradle/libs.versions.toml, whatsnew/whatsnew-en-US
=> build: 3.1.1 release

app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/mapView/SearchTEMap.kt, dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapItemHorizontalList.kt
=> fix: [ANDROAPP-6758] don't allow title overflow in list cards in map views

compose-table/src/androidTest/java/org/dhis2/composetable/CellTableTest.kt, tracker/src/test/kotlin/org/dhis2/tracker/relationships/RelationshipFakeModels.kt
=> test: remove migrated test in ANDROAPP-6756

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> fix breaking changes from mobile ui

app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
=> fix: [ANDROAPP-6778] avoid json removal on shrinking

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> reexport DB

aggregates/build.gradle.kts, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> fix: designsystem breaking changes

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt
=> fix: [ANDROAPP-6767] set useVertivalTabs from displayoptions

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepository.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetInstanceSectionConfiguration.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetInstanceSectionData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableGroupToTableModel.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/AdaptativeTabRow.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/CategoryToRowTestingData.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> feat: [ANDROAPP-6641] Move a category to rows

Jenkinsfile, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/DisableDataElementGrouping.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/data/DataElementAutoGroupingTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DisableAutomaticGroupingTestingData.kt
=> feat: [ANDROAPP-6638] Disable automatic grouping of data elements

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetInstanceSectionData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableGroupToTableModel.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableModelToTableModelWithTotalRow.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DisableAutomaticGroupingTestingData.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/dataSetTable/PivotTestingData.kt
=> feat: [ANDROAPP-6640] Support pivot categories as rows

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/snackbar/DataSetSnackbarHost.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetInstanceActivity.kt
=> feat: [ANDROAPP-6815] Implement sync functionality into new data sets screen

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, commons/src/main/java/org/dhis2/commons/periods/ui/PeriodSelector.kt
=> feat: [ANDROAPP-6788] animate content size for period selector

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepository.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInput.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/CellInfo.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataValueData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/CellInfoToInputData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableGroupToTableModel.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableModelToTableModelWithUpdatedValue.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/extensions/StringExtensions.kt, form/src/main/java/org/dhis2/form/extensions/FieldUiModelExtensions.kt
=> feat: [ANDROAPP-6855] Add legends to cell

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/mappers/DataSetInstanceToDataSetDetails.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetDetails.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetDetailRow.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, scripts/config_jenkins.init
=> feat: [ANDROAPP-6841] Support feature title and subtitle

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/OptionRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/ui/UIActionHandlerImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInput.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/CellInfoToInputData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/InputData.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInputTest.kt
=> feat: [ANDROAPP-6864] Optionset input

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableGroupToTableModel.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/CategoryToRowTestingData.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/dataSetTable/PivotTestingData.kt
Adding legends (ANDROAPP- 6855) and custom title configurations in datasets
=> [test]: update-testing-db

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/OptionRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.android.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/ui/UIActionHandlerImpl.kt, aggregates/src/commonMain/composeResources/values/strings.xml, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/OptionRepository.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInput.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/CellInfo.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/InputType.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/OptionData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/CellInfoToInputData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/UIActionHandler.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/UiAction.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/provider/IdsProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/provider/ResourceManager.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/InputData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInputTest.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/data/ValueParserImpl.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/data/ValueParser.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/extensions/StringExtensions.kt
=> feat: [ANDROAPP-6832] Implement multiselect value type

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/LegendTestingData.kt
=> test: [ANDROAPP-6855] Automate aggregates legends

aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> feat: [ANDROAPP-6841] Add custom title step to automated test, and unit tests. 

.tx/config, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/data/ValueParserImpl.kt, commonskmm/src/commonMain/composeResources/values/strings.xml, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/data/ValueParser.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/extensions/StringExtensions.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/model/internal/ValueInfo.kt, commonskmm/src/commonTest/kotlin/org/dhis2/mobile/commons/extensions/StringExtensionsTest.kt
=> feat: [ANDROAPP-6878] add boolean type fields to value parser

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/mappers/DataSetInstanceToDataSetDetails.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.android.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetDetailRow.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetInstanceActivity.kt, commons/src/main/java/org/dhis2/commons/di/ResourceManagerModule.kt
=> fix: [ANDROAPP-6867] scroll whole table

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
=> fix: [ANDROAPP-6883] Add imePaddings to InputDialog

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> feat: [ANDROAPP-6880] Dismiss InputDialog and remove cell selection when changing sections

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/mapper/InputDataUiStateMapper.kt
=> fix: [ANDROAPP-6895] Handling Errors in cells

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepository.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInput.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/SetDataValue.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/ValueValidator.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, commons/src/main/java/org/dhis2/commons/featureconfig/data/FeatureConfigRepositoryImpl.kt, commons/src/main/java/org/dhis2/commons/featureconfig/model/Feature.kt
=> fix: [ANDROAPP-6886] Some sections crashed when opened

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt
=> fix: [ANDROAPP-6922] Do not fetch deleted data element values

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/ComputeResizeAction.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/ResizeSaveDimension.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/ResizeAction.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/DataSetScreenState.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetInstanceActivity.kt, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/data/TableDimensionRepositoryImpl.kt, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/di/CommonsModule.android.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/data/TableDimensionRepository.kt
=> fix: [ANDROAPP-6899] Persis table resize action

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/component/ValidationBottomSheet.kt
make complete anyway button fill max width
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-802)
=> fix: [ANDROAPP-6802] Complete anyway button alignment

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/ui/UiActionHandlerImpl.kt
Save org unit only if selected, not with dismiss
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-903)
=> fix: [ANDROAPP-6903] update org unit only if any selected

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepository.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInput.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/SetDataValue.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/ValueValidator.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableGroupToTableModel.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/CategoryToRowTestingData.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> fix: [ANDROAPP-6886] Crash when clicking on pivoted category value cell

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt
=> fix: [ANDROAPP-6882] Cursor slides to the end when typing

build.gradle.kts
Add mavenLocal as a repository
=> add-maven-local

aggregates/src/commonMain/composeResources/values/strings.xml
=> fix: parsing error caused by spaces in attribute

aggregates/src/commonMain/composeResources/values/strings.xml
=> aggregate_resources

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/composeResources/values/strings.xml, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/IndicatorsMapToTableModel.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/provider/ResourceManager.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/dataSetTable/PivotTestingData.kt
=> fix: [ANDROAPP-6911] Set table title labels

aggregates/src/commonMain/composeResources/values/strings.xml
=> fix: change cant by can not in string resources

commons/src/main/res/values/strings.xml
=> fix: fix enrollment plural

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt
=> [ANDROAPP-6882]  Cursor slides to the end when typing

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableModelToTableModelWithTotalRow.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableModelToTableModelWithUpdatedValue.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6889)
=> fix: [ANDROAPP-6889] set absoluteRowIndex as row to compute totals

.github/pull_request_template.md
=> chore: [ANDROAPP-6950] modify pull request template

app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeViewModelTest.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeFragment.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeModule.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModel.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModelFactory.kt
=> fix: [ANDROAPP-6742] Crash when rotating while org unit dialog is displayed

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
=> feat: [ANDROAPP-6936] modify bottom content depending on inputDialog Size

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt
Check unCheck checkbox in multiselect
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-6963)
=> test: [ANDROAPP-6963] check un check multiselect

app/src/main/java/org/dhis2/usescases/general/SessionManagerActivity.kt
=> fix: [ANDROAPP-6872] pin dialog crash

dhis2_android_maps/src/main/java/org/dhis2/maps/usecases/GeocoderSearchImpl.kt
=> fix: [ANDROAPP-6737] handle exception on map search error

.github/workflows/build-release-candidate.yml
Update build release candidate Github Action to generate two APKs 
Update build release candidate Github Action to generate two APKs: DHIS2 and DHIS2PlayServices
=> build-play-services-release

aggregates/src/commonMain/composeResources/values/strings.xml, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
=> fix: [ANDROAPP-6928] Show Info message when dataset is empty or when section is empty

commons/src/main/java/org/dhis2/commons/bindings/ValueExtensions.kt
=> fix: [ANDROAPP-6954] Surround value extension date time formatting with try catch

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetInstanceConfiguration.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetInstanceSectionData.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/mapper/TableGroupToTableModel.kt
=> fix: [ANDROAPP-6981] Incorrect display of greyed out fields

.github/workflows/continuous-delivery.yml
Add sentry token to continuous delivery
=> build: Add sentry token to continuous-delivery.yml

commons/src/main/java/org/dhis2/commons/locationprovider/LocationProviderImpl.kt
=> fix: [ANDROAPP-6970] verify location manager provider exists on device for location requests

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetDetailRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> fix: [ANDROAPP-6959] Verify created dataSet has been completed

app/src/main/java/org/dhis2/data/service/VersionRepository.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
=> fix: [ANDROAPP-7005] Add version checks for permissions in apk download procces

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetInitialRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java, app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeFragment.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/RadioButtonProvider.kt
=> fix: [ANDROAPP-6984] crash when clearing radio button input

.github/workflows/continuous-delivery.yml
Fix continuous delivery APK path
=> fix: remove training suffix on continuous-delivery.yml action

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> test: [ANDROAPP-6929] Form configuration test automation

RELEASE.md, gradle/libs.versions.toml, whatsnew/whatsnew-en-US
Update app version to 3.2.0 and code to 143
=> build: update version code to 143 and version name to 3.2.0

app/src/androidTest/java/org/dhis2/common/BaseRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt, app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt, app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt, app/src/main/java/org/dhis2/usescases/login/LoginModule.kt, app/src/main/java/org/dhis2/usescases/login/LoginRepository.kt, app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/main/java/org/dhis2/usescases/login/LoginViewModelFactory.kt, app/src/main/res/raw/testing_credentials.json, app/src/main/res/raw/training_credentials.json, app/src/test/java/org/dhis2/usescases/login/LoginViewModelTest.kt, app/src/test/java/org/dhis2/usescases/programEventDetail/eventList/EventListViewModelTest.kt
Remove testing credentials on release
Display testing credentials (play services) on training builds.
Display development credentials (instance manager servers) on development builds.
[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-ANDROAPP-7015)
=> ANDROAPP-7015-disable-credentials-on-release

app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/main/java/org/dhis2/usescases/notes/NotesPresenter.kt, app/src/main/res/layout/activity_note_detail.xml
[JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7024).
Add idling resources for asynchronous tasks when creating notes.
=> fix: [ANDROAPP-7024] Add CountingIdlingResourceSingleton in Notes screen

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> ci: [ANDROAPP-6986] replace weekly period

app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.kt, form/src/main/java/org/dhis2/form/data/EventRepository.kt, form/src/main/java/org/dhis2/form/data/metadata/EnrollmentConfiguration.kt, form/src/main/java/org/dhis2/form/data/metadata/FormBaseConfiguration.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/test/java/org/dhis2/form/data/EventRepositoryTest.kt
=> fix: [ANDROAPP-6992] apply optionSet program rules in background thread

aggregates/src/commonMain/composeResources/values/strings.xml
=> refactor: Fix trailing whitespace in strings.xml

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> ci: [ANDROAPP-6986] replace weekly period (#4142)

form/src/main/java/org/dhis2/form/ui/provider/inputfield/DropdownProvider.kt
the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7004).
The optionData was not restarted when it changed.
=> fix: [ANDROAPP-7004] Dropdown option set not displaying correct program rules related actions

commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/logging/Logging.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/logging/Logging.kt, commonskmm/src/desktopMain/kotlin/org/dhis2/mobile/commons/logging/Logging.desktop.kt
[JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7031).
Simple Kotlin Multiplatform logger
=> feat: [ANDROAPP-7031] Implement KMM logging (#4137)

Jenkinsfile, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, scripts/browserstackJenkinsLandscape.sh, scripts/config_jenkins.init
=> test: [ANDROAPP-6986] Set Singlerunner on Landscape testing

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/OptionRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/qrScanner/ScanRepository.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt, dhis2-mobile-program-rules/src/main/java/org/dhis2/mobileProgramRules/RulesRepository.kt, form/src/main/java/org/dhis2/form/data/metadata/FormBaseConfiguration.kt
=> fix: [ANDROAPP-7006] sort options in option set by ascending order

Jenkinsfile, app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt, app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowTest.kt, app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
=> build: deactivate landscape tests in PRs, correct flaky test

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepository.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/CheckCompletionStatus.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataSetCompletionStatus.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/component/ValidationBottomSheet.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/provider/DataSetModalDialogProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/DataSetModalDialogUiState.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/domain/CheckCompletionStatusTest.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
=> fix: [ANDROAPP-6957] Restrict completion of non editable data set instances

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/AdaptativeTabRow.kt
=> fix: [ANDROAPP-6983] Render long section names properly

stock-usecase/src/main/java/org/dhis2/android/rtsm/services/StockManagerImpl.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/utils/AttributeHelper.kt, stock-usecase/src/test/java/org/dhis2/android/rtsm/services/StockManagerTest.kt
=> fix: [ANDROAPP-6524] Option code is use instead of name in stock use case

app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt, app/src/main/java/org/dhis2/data/service/SyncStatusController.kt
=> fix: [ANDROAPP-6930] call onError on complete if syncMetadata fails

app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetDetailRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetInitialRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/dataSetTable/period/ReportPeriodSelectorRobot.kt, app/src/androidTest/java/org/dhis2/usescases/programevent/robot/ProgramEventsRobot.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/robot/FilterRobot.kt, app/src/main/java/org/dhis2/usescases/login/LoginIdlingResource.kt, app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/main/java/org/dhis2/usescases/notes/NotesIdlingResource.kt, app/src/main/java/org/dhis2/usescases/notes/NotesPresenter.kt, commons/src/main/java/org/dhis2/commons/animations/ViewAnimations.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OUTreeViewModel.kt, commons/src/main/java/org/dhis2/commons/orgunitselector/OrgUnitIdlingResource.kt
=> test: [ANDROAPP-6958] add steps in datasetAutomate test

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt
=> fix: [ANDROAPP-6880] Clear selection when dismissing input or clicking done

app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenter.kt, app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
=> fix: [ANDROAPP-7038] Get categoryOptionCombo uids in background

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/UiAction.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/DataSetScreenState.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/InputDataUiState.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/mapper/InputDataUiStateMapper.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt
=> fix: [ANDROAPP-6988] Irregular data set navigation

app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt, app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueActivity.java, app/src/main/res/layout/activity_note_detail.xml, app/src/main/res/layout/activity_program_stage_selection.xml, app/src/main/res/layout/activity_reserved_value.xml
…tail and reserved value activity
=> fix: [ANDROAPP-6987] hide background gradient in XML activities

app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
=> fix: [ANDROAPP-7040] crash when current event is null

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt
=> fix: [ANDROAPP-7044] Concurrent modification exception while applying program rules

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetDetailRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java, app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchNavigator.kt, commons/src/main/java/org/dhis2/commons/filters/FilterManager.java, commons/src/main/java/org/dhis2/commons/filters/periods/ui/viewmodel/FilterPeriodsDialogViewmodel.kt
=> fix: [ANDROAPP-7039] Crash when using event related working list in search screen

Jenkinsfile, run_tests.sh
=> ci: Enable landscape automation pull request

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/InputType.kt
=> fix: [ANDROAPP-7068] Do not request focus if value type is username

commons/src/main/java/org/dhis2/commons/filters/workingLists/WorkingListChipGroup.kt, commons/src/main/java/org/dhis2/commons/filters/workingLists/WorkingListItemSaver.kt
persist selected working list with rememberSavable and using a custom Saver
=> fix: [ANDROAPP-7039] Persist the selected working list across configuration changes.

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> fix: [ANDROAPP-6899] Persist resizing

.github/workflows/release-start.yml, scripts/toml_file_handler.py, scripts/updateDependencyVersions.py, scripts/updateVersionName.py
=> build: [ANDROAPP-7090] Updated release start to include sdk and design develop versions

.github/workflows/release-start.yml, scripts/toml_file_handler.py, scripts/updateDependencyVersions.py, scripts/updateVersionName.py
…pdates during the release process.
=> build: [ANDROAPP-7090] Add release-finish workflow to update release versions name of sdk and design system, and version code

app/src/androidTest/java/org/dhis2/AppTest.kt, app/src/androidTest/java/org/dhis2/common/filters/FiltersRobot.kt, app/src/androidTest/java/org/dhis2/usescases/BaseTest.kt, app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt, app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt, app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.kt, app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
=> build: [ANDROAPP-7086] Fix MainTest Ignored tests

.github/workflows/release-finish.yml, scripts/updateVersionCode.py
…d design system. and update version code automatically
=> build: [ANDROAPP-7090]New release finish job

app/src/main/java/org/dhis2/usescases/login/LoginViewModel.kt, commons/src/main/java/org/dhis2/commons/prefs/PreferenceProvider.kt, commons/src/main/java/org/dhis2/commons/prefs/PreferenceProviderImpl.kt
=> fix: refactor preferences

form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt
=> fix: [ANDROAPP-7099] Call onItemClick after saving value in form dropdown input

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetDetailRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
=> fix: [ANDROAPP-6877] Add verification of re-open functionality to test

RELEASE.md, app/src/main/res/raw/training_credentials.json, gradle/libs.versions.toml, whatsnew/whatsnew-en-US
=> Update version code, sdk, and design system release version

gradle/libs.versions.toml
=> build: update version code

app/proguard-rules.pro
=> chore: [ANDROAPP-7082] Add maps module proguard rules

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
=> fix: [ANDROAPP-7076] Handle null organisation unit in search

app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt, app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt, app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java, commons/src/main/java/org/dhis2/commons/network/NetworkUtils.kt
=> fix: [ANDROAPP-7058] Secure connection status listener

app/src/main/AndroidManifest.xml, commons/src/main/java/org/dhis2/commons/bindings/FileExtensions.kt
=> fix: [ANDROAPP-7061] review external access

.github/dependabot.yml
=> Update dependencies only with major and minor versions

.github/workflows/release-finish.yml
=> fix: Remove redundant "release/" prefix in release-finish script 

app/src/androidTest/java/org/dhis2/common/di/TestingInjector.kt, app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/injection/EventDetailsModule.kt, app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java, app/src/main/java/org/dhis2/usescases/general/AbstractActivityContracts.java, app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java, app/src/main/java/org/dhis2/usescases/general/FragmentGlobalAbstract.java, app/src/main/java/org/dhis2/usescases/general/SessionManagerActivity.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.kt, app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailView.kt, app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java, app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt, app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt, app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterTest.kt, commons/src/main/java/org/dhis2/commons/prefs/PreferenceProvider.kt, commons/src/main/java/org/dhis2/commons/prefs/PreferenceProviderImpl.kt, form/src/main/java/org/dhis2/form/data/FormRepository.kt, form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/di/Injector.kt, form/src/main/java/org/dhis2/form/ui/FormViewModel.kt, form/src/main/java/org/dhis2/form/ui/provider/AutoCompleteProviderImpl.kt
the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7055).
=> fix: [ANDROAPP-7055] Remove usage of shared preferences

app/src/main/AndroidManifest.xml
=> fix: [ANDROAPP-7146] remove RedirectUriReceiverActivity declaration from AndroidManifest.xml

app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetDetailRobot.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt, app/src/androidTest/java/org/dhis2/usescases/datasets/dataSetTable/period/ReportPeriodSelectorRobot.kt, commons/src/main/java/org/dhis2/commons/periods/ui/PeriodSelector.kt
the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7026).
=> refactor: [ANDROAPP-7026] make period selection relative in dataset test

app/src/main/java/org/dhis2/data/dhislogic/EnrollmentEventGeneratorRepositoryImpl.kt
=> fix: [ANDROAPP-7115] Set first category option combo for autogenerated events

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/UiAction.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> feat: [ANDROAPP-7117] Add check box tap functionality in cells in data sets

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
=> fix: [ANDROAPP-7075] Reduce bottom padding in tables

aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt
=> fix: [ANDROAPP-7165] Update table dimensions in state when modified

aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/DataSetInstanceRepositoryImpl.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/data/mappers/ValueTypeToInputType.kt, aggregates/src/androidMain/kotlin/org/dhis2/mobile/aggregates/ui/UiActionHandlerImpl.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/di/AggregateModule.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInput.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/CellInfo.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/model/DataElementInfo.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/inputs/InputProvider.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/InputDataUiState.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/states/mapper/InputDataUiStateMapper.kt, aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModel.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/domain/GetDataValueInputTest.kt, aggregates/src/commonTest/kotlin/org/dhis2/mobile/aggregates/ui/viewModel/DataSetTableViewModelTest.kt, commonskmm/build.gradle.kts, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/extensions/WindowExtensions.android.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/extensions/WindowExtensions.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/input/InputExtra.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/input/InputType.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/input/UiAction.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/input/UiActionHandler.kt, commonskmm/src/desktopMain/kotlin/org/dhis2/mobile/commons/extensions/WindowExtensions.desktop.kt
Move some classes for inputs to commonsKmm in order to create generic InputProvider
=> ANDROAPP-7147-Part1-Move-InputUi-classes [skip size]

commons/src/main/java/org/dhis2/commons/bindings/SdkModelsExtensions.kt, compose-table/src/main/java/org/dhis2/composetable/ui/Table.kt, compose-table/src/main/java/org/dhis2/composetable/ui/TextInput.kt, stock-usecase/src/main/java/org/dhis2/android/rtsm/ui/home/screens/components/Toolbar.kt
Add imePadding to TextInput component to respect keyboard layout
=> ANDROAPP-7167-Keyboard-hides-input-dialog

.github/dependabot.yml
Refine dependency ignore rules for designsystem.
=> Update dependabot.yml to modify ignored dependencies

app/src/androidTest/assets/mocks/loginconfig/legacy_flow_config.json, app/src/androidTest/java/org/dhis2/usescases/login/LoginRobot.kt, app/src/androidTest/java/org/dhis2/usescases/login/LoginTest.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/extensions/CoroutineExtensions.kt, login/src/androidMain/kotlin/org/dhis2/mobile/login/main/ui/contracts/ServerQRReader.android.kt, login/src/commonMain/composeResources/values-ar/strings.xml, login/src/commonMain/composeResources/values-cs/strings.xml, login/src/commonMain/composeResources/values-es-rES/strings.xml, login/src/commonMain/composeResources/values-es/strings.xml, login/src/commonMain/composeResources/values-fr/strings.xml, login/src/commonMain/composeResources/values-lo/strings.xml, login/src/commonMain/composeResources/values-nl/strings.xml, login/src/commonMain/composeResources/values-pt/strings.xml, login/src/commonMain/composeResources/values-ru/strings.xml, login/src/commonMain/composeResources/values-uk/strings.xml, login/src/commonMain/composeResources/values-uz/strings.xml, login/src/commonMain/composeResources/values-vi/strings.xml, login/src/commonMain/composeResources/values-zh-rCN/strings.xml, login/src/commonMain/composeResources/values-zh/strings.xml, login/src/commonMain/composeResources/values/strings.xml, login/src/commonMain/kotlin/org/dhis2/mobile/login/accounts/ui/viewmodel/AccountsViewModel.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/domain/model/LoginScreenState.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/domain/usecase/GetInitialScreen.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/contracts/ServerQRReader.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/screen/LoginScreen.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/screen/ServerValidationContent.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/viewmodel/LoginViewModel.kt, login/src/desktopMain/kotlin/org/dhis2/mobile/login/main/ui/contracts/ServerQRReader.desktop.kt
Link the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7182).
Implement ValidateServer screen
=> feat: [ANDROAPP-7182] ValidateServer screen

commons/src/main/java/org/dhis2/commons/network/NetworkUtils.kt, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/di/CommonsModule.android.kt, commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/network/NetworkStatusProviderImpl.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/network/NetworkStatusProvider.kt
=> feat: [ANDROAPP-7215] Move NetworkUtils isOnline to commonsKmm

app/src/main/AndroidManifest.xml, app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt, gradle/libs.versions.toml, login/build.gradle.kts, login/src/androidMain/kotlin/org/dhis2/mobile/login/main/ui/screen/WebAuthenticator.android.kt, login/src/commonMain/composeResources/values/strings.xml, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/di/LoginModule.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/navigation/AppLinkNavigation.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/screen/LoginScreen.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/screen/WebAuthenticator.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/viewmodel/LoginViewModel.kt, login/src/commonTest/kotlin/org/dhis2/mobile/login/main/ui/viewmodel/LoginViewModelTest.kt, login/src/desktopMain/kotlin/org/dhis2/mobile/login/main/ui/screen/WebAuthenticator.desktop.kt
Link the [JIRA issue](https://dhis2.atlassian.net/browse/ANDROAPP-7200).
Implement OAuth flow part 1 launching custom tabs
=> ANDROAPP-7200-Implement-OAuth-login-flow

app/src/androidTest/java/org/dhis2/usescases/settings/SettingsRobot.kt, app/src/main/java/org/dhis2/usescases/settings/SettingsRepository.kt, app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.kt, app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.kt, app/src/main/java/org/dhis2/usescases/settings/domain/GetSettingsState.kt, app/src/main/java/org/dhis2/usescases/settings/models/SettingsState.kt, app/src/main/java/org/dhis2/usescases/settings/ui/AppUpdateSettingItem.kt, app/src/main/java/org/dhis2/usescases/settings/ui/ReservedValuesSettingItem.kt, app/src/main/java/org/dhis2/usescases/settings/ui/SettingItem.kt, app/src/main/java/org/dhis2/usescases/settings/ui/SettingsScreen.kt, app/src/main/java/org/dhis2/usescases/settings/ui/SyncDataSettingItem.kt, app/src/main/java/org/dhis2/usescases/settings/ui/SyncMetadataSettingItem.kt, app/src/main/java/org/dhis2/usescases/settings/ui/SyncParametersSettingItem.kt, app/src/main/java/org/dhis2/usescases/settings/ui/SyncPeriodLabel.kt, app/src/main/java/org/dhis2/usescases/settings/ui/TwoFASettingItem.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/settings/SyncManagerPresenterTest.kt, commons/src/main/res/values/colors.xml
=> feat: [ANDROAPP-7170] Settings screen design update [skip size]

app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepository.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt, app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/ui/mapper/TEIEventCardMapper.kt, app/src/main/res/values/strings.xml, app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryTest.kt, commons/src/main/java/org/dhis2/commons/data/EventModel.kt
=> fix: [ANDROAPP-7145] Scheduled events not reassigned correctly after patient transfer on android v3.2.0

form/src/main/java/org/dhis2/form/data/FormRepositoryImpl.kt, form/src/main/java/org/dhis2/form/model/FieldUiModel.kt, form/src/main/java/org/dhis2/form/model/FieldUiModelImpl.kt, form/src/main/java/org/dhis2/form/model/SectionUiModelImpl.kt, form/src/main/java/org/dhis2/form/ui/FieldViewModelFactoryImpl.kt, form/src/main/java/org/dhis2/form/ui/provider/inputfield/FieldProvider.kt
=> fix: [ANDROAPP-7216] option related program rules on multitext value type

commonskmm/src/androidMain/kotlin/org/dhis2/mobile/commons/resources/Resources.android.kt, commonskmm/src/commonMain/kotlin/org/dhis2/mobile/commons/resources/Resources.kt, commonskmm/src/desktopMain/java/org/dhis2/mobile/commons/resources/Resources.desktop.kt, login/src/androidMain/kotlin/org/dhis2/mobile/login/accounts/data/repository/AccountRepositoryImpl.kt, login/src/androidMain/kotlin/org/dhis2/mobile/login/main/data/LoginRepositoryImpl.kt, login/src/commonMain/composeResources/values/strings.xml, login/src/commonMain/kotlin/org/dhis2/mobile/login/accounts/domain/model/AccountModel.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/accounts/ui/screen/AccountItem.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/accounts/ui/screen/AccountsScreen.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/data/LoginRepository.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/di/LoginModule.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/domain/usecase/GetHasOtherAccounts.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/screen/CredentialsScreen.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/states/CredentialsUiState.kt, login/src/commonMain/kotlin/org/dhis2/mobile/login/main/ui/viewmodel/CredentialsViewModel.kt
=> refactor: [ANDROAPP-7205] Redesign Manage Account Screen 

app/build.gradle.kts, build.gradle.kts, commons/src/main/java/org/dhis2/commons/filters/data/FilterBindings.kt, commons/src/main/java/org/dhis2/commons/resources/ColorUtils.kt, gradle.properties
This PR delivers significant build performance improvements and reduces compiler warnings through targeted optimizations and code quality enhancements, with minimal changes to the codebase.
---
| Metric | Before | After | Improvement |
|--------|--------|-------|-------------|
| **Build Time** | 9m 43s (583s) | 7m 9s (429s) | **🚀 26.4% faster** |
| **Time Saved** | - | 2m 34s (154s) | Per full build |
| **Warnings** | 686 | 671 | ✅ 15 eliminated |
| **Files Changed** | - | 5 | Minimal impact |
---
**File:** `app/build.gradle.kts`
Replaced the deprecated Gradle `exec()` method with `ProcessBuilder`, which:
- ✅ Eliminates deprecation warning
- ✅ Adds proper error handling
- ✅ Returns "unknown" as fallback instead of failing
<details>
<summary>View code change</summary>
**Before:**
```kotlin …
```
=> 🚀 Optimize Build Time and Reduce Compiler Warnings
